SELECT
    account,
    lot,
    lotsuff,
    block,
    blocksuf,
    qlfr,
    block_lot,
    status,
    property_descr,
    cycle,
    estimated,
    service_location_name,
    service_address,
    service_phone,
    billing_name,
    billing_address,
    city_state,
    zip_code,
    billing_phone,
    ward,
    street_name,
    current_bal,
    new_charges,
    arrears_30_principal,
    arrears_30_interest,
    arrears_60_principal,
    arrears_60_interest,
    arrears_90_principal,
    arrears_90_interest,
    arrears_total,
    latest_pay_dt,
    pa_flag
FROM JRS2C2M.REP8_AGED_BALANCE
WHERE rpt_dt = NVL($P{Report_Date}, TRUNC(SYSDATE))
ORDER BY account
