CREATE TABLE cisadm.acct_debt_rpt_curr (
    acct_id                              VARCHAR2(40)    NOT NULL,
    coll_cl_cd                           VARCHAR2(40),
    coll_cl_desc                         VARCHAR2(240),
    cr_review_dt                         DATE,
    postpone_cr_rvw_dt                   DATE,
    per_id                               VARCHAR2(40),
    customer_name                        VARCHAR2(200),
    active_sa_count                      NUMBER(18,0),
    debt_cl_count                        NUMBER(18,0),
    sole_debt_cl_cd                      VARCHAR2(16),
    sole_debt_cl_desc                    VARCHAR2(240),
    governed_arrears_ft_count            NUMBER(18,0),
    governed_arrears_sa_count            NUMBER(18,0),
    total_debt                           NUMBER(18,2),
    debt_0_30                            NUMBER(18,2),
    debt_31_60                           NUMBER(18,2),
    debt_61_90                           NUMBER(18,2),
    debt_over_90                         NUMBER(18,2),
    oldest_age_days                      NUMBER(18,0),
    newest_age_days                      NUMBER(18,0),
    oldest_ars_dt                        DATE,
    newest_ars_dt                        DATE,
    last_bill_dt                         DATE,
    coll_proc_count                      NUMBER(18,0),
    latest_coll_proc_id                  VARCHAR2(40),
    latest_coll_proc_cre_dttm            DATE,
    latest_coll_status_flg               VARCHAR2(8),
    latest_coll_status_desc              VARCHAR2(240),
    latest_coll_stat_rsn_flg             VARCHAR2(8),
    latest_coll_proc_tmpl_cd             VARCHAR2(48),
    latest_coll_proc_tmpl_desc           VARCHAR2(240),
    latest_coll_ars_dt                   DATE,
    latest_coll_ars_amt                  NUMBER(18,2),
    wo_proc_count                        NUMBER(18,0),
    latest_wo_proc_id                    VARCHAR2(40),
    latest_wo_proc_cre_dttm              DATE,
    latest_wo_status_flg                 VARCHAR2(8),
    latest_wo_status_desc                VARCHAR2(240),
    latest_wo_stat_rsn_flg               VARCHAR2(8),
    latest_wo_proc_tmpl_cd               VARCHAR2(48),
    latest_wo_proc_tmpl_desc             VARCHAR2(240),
    latest_wo_proc_compl_dt              DATE,
    latest_wo_ars_at_start               NUMBER(18,2),
    latest_wo_ars_at_end                 NUMBER(18,2),
    coll_agy_ref_count                   NUMBER(18,0),
    load_dttm                            TIMESTAMP DEFAULT SYSTIMESTAMP
);
