"""
Governed SQL constants for Oracle C2M BI pipeline.
All queries are SELECT-only with explicit column lists (no SELECT *).
Schema: CISADM for CI_* tables; D1 for device/meter tables (adjust if your C2M uses different owner).
Source of truth for table and column names: Domain Designs.xlsx (D1_DVC, D1_DVC_CFG, D1_INSTALL_EVT, CI_SP, etc.).
See docs/semantic-layer.md and sql/governance_snippets.sql.

Mode: Set RISK_DATA_ENABLED=1 in .env (or environment) to run "Risk Data" queries (Revenue Leakage,
Liquidity Risk, Stale Pending SA) for operational monitoring. When unset, only "Clean Data" is used for financial statements.
"""

# -----------------------------------------------------------------------------
# Usage (legacy): last two billing periods from CI_BSEG
# -----------------------------------------------------------------------------
USAGE_QUERY = """
SELECT bill_dt, amount
FROM (
  SELECT b.bill_dt, b.amount
  FROM CISADM.CI_BSEG b
  WHERE b.FREEZE_SW = 'Y'
    AND b.bill_dt >= ADD_MONTHS(TRUNC(SYSDATE), -3)
    AND b.bill_dt <  TRUNC(SYSDATE) + 1
  ORDER BY b.bill_dt DESC
) WHERE ROWNUM <= 2
"""

# -----------------------------------------------------------------------------
# BI Pipeline: Arrears, Payment Integrity, Bankruptcy, Entity Resolution
# Multi-Layer Validation (Source of Truth):
#   - CI_FT: FREEZE_SW='Y' (audited only; exclude in-progress/canceled), NOT_IN_ARS_SW='N',
#     FT_TYPE not PS/PX (exclude payments), ARS_DT IS NOT NULL (valid arrears date).
#   - CI_SA: Active only (SA_STATUS_FLG='20'). For tenant isolation, join F1_BUS_OBJ when
#     available to verify standard life cycle per SmartCity tenant.
#   - Balance check: HAVING SUM(FT.CUR_AMT) > 0 so paid-off/zero balances are excluded.
# -----------------------------------------------------------------------------
CI_FT_ARREARS_GOLD_FILTER = (
    "FT.FREEZE_SW = 'Y' AND FT.NOT_IN_ARS_SW = 'N' "
    "AND FT.FT_TYPE_FLG NOT IN ('PS', 'PX') AND FT.ARS_DT IS NOT NULL"
)
QUERY_ARREARS_STRATEGIC = """
SELECT
    ACCNT.ACCT_ID,
    ST.DEBT_CL_CD,
    NULLIF(TRIM(DCL.DESCR), '') AS DEBT_CL_DESCR,
    SUM(FT.CUR_AMT) AS TOTAL_DEBT,
    SUM(CASE WHEN (TRUNC(SYSDATE) - FT.ARS_DT) <= 30 THEN FT.CUR_AMT ELSE 0 END) AS DEBT_30_DAYS,
    SUM(CASE WHEN (TRUNC(SYSDATE) - FT.ARS_DT) BETWEEN 31 AND 60 THEN FT.CUR_AMT ELSE 0 END) AS DEBT_60_DAYS,
    SUM(CASE WHEN (TRUNC(SYSDATE) - FT.ARS_DT) > 60 THEN FT.CUR_AMT ELSE 0 END) AS DEBT_OVER_60,
    COUNT(CASE WHEN FT.CUR_AMT > 500 THEN 1 END) AS LARGE_BILL_COUNT
FROM CISADM.CI_FT FT
JOIN CISADM.CI_SA SA ON SA.SA_ID = FT.SA_ID
JOIN CISADM.CI_SA_TYPE ST ON SA.SA_TYPE_CD = ST.SA_TYPE_CD
LEFT JOIN CISADM.CI_DEBT_CL_L DCL
  ON DCL.DEBT_CL_CD = ST.DEBT_CL_CD
 AND DCL.LANGUAGE_CD = 'EN'
JOIN CISADM.CI_ACCT ACCNT ON SA.ACCT_ID = ACCNT.ACCT_ID
WHERE """ + CI_FT_ARREARS_GOLD_FILTER + """
  AND NULLIF(TRIM(SA.SA_STATUS_FLG), '') = '20'
GROUP BY ACCNT.ACCT_ID, ST.DEBT_CL_CD, DCL.DESCR
HAVING SUM(FT.CUR_AMT) > 0
"""

QUERY_ARREARS_BY_ACCT = """
SELECT
    ACCNT.ACCT_ID,
    ST.DEBT_CL_CD,
    NULLIF(TRIM(DCL.DESCR), '') AS DEBT_CL_DESCR,
    SUM(FT.CUR_AMT) AS TOTAL_DEBT,
    SUM(CASE WHEN (TRUNC(SYSDATE) - FT.ARS_DT) <= 30 THEN FT.CUR_AMT ELSE 0 END) AS DEBT_30_DAYS,
    SUM(CASE WHEN (TRUNC(SYSDATE) - FT.ARS_DT) BETWEEN 31 AND 60 THEN FT.CUR_AMT ELSE 0 END) AS DEBT_60_DAYS,
    SUM(CASE WHEN (TRUNC(SYSDATE) - FT.ARS_DT) > 60 THEN FT.CUR_AMT ELSE 0 END) AS DEBT_OVER_60,
    COUNT(CASE WHEN FT.CUR_AMT > 500 THEN 1 END) AS LARGE_BILL_COUNT
FROM CISADM.CI_FT FT
JOIN CISADM.CI_SA SA ON SA.SA_ID = FT.SA_ID
JOIN CISADM.CI_SA_TYPE ST ON SA.SA_TYPE_CD = ST.SA_TYPE_CD
LEFT JOIN CISADM.CI_DEBT_CL_L DCL
  ON DCL.DEBT_CL_CD = ST.DEBT_CL_CD
 AND DCL.LANGUAGE_CD = 'EN'
JOIN CISADM.CI_ACCT ACCNT ON SA.ACCT_ID = ACCNT.ACCT_ID
WHERE """ + CI_FT_ARREARS_GOLD_FILTER + """
  AND NULLIF(TRIM(SA.SA_STATUS_FLG), '') = '20'
  AND ACCNT.ACCT_ID = :acct_id
GROUP BY ACCNT.ACCT_ID, ST.DEBT_CL_CD, DCL.DESCR
HAVING SUM(FT.CUR_AMT) > 0
"""

QUERY_PREMISE_TO_ACCT = """
SELECT DISTINCT SA.ACCT_ID, P.PREM_ID, P.ADDRESS1
FROM CISADM.CI_PREM P
INNER JOIN CISADM.CI_SA SA ON P.PREM_ID = SA.CHAR_PREM_ID
WHERE (P.ADDRESS1_UPR LIKE '%' || UPPER(TRIM(:address)) || '%'
       OR P.ADDRESS1 LIKE '%' || TRIM(:address) || '%')
  AND NULLIF(TRIM(SA.SA_STATUS_FLG), '') = '20'
  AND ROWNUM <= 5
"""

QUERY_CUSTOMER_NAME_TO_ACCT = """
SELECT DISTINCT AP.ACCT_ID, PN.ENTITY_NAME, PN.PER_ID
FROM CISADM.CI_PER_NAME PN
INNER JOIN CISADM.CI_ACCT_PER AP ON PN.PER_ID = AP.PER_ID
WHERE PN.ENTITY_NAME_UPR LIKE '%' || UPPER(TRIM(:customer_name)) || '%'
  AND PN.PRIM_NAME_SW = 'Y'
  AND AP.MAIN_CUST_SW = 'Y'
  AND ROWNUM <= 5
"""

QUERY_DUPLICATE_PAYMENT = """
SELECT b.ACCT_NBR,
       b.ACCT_PAYMENTS_TODAY,
       b.ACCT_PAYMENTS_YESTERDAY,
       'Potential Duplicate Payment' AS ANOMALY_TYPE
FROM (
    SELECT a.ACCT_ID AS ACCT_NBR,
            (SELECT NVL(SUM(ft2.CUR_AMT),0)
             FROM CISADM.CI_FT ft2
             JOIN CISADM.CI_SA sa2 ON sa2.SA_ID = ft2.SA_ID AND NULLIF(TRIM(sa2.SA_STATUS_FLG), '') = '20'
             WHERE sa2.ACCT_ID = a.ACCT_ID
                   AND ft2.REDUNDANT_SW = 'N'
                   AND ft2.FREEZE_SW = 'Y'
                   AND ft2.FT_TYPE_FLG IN ('PS', 'PX')
                   AND TRUNC(ft2.CRE_DTTM) = TRUNC(SYSDATE)
            ) AS ACCT_PAYMENTS_TODAY,
            (SELECT NVL(SUM(ft2.CUR_AMT),0)
             FROM CISADM.CI_FT ft2
             JOIN CISADM.CI_SA sa2 ON sa2.SA_ID = ft2.SA_ID AND NULLIF(TRIM(sa2.SA_STATUS_FLG), '') = '20'
             WHERE sa2.ACCT_ID = a.ACCT_ID
                   AND ft2.REDUNDANT_SW = 'N'
                   AND ft2.FREEZE_SW = 'Y'
                   AND ft2.FT_TYPE_FLG IN ('PS', 'PX')
                   AND TRUNC(ft2.CRE_DTTM) = TRUNC(SYSDATE) - 1
            ) AS ACCT_PAYMENTS_YESTERDAY
    FROM CISADM.CI_ACCT a
) b
WHERE b.ACCT_PAYMENTS_TODAY = b.ACCT_PAYMENTS_YESTERDAY
  AND b.ACCT_PAYMENTS_TODAY <> 0
"""

QUERY_BANKRUPTCY_MONITOR = """
SELECT DISTINCT
    acct.acct_id,
    pym.ars_dt,
    pym.pym_amt
FROM CISADM.ci_acct acct
INNER JOIN CISADM.ci_acct_alert alert ON acct.acct_id = alert.acct_id
    AND alert.alert_type_cd = 'BNKRTPCY'
    AND SYSDATE BETWEEN alert.start_dt AND alert.end_dt
INNER JOIN (
    SELECT sa.acct_id, ft.ars_dt, NVL(SUM(ft.cur_amt),0) AS pym_amt
    FROM CISADM.ci_ft ft
    JOIN CISADM.ci_sa sa ON sa.sa_id = ft.sa_id AND NULLIF(TRIM(sa.SA_STATUS_FLG), '') = '20'
    WHERE ft.ft_type_flg = 'PS' AND ft.freeze_sw = 'Y'
    GROUP BY sa.acct_id, ft.ars_dt
) pym ON acct.acct_id = pym.acct_id
WHERE pym.ars_dt BETWEEN SYSDATE - 60 AND SYSDATE
"""

# -----------------------------------------------------------------------------
# Risk Data (Audit Mode): Revenue Leakage, Cash Flow Bottleneck, Service Initiation
# Run when RISK_DATA_ENABLED=1. Differentiate "Clean Data" (financials) from "Risk Data" (operational monitoring).
# -----------------------------------------------------------------------------

# Revenue Leakage: Canceled SAs that still have outstanding (frozen) arrears — "ghost" debt; prompt write-off or final bill.
QUERY_REVENUE_LEAKAGE_CANCELED_SA = """
SELECT
    SA.ACCT_ID,
    SA.SA_ID,
    SUM(FT.CUR_AMT) AS TOTAL_UNRESOLVED_AMT
FROM CISADM.CI_SA SA
JOIN CISADM.CI_FT FT ON FT.SA_ID = SA.SA_ID
WHERE NULLIF(TRIM(SA.SA_STATUS_FLG), '') = '70'
  AND FT.FREEZE_SW = 'Y'
  AND FT.ARS_DT IS NOT NULL
  AND FT.NOT_IN_ARS_SW = 'N'
  AND FT.FT_TYPE_FLG NOT IN ('PS', 'PX')
GROUP BY SA.ACCT_ID, SA.SA_ID
HAVING SUM(FT.CUR_AMT) > 0
"""

# Liquidity Risk (A): Pending payments (PAY_STATUS_FLG = 'P') — not yet finalized; >48h = Suspense Alert.
QUERY_LIQUIDITY_RISK_PENDING_PAYMENTS = """
SELECT
    PE.PAY_EVENT_ID,
    P.ACCT_ID,
    NVL(P.PAY_AMT, 0) AS PAY_AMT,
    TRUNC(SYSDATE) - TRUNC(PE.CRE_DTTM) AS DAYS_SINCE_CRE
FROM CISADM.CI_PAY_EVENT PE
JOIN CISADM.CI_PAY P ON P.PAY_EVENT_ID = PE.PAY_EVENT_ID
WHERE NULLIF(TRIM(P.PAY_STATUS_FLG), '') = 'P'
  AND PE.CRE_DTTM >= TRUNC(SYSDATE) - 14
"""

# Liquidity Risk (B): Unfrozen payment transactions (CI_FT) — not yet hit GL; >48h = batch/drawer risk.
QUERY_LIQUIDITY_RISK_UNFROZEN_FT = """
SELECT
    FT.FT_ID,
    FT.SA_ID,
    NVL(FT.CUR_AMT, 0) AS CUR_AMT,
    TRUNC(SYSDATE) - TRUNC(FT.CRE_DTTM) AS DAYS_SINCE_CRE
FROM CISADM.CI_FT FT
WHERE FT.FT_TYPE_FLG IN ('PS', 'PX')
  AND FT.FREEZE_SW = 'N'
  AND FT.CRE_DTTM >= TRUNC(SYSDATE) - 14
"""

# Stale Pending SA: New Services still Pending with START_DT in the past — service delay; check F1_TSK.
QUERY_STALE_PENDING_SA = """
SELECT SA_ID, ACCT_ID, START_DT, CRE_DTTM
FROM CISADM.CI_SA
WHERE NULLIF(TRIM(SA_STATUS_FLG), '') = '10'
  AND START_DT IS NOT NULL
  AND TRUNC(START_DT) < TRUNC(SYSDATE)
"""

# -----------------------------------------------------------------------------
# Workstream: Billing & Rates
# Governed logic: CI_BSEG (bill segments) joins to CI_BILL (header) and CI_RS_L (rate schedule).
# Live DB: CI_BILL has BILL_DT, ACCT_ID; CI_BSEG may not have AMOUNT — use CI_BILL for bill list.
# -----------------------------------------------------------------------------
QUERY_BILLING_BY_ACCT = """
SELECT bl.BILL_ID, bl.BILL_DT, bl.BILL_STAT_FLG, bl.ACCT_ID, bl.DUE_DT, bl.CRE_DTTM
FROM CISADM.CI_BILL bl
WHERE bl.ACCT_ID = :acct_id
  AND bl.BILL_DT >= ADD_MONTHS(TRUNC(SYSDATE), -3)
  AND bl.BILL_DT < TRUNC(SYSDATE) + 1
ORDER BY bl.BILL_DT DESC
FETCH FIRST 24 ROWS ONLY
"""

# Billing: BSEG -> BILL (safe for all schemas). Use when you need segment-level link to bill header.
QUERY_BILLING_BSEG_BILL = """
SELECT b.BILL_ID, b.BILL_DT, b.ACCT_ID, b.BILL_STAT_FLG, s.BSEG_ID, s.SA_ID
FROM CISADM.CI_BSEG s
JOIN CISADM.CI_BILL b ON b.BILL_ID = s.BILL_ID
WHERE b.BILL_DT >= ADD_MONTHS(TRUNC(SYSDATE), -3)
  AND b.BILL_DT < TRUNC(SYSDATE) + 1
  AND ROWNUM <= 500
"""
# Billing: BSEG -> BILL -> RS_L (use only when CI_BSEG has RS_CD column; many C2M builds do not)
# QUERY_BILLING_BSEG_BILL_RS_L = "SELECT ... s.RS_CD, r.DESCR ... JOIN CI_RS_L r ON r.RS_CD = s.RS_CD ..."

# Rate schedule lookup (CI_RS_L: live has RS_CD, LANGUAGE_CD, DESCR)
QUERY_BILLING_RATE_SCHEDULE = """
SELECT RS_CD, LANGUAGE_CD, NULLIF(TRIM(DESCR), '') AS RATE_DESCR
FROM CISADM.CI_RS_L
WHERE ROWNUM <= 100
"""

# Governed rate configuration: CI_RS_L (rate schedule labels).
# CI_RC_L is not referenced in this environment; extend to join CI_RC_L when available.
QUERY_RATE_CONFIG = """
SELECT RS_CD,
       LANGUAGE_CD,
       NULLIF(TRIM(DESCR), '') AS RATE_DESCR
FROM CISADM.CI_RS_L
WHERE LANGUAGE_CD = 'EN'
"""

# Billing & Rates: Strategic queries (portfolio-level insights)
QUERY_BILLING_STRATEGIC = """
SELECT 
    COUNT(DISTINCT bl.ACCT_ID) AS TOTAL_ACCOUNTS_BILLED,
    COUNT(bl.BILL_ID) AS TOTAL_BILLS,
    SUM(CASE WHEN bl.LATE_PAY_CHARGE_SW = 'Y' THEN 1 ELSE 0 END) AS BILLS_WITH_LATE_FEE,
    COUNT(DISTINCT bl.BILL_CYC_CD) AS BILL_CYCLE_COUNT,
    COUNT(DISTINCT SA.RATE_RS_CD) AS RATE_SCHEDULE_COUNT
FROM CISADM.CI_BILL bl
LEFT JOIN CISADM.CI_SA SA ON SA.ACCT_ID = bl.ACCT_ID 
    AND NULLIF(TRIM(SA.SA_STATUS_FLG), '') = '20'
WHERE bl.BILL_DT >= ADD_MONTHS(TRUNC(SYSDATE), -3)
  AND bl.BILL_DT < TRUNC(SYSDATE) + 1
"""

QUERY_BILLING_RATE_DISTRIBUTION = """
SELECT 
    NULLIF(TRIM(SA.RATE_RS_CD), '') AS RATE_RS_CD,
    COUNT(DISTINCT SA.SA_ID) AS SA_COUNT,
    COUNT(DISTINCT SA.ACCT_ID) AS ACCT_COUNT
FROM CISADM.CI_SA SA
WHERE NULLIF(TRIM(SA.SA_STATUS_FLG), '') = '20'
  AND SA.RATE_RS_CD IS NOT NULL
GROUP BY SA.RATE_RS_CD
ORDER BY SA_COUNT DESC
"""

QUERY_BILLING_LATE_FEE_ANALYSIS = """
SELECT 
    COUNT(DISTINCT bl.ACCT_ID) AS ACCOUNTS_WITH_LATE_FEES,
    COUNT(bl.BILL_ID) AS BILLS_WITH_LATE_FEES,
    MIN(bl.LATE_PAY_CHARGE_DT) AS EARLIEST_LATE_FEE,
    MAX(bl.LATE_PAY_CHARGE_DT) AS LATEST_LATE_FEE
FROM CISADM.CI_BILL bl
WHERE bl.LATE_PAY_CHARGE_SW = 'Y'
  AND bl.LATE_PAY_CHARGE_DT >= ADD_MONTHS(TRUNC(SYSDATE), -3)
"""

# -----------------------------------------------------------------------------
# Workstream: Cashiering (CI_PAY_EVENT, CI_PAY_TNDR, CI_DEP_CTL)
# Live DB: CI_PAY_TNDR has TNDR_STATUS_FLG (not TNDR_STATUS). Valid = '25' for bank reconciliation.
# -----------------------------------------------------------------------------
QUERY_CASHIERING_VALID_TENDERS = """
SELECT PE.PAY_EVENT_ID, PE.CRE_DTTM, PT.TNDR_STATUS_FLG, PT.TENDER_TYPE_CD,
       DC.DEP_CTL_ID, DC.DEP_CTL_STATUS_FLG
FROM CISADM.CI_PAY_EVENT PE
JOIN CISADM.CI_PAY_TNDR PT ON PT.PAY_EVENT_ID = PE.PAY_EVENT_ID
JOIN CISADM.CI_TNDR_CTL TC ON TC.TNDR_CTL_ID = PT.TNDR_CTL_ID
JOIN CISADM.CI_DEP_CTL DC ON DC.DEP_CTL_ID = TC.DEP_CTL_ID
WHERE PT.TNDR_STATUS_FLG = '25'
  AND PE.CRE_DTTM >= SYSDATE - 30
  AND ROWNUM <= 500
"""

QUERY_CASHIERING_BY_ACCT = """
SELECT P.ACCT_ID, PE.PAY_EVENT_ID, PE.CRE_DTTM, P.PAY_AMT, P.PAY_STATUS_FLG,
       PT.TNDR_STATUS_FLG, PT.TENDER_TYPE_CD, PT.TENDER_AMT, DC.DEP_CTL_STATUS_FLG
FROM CISADM.CI_PAY_EVENT PE
JOIN CISADM.CI_PAY P ON P.PAY_EVENT_ID = PE.PAY_EVENT_ID
JOIN CISADM.CI_PAY_TNDR PT ON PT.PAY_EVENT_ID = PE.PAY_EVENT_ID
JOIN CISADM.CI_TNDR_CTL TC ON TC.TNDR_CTL_ID = PT.TNDR_CTL_ID
JOIN CISADM.CI_DEP_CTL DC ON DC.DEP_CTL_ID = TC.DEP_CTL_ID
WHERE P.ACCT_ID = :acct_id
  AND PE.CRE_DTTM >= SYSDATE - 90
ORDER BY PE.CRE_DTTM DESC
FETCH FIRST 50 ROWS ONLY
"""

# Cashiering: Strategic queries
QUERY_CASHIERING_STRATEGIC = """
SELECT 
    COUNT(DISTINCT P.ACCT_ID) AS ACCOUNTS_WITH_PAYMENTS,
    COUNT(PE.PAY_EVENT_ID) AS TOTAL_PAYMENT_EVENTS,
    SUM(P.PAY_AMT) AS TOTAL_PAYMENT_AMOUNT,
    COUNT(CASE WHEN PT.TNDR_STATUS_FLG = '25' THEN 1 END) AS VALID_TENDERS,
    COUNT(CASE WHEN DC.DEP_CTL_STATUS_FLG IS NOT NULL THEN 1 END) AS DEPOSITS_CONTROLLED,
    COUNT(DISTINCT PT.TENDER_TYPE_CD) AS TENDER_TYPE_COUNT
FROM CISADM.CI_PAY_EVENT PE
JOIN CISADM.CI_PAY P ON P.PAY_EVENT_ID = PE.PAY_EVENT_ID
JOIN CISADM.CI_PAY_TNDR PT ON PT.PAY_EVENT_ID = PE.PAY_EVENT_ID
JOIN CISADM.CI_TNDR_CTL TC ON TC.TNDR_CTL_ID = PT.TNDR_CTL_ID
LEFT JOIN CISADM.CI_DEP_CTL DC ON DC.DEP_CTL_ID = TC.DEP_CTL_ID
WHERE PE.CRE_DTTM >= SYSDATE - 30
"""

QUERY_CASHIERING_TENDER_DISTRIBUTION = """
SELECT 
    NULLIF(TRIM(PT.TENDER_TYPE_CD), '') AS TENDER_TYPE_CD,
    COUNT(PT.PAY_EVENT_ID) AS PAYMENT_COUNT,
    SUM(PT.TENDER_AMT) AS TOTAL_TENDER_AMOUNT,
    COUNT(CASE WHEN PT.TNDR_STATUS_FLG = '25' THEN 1 END) AS VALID_COUNT
FROM CISADM.CI_PAY_TNDR PT
JOIN CISADM.CI_PAY_EVENT PE ON PE.PAY_EVENT_ID = PT.PAY_EVENT_ID
WHERE PE.CRE_DTTM >= SYSDATE - 30
  AND PT.TENDER_TYPE_CD IS NOT NULL
GROUP BY PT.TENDER_TYPE_CD
ORDER BY PAYMENT_COUNT DESC
"""

QUERY_CASHIERING_MISSING_DEPOSITS = """
SELECT 
    COUNT(DISTINCT SA.ACCT_ID) AS ACCOUNTS_MISSING_DEPOSIT,
    COUNT(SA.SA_ID) AS SA_MISSING_DEPOSIT_COUNT
FROM CISADM.CI_SA SA
LEFT JOIN CISADM.CI_FT FT ON FT.SA_ID = SA.SA_ID 
    AND FT.FT_TYPE_FLG = 'DP'
    AND FT.FREEZE_SW = 'Y'
WHERE NULLIF(TRIM(SA.SA_STATUS_FLG), '') = '20'
  AND FT.FT_ID IS NULL
"""

# -----------------------------------------------------------------------------
# Workstream: Meter Operations (source: Domain Designs.xlsx)
# Tables: D1_DVC (Device), D1_DVC_CFG (Device Config), D1_INSTALL_EVT (Install Event).
# In this environment D1 tables are exposed under CISADM (CISADM.D1_* synonyms).
# Legacy: some C2M instances use CI_MTR (Legacy Meter); this pipeline prefers D1_* when available,
# and falls back to CI_SP.INSTALL_DT when D1_* is not present.
# Ground truth: D1_INSTALL_EVT.D1_INSTALL_DTTM = when meter/device was installed at SP.
# -----------------------------------------------------------------------------
QUERY_METER_OPS_BY_SP = """
SELECT IE.INSTALL_EVT_ID, IE.D1_SP_ID, IE.D1_INSTALL_DTTM, IE.DEVICE_CONFIG_ID,
       DC.D1_DEVICE_ID, NULLIF(TRIM(D.DEVICE_TYPE_CD), '') AS DEVICE_TYPE_CD,
       SP.SP_ID, NULLIF(TRIM(SP.SP_STATUS_FLG), '') AS SP_STATUS_FLG
FROM CISADM.D1_INSTALL_EVT IE
LEFT JOIN CISADM.D1_DVC_CFG DC ON DC.DEVICE_CONFIG_ID = IE.DEVICE_CONFIG_ID
LEFT JOIN CISADM.D1_DVC D ON D.D1_DEVICE_ID = DC.D1_DEVICE_ID
LEFT JOIN CISADM.CI_SP SP ON SP.SP_ID = IE.D1_SP_ID
WHERE IE.D1_SP_ID = :sp_id
  AND ROWNUM <= 20
"""

QUERY_METER_OPS_BY_ACCT = """
SELECT IE.INSTALL_EVT_ID, IE.D1_SP_ID, IE.D1_INSTALL_DTTM, IE.DEVICE_CONFIG_ID,
       DC.D1_DEVICE_ID, NULLIF(TRIM(D.DEVICE_TYPE_CD), '') AS DEVICE_TYPE_CD,
       SA.ACCT_ID
FROM CISADM.D1_INSTALL_EVT IE
LEFT JOIN CISADM.D1_DVC_CFG DC ON DC.DEVICE_CONFIG_ID = IE.DEVICE_CONFIG_ID
LEFT JOIN CISADM.D1_DVC D ON D.D1_DEVICE_ID = DC.D1_DEVICE_ID
JOIN CISADM.CI_SP SP ON SP.SP_ID = IE.D1_SP_ID
JOIN CISADM.CI_SA SA ON SA.SP_ID = SP.SP_ID AND NULLIF(TRIM(SA.SA_STATUS_FLG), '') = '20'
WHERE SA.ACCT_ID = :acct_id
  AND ROWNUM <= 20
"""

# Fallback when D1_* tables are not present (e.g. C2M without Meter Solution): use CI_SP.INSTALL_DT.
QUERY_METER_OPS_FALLBACK_BY_ACCT = """
SELECT SP.SP_ID, SP.INSTALL_DT, NULLIF(TRIM(SP.SP_STATUS_FLG), '') AS SP_STATUS_FLG, SA.ACCT_ID
FROM CISADM.CI_SP SP
JOIN CISADM.CI_SA SA ON SA.SP_ID = SP.SP_ID AND NULLIF(TRIM(SA.SA_STATUS_FLG), '') = '20'
WHERE SA.ACCT_ID = :acct_id
ORDER BY SP.INSTALL_DT DESC NULLS LAST
FETCH FIRST 20 ROWS ONLY
"""

# Meter Operations: Strategic queries
QUERY_METER_OPS_STRATEGIC = """
SELECT 
    COUNT(DISTINCT IE.D1_SP_ID) AS SERVICE_POINTS_WITH_DEVICES,
    COUNT(IE.INSTALL_EVT_ID) AS TOTAL_INSTALL_EVENTS,
    COUNT(DISTINCT D.DEVICE_TYPE_CD) AS DEVICE_TYPE_COUNT,
    MIN(IE.D1_INSTALL_DTTM) AS EARLIEST_INSTALL,
    MAX(IE.D1_INSTALL_DTTM) AS LATEST_INSTALL
FROM CISADM.D1_INSTALL_EVT IE
LEFT JOIN CISADM.D1_DVC_CFG DC ON DC.DEVICE_CONFIG_ID = IE.DEVICE_CONFIG_ID
LEFT JOIN CISADM.D1_DVC D ON D.D1_DEVICE_ID = DC.D1_DEVICE_ID
WHERE IE.D1_INSTALL_DTTM >= ADD_MONTHS(TRUNC(SYSDATE), -12)
"""

QUERY_METER_OPS_DEVICE_TYPE_DISTRIBUTION = """
SELECT 
    NULLIF(TRIM(D.DEVICE_TYPE_CD), '') AS DEVICE_TYPE_CD,
    COUNT(DISTINCT IE.D1_SP_ID) AS SP_COUNT,
    COUNT(IE.INSTALL_EVT_ID) AS INSTALL_COUNT
FROM CISADM.D1_INSTALL_EVT IE
LEFT JOIN CISADM.D1_DVC_CFG DC ON DC.DEVICE_CONFIG_ID = IE.DEVICE_CONFIG_ID
LEFT JOIN CISADM.D1_DVC D ON D.D1_DEVICE_ID = DC.D1_DEVICE_ID
WHERE IE.D1_INSTALL_DTTM >= ADD_MONTHS(TRUNC(SYSDATE), -12)
  AND D.DEVICE_TYPE_CD IS NOT NULL
GROUP BY D.DEVICE_TYPE_CD
ORDER BY SP_COUNT DESC
"""

# -----------------------------------------------------------------------------
# Workstream: Customer Operations (CI_ACCT, CI_PER_NAME, CI_ACCT_ALERT)
# Live DB: CI_ACCT has ACCT_ID, BILL_CYC_CD, SETUP_DT (no ACCT_NBR, ACCT_STATUS_CD).
# -----------------------------------------------------------------------------
QUERY_CUSTOMER_OPS_BY_ACCT = """
SELECT A.ACCT_ID, A.BILL_CYC_CD, A.SETUP_DT, A.CUST_CL_CD, A.COLL_CL_CD,
       PN.ENTITY_NAME, PN.PER_ID, ALA.ALERT_TYPE_CD, ALA.START_DT, ALA.END_DT
FROM CISADM.CI_ACCT A
LEFT JOIN CISADM.CI_ACCT_PER AP ON AP.ACCT_ID = A.ACCT_ID AND AP.MAIN_CUST_SW = 'Y'
LEFT JOIN CISADM.CI_PER_NAME PN ON PN.PER_ID = AP.PER_ID AND PN.PRIM_NAME_SW = 'Y'
LEFT JOIN CISADM.CI_ACCT_ALERT ALA ON ALA.ACCT_ID = A.ACCT_ID
  AND SYSDATE BETWEEN ALA.START_DT AND ALA.END_DT
WHERE A.ACCT_ID = :acct_id
"""

# Customer Operations: Strategic queries
QUERY_CUSTOMER_OPS_STRATEGIC = """
SELECT 
    COUNT(DISTINCT A.ACCT_ID) AS TOTAL_ACCOUNTS,
    COUNT(DISTINCT A.CUST_CL_CD) AS CUSTOMER_CLASS_COUNT,
    COUNT(DISTINCT A.COLL_CL_CD) AS COLLECTION_CLASS_COUNT,
    COUNT(DISTINCT A.BILL_CYC_CD) AS BILL_CYCLE_COUNT,
    COUNT(DISTINCT ALA.ACCT_ID) AS ACCOUNTS_WITH_ALERTS,
    COUNT(ALA.ALERT_TYPE_CD) AS TOTAL_ACTIVE_ALERTS
FROM CISADM.CI_ACCT A
LEFT JOIN CISADM.CI_ACCT_ALERT ALA ON ALA.ACCT_ID = A.ACCT_ID
  AND SYSDATE BETWEEN ALA.START_DT AND ALA.END_DT
"""

QUERY_CUSTOMER_OPS_CLASS_DISTRIBUTION = """
SELECT 
    NULLIF(TRIM(A.CUST_CL_CD), '') AS CUST_CL_CD,
    COUNT(DISTINCT A.ACCT_ID) AS ACCOUNT_COUNT,
    COUNT(DISTINCT SA.SA_ID) AS SA_COUNT
FROM CISADM.CI_ACCT A
LEFT JOIN CISADM.CI_SA SA ON SA.ACCT_ID = A.ACCT_ID 
    AND NULLIF(TRIM(SA.SA_STATUS_FLG), '') = '20'
WHERE A.CUST_CL_CD IS NOT NULL
GROUP BY A.CUST_CL_CD
ORDER BY ACCOUNT_COUNT DESC
"""

QUERY_CUSTOMER_OPS_ALERT_DISTRIBUTION = """
SELECT 
    NULLIF(TRIM(ALA.ALERT_TYPE_CD), '') AS ALERT_TYPE_CD,
    COUNT(DISTINCT ALA.ACCT_ID) AS ACCOUNTS_WITH_ALERT,
    COUNT(ALA.ALERT_TYPE_CD) AS ALERT_COUNT
FROM CISADM.CI_ACCT_ALERT ALA
WHERE SYSDATE BETWEEN ALA.START_DT AND ALA.END_DT
  AND ALA.ALERT_TYPE_CD IS NOT NULL
GROUP BY ALA.ALERT_TYPE_CD
ORDER BY ACCOUNTS_WITH_ALERT DESC
"""

# -----------------------------------------------------------------------------
# Workstream: New Services (CI_SA status 10/20, CI_SP_CHAR)
# Ground truth: SA_STATUS_FLG = '10' (Pending) for pipeline view
# -----------------------------------------------------------------------------
QUERY_NEW_SERVICES_PIPELINE = """
SELECT SA.SA_ID, SA.ACCT_ID, SA.SP_ID, SA.SA_STATUS_FLG, SA.CRE_DTTM AS SA_INITIATION_DTTM,
       SC.SP_CHAR_ID, NULLIF(TRIM(SC.CHAR_VAL), '') AS DEVICE_ATTR_VAL
FROM CISADM.CI_SA SA
LEFT JOIN CISADM.CI_SP_CHAR SC ON SC.SP_ID = SA.SP_ID
WHERE SA.SA_STATUS_FLG IN ('10', '20')
  AND SA.CRE_DTTM >= ADD_MONTHS(TRUNC(SYSDATE), -6)
  AND ROWNUM <= 200
"""

QUERY_NEW_SERVICES_BY_ACCT = """
SELECT SA.SA_ID, SA.ACCT_ID, SA.SP_ID, SA.SA_STATUS_FLG, SA.CRE_DTTM AS SA_INITIATION_DTTM,
       SC.SP_CHAR_ID, NULLIF(TRIM(SC.CHAR_VAL), '') AS DEVICE_ATTR_VAL
FROM CISADM.CI_SA SA
LEFT JOIN CISADM.CI_SP_CHAR SC ON SC.SP_ID = SA.SP_ID
WHERE SA.SA_STATUS_FLG IN ('10', '20')
  AND SA.ACCT_ID = :acct_id
ORDER BY SA.CRE_DTTM DESC
FETCH FIRST 20 ROWS ONLY
"""

# New Services: Strategic queries
QUERY_NEW_SERVICES_STRATEGIC = """
SELECT 
    COUNT(DISTINCT SA.ACCT_ID) AS ACCOUNTS_IN_PIPELINE,
    COUNT(SA.SA_ID) AS TOTAL_SA_IN_PIPELINE,
    COUNT(CASE WHEN SA.SA_STATUS_FLG = '10' THEN 1 END) AS PENDING_COUNT,
    COUNT(CASE WHEN SA.SA_STATUS_FLG = '20' THEN 1 END) AS ACTIVE_NEW_COUNT,
    MIN(SA.CRE_DTTM) AS EARLIEST_INITIATION,
    MAX(SA.CRE_DTTM) AS LATEST_INITIATION
FROM CISADM.CI_SA SA
WHERE SA.SA_STATUS_FLG IN ('10', '20')
  AND SA.CRE_DTTM >= ADD_MONTHS(TRUNC(SYSDATE), -6)
"""

QUERY_NEW_SERVICES_STATUS_DISTRIBUTION = """
SELECT 
    NULLIF(TRIM(SA.SA_STATUS_FLG), '') AS SA_STATUS_FLG,
    COUNT(SA.SA_ID) AS SA_COUNT,
    COUNT(DISTINCT SA.ACCT_ID) AS ACCOUNT_COUNT,
    AVG(TRUNC(SYSDATE) - TRUNC(SA.CRE_DTTM)) AS AVG_DAYS_IN_STATUS
FROM CISADM.CI_SA SA
WHERE SA.SA_STATUS_FLG IN ('10', '20')
  AND SA.CRE_DTTM >= ADD_MONTHS(TRUNC(SYSDATE), -6)
GROUP BY SA.SA_STATUS_FLG
ORDER BY SA_COUNT DESC
"""

# -----------------------------------------------------------------------------
# Workstream: Finance (CI_FT_GL, CI_FT_PROC, CI_FT)
# Live DB: CI_FT_GL has GL_ACCT, AMOUNT (no GL_DISTRIB_STATUS); CI_FT has GL_DISTRIB_STATUS. CI_FT_PROC has BATCH_CD, BATCH_NBR.
# -----------------------------------------------------------------------------
QUERY_FINANCE_GL_BATCH = """
SELECT FG.FT_ID, FT.GL_DISTRIB_STATUS, FG.GL_ACCT, FG.AMOUNT,
       FP.BATCH_CD, FP.BATCH_NBR
FROM CISADM.CI_FT_GL FG
JOIN CISADM.CI_FT FT ON FT.FT_ID = FG.FT_ID
LEFT JOIN CISADM.CI_FT_PROC FP ON FP.FT_ID = FG.FT_ID
WHERE FT.CRE_DTTM >= TRUNC(SYSDATE) - 7
  AND ROWNUM <= 500
"""

QUERY_FINANCE_GL_BY_ACCT = """
SELECT FG.FT_ID, FT.GL_DISTRIB_STATUS, FG.GL_ACCT, FG.AMOUNT,
       FT.SA_ID, SA.ACCT_ID, FP.BATCH_CD, FP.BATCH_NBR
FROM CISADM.CI_FT_GL FG
JOIN CISADM.CI_FT FT ON FT.FT_ID = FG.FT_ID
JOIN CISADM.CI_SA SA ON SA.SA_ID = FT.SA_ID AND NULLIF(TRIM(SA.SA_STATUS_FLG), '') = '20'
LEFT JOIN CISADM.CI_FT_PROC FP ON FP.FT_ID = FG.FT_ID
WHERE SA.ACCT_ID = :acct_id
  AND FT.CRE_DTTM >= ADD_MONTHS(TRUNC(SYSDATE), -3)
ORDER BY FT.CRE_DTTM DESC
FETCH FIRST 50 ROWS ONLY
"""

# Finance: Strategic queries
QUERY_FINANCE_STRATEGIC = """
SELECT 
    COUNT(DISTINCT FG.FT_ID) AS TOTAL_GL_DISTRIBUTIONS,
    COUNT(DISTINCT FG.GL_ACCT) AS GL_ACCOUNT_COUNT,
    SUM(FG.AMOUNT) AS TOTAL_GL_AMOUNT,
    COUNT(DISTINCT FP.BATCH_CD) AS BATCH_COUNT,
    COUNT(DISTINCT CASE WHEN FT.GL_DISTRIB_STATUS IS NOT NULL THEN FT.FT_ID END) AS DISTRIBUTED_COUNT
FROM CISADM.CI_FT_GL FG
JOIN CISADM.CI_FT FT ON FT.FT_ID = FG.FT_ID
LEFT JOIN CISADM.CI_FT_PROC FP ON FP.FT_ID = FG.FT_ID
WHERE FT.CRE_DTTM >= TRUNC(SYSDATE) - 30
"""

QUERY_FINANCE_GL_DISTRIBUTION_STATUS = """
SELECT 
    NULLIF(TRIM(FT.GL_DISTRIB_STATUS), '') AS GL_DISTRIB_STATUS,
    COUNT(DISTINCT FT.FT_ID) AS FT_COUNT,
    SUM(FG.AMOUNT) AS TOTAL_AMOUNT
FROM CISADM.CI_FT FT
JOIN CISADM.CI_FT_GL FG ON FG.FT_ID = FT.FT_ID
WHERE FT.CRE_DTTM >= TRUNC(SYSDATE) - 30
  AND FT.GL_DISTRIB_STATUS IS NOT NULL
GROUP BY FT.GL_DISTRIB_STATUS
ORDER BY FT_COUNT DESC
"""

# -----------------------------------------------------------------------------
# Workstream: Common (CI_PREM, CI_LOOKUP_VAL)
# Live DB: CI_PREM has STATE, POSTAL (not STATE_CD, POSTAL_CD). CI_LOOKUP_VAL has FIELD_NAME, FIELD_VALUE, VALUE_NAME.
# -----------------------------------------------------------------------------
QUERY_COMMON_PREMISE = """
SELECT PREM_ID, ADDRESS1, ADDRESS1_UPR, NULLIF(TRIM(CITY), '') AS CITY,
       NULLIF(TRIM(STATE), '') AS STATE_CD, NULLIF(TRIM(POSTAL), '') AS POSTAL_CD
FROM CISADM.CI_PREM
WHERE PREM_ID = :prem_id
"""

QUERY_COMMON_LOOKUP_STATUS = """
SELECT FIELD_NAME, FIELD_VALUE, NULLIF(TRIM(VALUE_NAME), '') AS DESCR
FROM CISADM.CI_LOOKUP_VAL
WHERE FIELD_NAME = :lookup_type
  AND ROWNUM <= 100
"""

# -----------------------------------------------------------------------------
# Data health validation (explicit columns)
# -----------------------------------------------------------------------------
VALIDATION_QUERIES = {
    "financial_transactions": "SELECT COUNT(*) AS cnt FROM CISADM.CI_FT WHERE CRE_DTTM > SYSDATE - 7",
    "active_service_agreements": "SELECT COUNT(*) AS cnt FROM CISADM.CI_SA WHERE SA_STATUS_FLG = '20'",
    "recent_payments": "SELECT COUNT(*) AS cnt FROM CISADM.CI_FT WHERE FT_TYPE_FLG IN ('PS','PX') AND CRE_DTTM > SYSDATE - 2",
}

# -----------------------------------------------------------------------------
# Workstream: Debt Management (collections, arrears follow-up, payment plans)
# Source: CI_ACCT (COLL_CL_CD, CR_REVIEW_DT), CI_FT (arrears). Optional: CI_COLL_PROC.
# -----------------------------------------------------------------------------
QUERY_DEBT_MGMT_BY_ACCT = """
SELECT A.ACCT_ID, NULLIF(TRIM(A.COLL_CL_CD), '') AS COLL_CL_CD,
       A.CR_REVIEW_DT, A.POSTPONE_CR_RVW_DT
FROM CISADM.CI_ACCT A
WHERE A.ACCT_ID = :acct_id
"""

# Debt Management: Strategic queries
QUERY_DEBT_MGMT_STRATEGIC = """
SELECT 
    COUNT(DISTINCT A.ACCT_ID) AS TOTAL_ACCOUNTS,
    COUNT(DISTINCT A.COLL_CL_CD) AS COLLECTION_CLASS_COUNT,
    COUNT(CASE WHEN A.CR_REVIEW_DT IS NOT NULL THEN 1 END) AS ACCOUNTS_WITH_CR_REVIEW,
    COUNT(CASE WHEN A.CR_REVIEW_DT <= TRUNC(SYSDATE) THEN 1 END) AS CR_REVIEWS_DUE,
    COUNT(CASE WHEN A.POSTPONE_CR_RVW_DT IS NOT NULL THEN 1 END) AS POSTPONED_REVIEWS
FROM CISADM.CI_ACCT A
"""

QUERY_DEBT_MGMT_COLLECTION_CLASS_DISTRIBUTION = """
SELECT 
    NULLIF(TRIM(A.COLL_CL_CD), '') AS COLL_CL_CD,
    COUNT(DISTINCT A.ACCT_ID) AS ACCOUNT_COUNT,
    COUNT(DISTINCT SA.SA_ID) AS SA_COUNT,
    SUM(FT.CUR_AMT) AS TOTAL_ARREARS
FROM CISADM.CI_ACCT A
LEFT JOIN CISADM.CI_SA SA ON SA.ACCT_ID = A.ACCT_ID 
    AND NULLIF(TRIM(SA.SA_STATUS_FLG), '') = '20'
LEFT JOIN CISADM.CI_FT FT ON FT.SA_ID = SA.SA_ID
    AND FT.FREEZE_SW = 'Y'
    AND FT.NOT_IN_ARS_SW = 'N'
    AND FT.FT_TYPE_FLG NOT IN ('PS', 'PX')
    AND FT.ARS_DT IS NOT NULL
WHERE A.COLL_CL_CD IS NOT NULL
GROUP BY A.COLL_CL_CD
ORDER BY ACCOUNT_COUNT DESC
"""

# -----------------------------------------------------------------------------
# Workstream: Field Operations (service point, install, work orders / appointments)
# Source: CI_SP (INSTALL_DT, SP_STATUS_FLG); optional D1_ACTIVITY when present.
# -----------------------------------------------------------------------------
QUERY_FIELD_OPS_BY_ACCT = """
SELECT SP.SP_ID, SP.INSTALL_DT, NULLIF(TRIM(SP.SP_STATUS_FLG), '') AS SP_STATUS_FLG, SA.ACCT_ID
FROM CISADM.CI_SP SP
JOIN CISADM.CI_SA SA ON SA.SP_ID = SP.SP_ID AND NULLIF(TRIM(SA.SA_STATUS_FLG), '') = '20'
WHERE SA.ACCT_ID = :acct_id
ORDER BY SP.INSTALL_DT DESC NULLS LAST
FETCH FIRST 20 ROWS ONLY
"""

# Field Operations: Strategic queries
QUERY_FIELD_OPS_STRATEGIC = """
SELECT 
    COUNT(DISTINCT SP.SP_ID) AS TOTAL_SERVICE_POINTS,
    COUNT(DISTINCT CASE WHEN SP.INSTALL_DT IS NOT NULL THEN SP.SP_ID END) AS INSTALLED_SP_COUNT,
    COUNT(DISTINCT SP.SP_STATUS_FLG) AS STATUS_TYPE_COUNT,
    MIN(SP.INSTALL_DT) AS EARLIEST_INSTALL,
    MAX(SP.INSTALL_DT) AS LATEST_INSTALL
FROM CISADM.CI_SP SP
JOIN CISADM.CI_SA SA ON SA.SP_ID = SP.SP_ID 
    AND NULLIF(TRIM(SA.SA_STATUS_FLG), '') = '20'
"""

QUERY_FIELD_OPS_STATUS_DISTRIBUTION = """
SELECT 
    NULLIF(TRIM(SP.SP_STATUS_FLG), '') AS SP_STATUS_FLG,
    COUNT(DISTINCT SP.SP_ID) AS SP_COUNT,
    COUNT(DISTINCT SA.ACCT_ID) AS ACCOUNT_COUNT
FROM CISADM.CI_SP SP
JOIN CISADM.CI_SA SA ON SA.SP_ID = SP.SP_ID 
    AND NULLIF(TRIM(SA.SA_STATUS_FLG), '') = '20'
WHERE SP.SP_STATUS_FLG IS NOT NULL
GROUP BY SP.SP_STATUS_FLG
ORDER BY SP_COUNT DESC
"""

# -----------------------------------------------------------------------------
# OCX & Field Tasks (F1 Metadata Layer: F1_TSK, F1_TSK_LOG)
# Hybrid Strategy: Join CI/D1 functional data with F1 task metadata for field operations tracking.
# -----------------------------------------------------------------------------
QUERY_FIELD_TASKS_BY_ACCT = """
SELECT 
    TSK.TSK_ID,
    TSK.BUS_OBJ_CD,
    TSK.BO_STATUS_CD,
    TSK.CRE_DTTM AS TASK_CREATED_DTTM,
    TSK.STATUS_UPD_DTTM,
    TSK.BO_STATUS_REASON_CD,
    LOG.LOG_DTTM AS LOG_DTTM,
    NULLIF(TRIM(LOG.LOG_MSG), '') AS LOG_MESSAGE,
    SA.ACCT_ID,
    SP.SP_ID
FROM CISADM.F1_TSK TSK
LEFT JOIN CISADM.F1_TSK_LOG LOG ON LOG.TSK_ID = TSK.TSK_ID
LEFT JOIN CISADM.CI_SP SP ON SP.SP_ID = TSK.BUS_OBJ_ID 
    AND TSK.BUS_OBJ_CD = 'SP'
LEFT JOIN CISADM.CI_SA SA ON SA.SP_ID = SP.SP_ID 
    AND NULLIF(TRIM(SA.SA_STATUS_FLG), '') = '20'
WHERE SA.ACCT_ID = :acct_id
  AND TSK.CRE_DTTM >= TRUNC(SYSDATE) - 30
ORDER BY TSK.CRE_DTTM DESC
FETCH FIRST 50 ROWS ONLY
"""

QUERY_FIELD_TASKS_STRATEGIC = """
SELECT 
    COUNT(DISTINCT TSK.TSK_ID) AS TOTAL_TASKS_30D,
    COUNT(DISTINCT CASE WHEN TSK.BO_STATUS_CD NOT IN ('COMPLETE', 'CLOSED') THEN TSK.TSK_ID END) AS OPEN_TASKS,
    COUNT(DISTINCT TSK.BUS_OBJ_CD) AS BUS_OBJ_TYPE_COUNT,
    COUNT(DISTINCT CASE WHEN LOG.TSK_ID IS NOT NULL THEN TSK.TSK_ID END) AS TASKS_WITH_LOGS,
    MIN(TSK.CRE_DTTM) AS EARLIEST_TASK,
    MAX(TSK.CRE_DTTM) AS LATEST_TASK
FROM CISADM.F1_TSK TSK
LEFT JOIN CISADM.F1_TSK_LOG LOG ON LOG.TSK_ID = TSK.TSK_ID
WHERE TSK.CRE_DTTM >= TRUNC(SYSDATE) - 30
"""

QUERY_FIELD_TASKS_STATUS_DISTRIBUTION = """
SELECT 
    NULLIF(TRIM(TSK.BO_STATUS_CD), '') AS TASK_STATUS_CD,
    COUNT(DISTINCT TSK.TSK_ID) AS TASK_COUNT,
    COUNT(DISTINCT CASE WHEN TSK.BUS_OBJ_CD = 'SP' THEN TSK.BUS_OBJ_ID END) AS SERVICE_POINT_TASKS
FROM CISADM.F1_TSK TSK
WHERE TSK.CRE_DTTM >= TRUNC(SYSDATE) - 30
  AND TSK.BO_STATUS_CD IS NOT NULL
GROUP BY TSK.BO_STATUS_CD
ORDER BY TASK_COUNT DESC
"""

# -----------------------------------------------------------------------------
# F1 Metadata Layer: Code Translation (F1_EXT_LOOKUP)
# Use F1_EXT_LOOKUP to translate technical codes (BO_STATUS_CD, BUS_OBJ_CD) into business-friendly descriptions.
# -----------------------------------------------------------------------------
QUERY_F1_LOOKUP_CODE_TRANSLATION = """
SELECT 
    NULLIF(TRIM(LOOKUP.FIELD_NAME), '') AS FIELD_NAME,
    NULLIF(TRIM(LOOKUP.FIELD_VALUE), '') AS FIELD_VALUE,
    NULLIF(TRIM(LOOKUP.VALUE_NAME), '') AS BUSINESS_DESCRIPTION
FROM CISADM.F1_EXT_LOOKUP LOOKUP
WHERE LOOKUP.FIELD_NAME = :field_name
  AND ROWNUM <= 100
"""

# Common lookup translations for Field Ops / OCX
QUERY_F1_LOOKUP_TASK_STATUS = """
SELECT 
    NULLIF(TRIM(FIELD_VALUE), '') AS STATUS_CODE,
    NULLIF(TRIM(VALUE_NAME), '') AS STATUS_DESCRIPTION
FROM CISADM.F1_EXT_LOOKUP
WHERE FIELD_NAME = 'BO_STATUS_CD'
  AND ROWNUM <= 50
"""

QUERY_F1_LOOKUP_BUS_OBJ = """
SELECT 
    NULLIF(TRIM(FIELD_VALUE), '') AS BUS_OBJ_CODE,
    NULLIF(TRIM(VALUE_NAME), '') AS BUS_OBJ_DESCRIPTION
FROM CISADM.F1_EXT_LOOKUP
WHERE FIELD_NAME = 'BUS_OBJ_CD'
  AND ROWNUM <= 50
"""

# -----------------------------------------------------------------------------
# F1 Metadata Layer: Batch Health Validation (F1_BATCH_RUN)
# Critical Path Risk: Check if Billing/Finance batches ran successfully in last 24 hours.
# -----------------------------------------------------------------------------
QUERY_F1_BATCH_RUN_HEALTH = """
SELECT 
    NULLIF(TRIM(BR.BATCH_CD), '') AS BATCH_CD,
    BR.BATCH_RUN_ID,
    BR.START_DTTM,
    BR.END_DTTM,
    NULLIF(TRIM(BR.STATUS_CD), '') AS STATUS_CD,
    BR.ROW_COUNT,
    BR.ERROR_COUNT
FROM CISADM.F1_BATCH_RUN BR
WHERE BR.START_DTTM >= TRUNC(SYSDATE) - 1
  AND BR.BATCH_CD IN ('BILLING', 'FINANCE', 'PAYMENT')
ORDER BY BR.START_DTTM DESC
FETCH FIRST 20 ROWS ONLY
"""

QUERY_F1_BATCH_RUN_CRITICAL_PATH = """
SELECT 
    NULLIF(TRIM(BR.BATCH_CD), '') AS BATCH_CD,
    COUNT(*) AS RUN_COUNT_24H,
    COUNT(CASE WHEN BR.STATUS_CD = 'SUCCESS' THEN 1 END) AS SUCCESS_COUNT,
    COUNT(CASE WHEN BR.STATUS_CD != 'SUCCESS' THEN 1 END) AS FAILURE_COUNT,
    MAX(BR.END_DTTM) AS LAST_RUN_DTTM
FROM CISADM.F1_BATCH_RUN BR
WHERE BR.START_DTTM >= TRUNC(SYSDATE) - 1
  AND BR.BATCH_CD IN ('BILLING', 'FINANCE', 'PAYMENT')
GROUP BY BR.BATCH_CD
"""

# -----------------------------------------------------------------------------
# Workstream Health Matrix: primary "Source of Truth" table + 7-day freshness check.
# Used by validate_tables.py to report Data Currency Risk when a workstream has no recent records.
# Nine workstreams: Billing, Cashiering, Meter Ops, Customer Ops, New Services, Finance, Common, Debt Mgmt, Field Ops.
# -----------------------------------------------------------------------------
WORKSTREAM_HEALTH = [
    ("billing", "CISADM.CI_BILL", "CRE_DTTM"),
    ("cashiering", "CISADM.CI_PAY_EVENT", "CRE_DTTM"),
    # D1 objects are exposed through CISADM in this environment.
    ("meter_ops", "CISADM.D1_INSTALL_EVT", "D1_INSTALL_DTTM"),
    ("customer_ops", "CISADM.CI_ACCT", "SETUP_DT"),
    ("new_services", "CISADM.CI_SA", "START_DT"),
    ("finance", "CISADM.CI_FT", "CRE_DTTM"),
    ("common", "CISADM.CI_PREM", None),
    ("debt_mgmt", "CISADM.CI_FT", "CRE_DTTM"),
    ("field_ops", "CISADM.CI_SP", "INSTALL_DT"),
    ("field_tasks", "CISADM.F1_TSK", "CRE_DTTM"),  # OCX & Field Tasks (F1 metadata layer)
]
