-- Purpose:
--   Domain-equivalent row-level dataset for General Ledger / fund balance validation.
--   Mirrors key fields consumed by:
--   - reports/general_ledger_exec_cover.jrxml
--   - reports/general_ledger_recent_batch_quality.jrxml
--   - reports/general_ledger_batch_executive_packet.jrxml
--
-- Primary source-of-truth for GL line amounts:
--   CISADM.C1_BI_FTGL_VW (bridge to CI_FT_GL/CI_FT semantics)
--
-- Parameters:
--   :P_START_ACCOUNTING_DT   DATE     -- optional inclusive lower bound
--   :P_END_ACCOUNTING_DT     DATE     -- optional inclusive upper bound
--   :P_BATCH_NBR             NUMBER   -- optional exact batch filter
--   :P_ONLY_LATEST_BATCH     CHAR     -- 'Y' or 'N' (default 'N')
--   :P_ONLY_EXCEPTIONS       CHAR     -- 'Y' or 'N' (default 'N')
--   :P_MIN_ABS_AMOUNT        NUMBER   -- optional minimum abs(amount)
--   :P_ACCT_ID_LIST          VARCHAR2 -- optional comma-separated ACCT_ID list

WITH ACCT_FILTER AS (
  SELECT TRIM(REGEXP_SUBSTR(:P_ACCT_ID_LIST, '[^,]+', 1, LEVEL)) AS ACCT_ID
  FROM DUAL
  CONNECT BY REGEXP_SUBSTR(:P_ACCT_ID_LIST, '[^,]+', 1, LEVEL) IS NOT NULL
),
FT_PROC_LATEST AS (
  SELECT
    P.FT_ID,
    MAX(P.BATCH_NBR) AS BATCH_NBR
  FROM CISADM.CI_FT_PROC P
  GROUP BY
    P.FT_ID
),
BASE AS (
  SELECT
    FP.BATCH_NBR,
    V.FT_ID,
    V.ACCT_ID,
    V.DST_ID,
    NVL(L_GL.DESCR, TRIM(F.GL_DISTRIB_STATUS)) AS GL_DISTRIB_STATUS_DESC,
    V.GL_ACCT,
    D.FUND_CD,
    FDL.DESCR AS FUND_DESCR,
    FD.FUND_TYPE_FLG,
    NVL(L_FUND.DESCR, TRIM(FD.FUND_TYPE_FLG)) AS FUND_TYPE_FLG_DESC,
    NVL(V.FT_GL_AMT, 0) AS AMOUNT,
    NVL(V.FT_GL_CREDIT_AMT, 0) AS CREDIT_AMOUNT,
    NVL(V.FT_GL_DEBIT_AMT, 0) AS DEBIT_AMOUNT,
    V.ACCOUNTING_DT,
    V.FREEZE_DTTM,
    V.GL_DIVISION,
    V.CIS_DIVISION,
    NVL(L_FT.DESCR, TRIM(V.FT_TYPE_FLG)) AS FT_TYPE_FLG_DESC,
    PN.ENTITY_NAME_UPR,
    PR.ADDRESS1,
    PR.CITY,
    PR.STATE,
    PR.POSTAL
  FROM CISADM.C1_BI_FTGL_VW V
  LEFT JOIN FT_PROC_LATEST FP
    ON FP.FT_ID = V.FT_ID
  LEFT JOIN CISADM.CI_FT F
    ON F.FT_ID = V.FT_ID
  LEFT JOIN CISADM.CI_LOOKUP_VAL_L L_GL
    ON TRIM(F.GL_DISTRIB_STATUS) = TRIM(L_GL.FIELD_VALUE)
   AND TRIM(L_GL.FIELD_NAME) = 'GL_DISTRIB_STATUS'
   AND L_GL.LANGUAGE_CD = 'ENG'
  LEFT JOIN CISADM.CI_LOOKUP_VAL_L L_FT
    ON TRIM(V.FT_TYPE_FLG) = TRIM(L_FT.FIELD_VALUE)
   AND TRIM(L_FT.FIELD_NAME) = 'FT_TYPE_FLG'
   AND L_FT.LANGUAGE_CD = 'ENG'
  LEFT JOIN CISADM.CI_DST_CODE_EFF D
    ON D.DST_ID = V.DST_ID
   AND D.GL_ACCT = V.GL_ACCT
   AND D.EFF_STATUS = 'A'
  LEFT JOIN CISADM.CI_FUND FD
    ON FD.FUND_CD = D.FUND_CD
  LEFT JOIN CISADM.CI_FUND_L FDL
    ON FDL.FUND_CD = FD.FUND_CD
   AND FDL.LANGUAGE_CD = 'ENG'
  LEFT JOIN CISADM.CI_LOOKUP_VAL_L L_FUND
    ON TRIM(FD.FUND_TYPE_FLG) = TRIM(L_FUND.FIELD_VALUE)
   AND TRIM(L_FUND.FIELD_NAME) = 'FUND_TYPE_FLG'
   AND L_FUND.LANGUAGE_CD = 'ENG'
  LEFT JOIN CISADM.CI_ACCT A
    ON A.ACCT_ID = V.ACCT_ID
  LEFT JOIN CISADM.CI_PREM PR
    ON PR.PREM_ID = A.MAILING_PREM_ID
  LEFT JOIN CISADM.CI_ACCT_PER AP
    ON AP.ACCT_ID = V.ACCT_ID
   AND AP.MAIN_CUST_SW = 'Y'
  LEFT JOIN CISADM.CI_PER_NAME PN
    ON PN.PER_ID = AP.PER_ID
   AND PN.NAME_TYPE_FLG = 'PRIM'
  WHERE (:P_START_ACCOUNTING_DT IS NULL OR V.ACCOUNTING_DT >= :P_START_ACCOUNTING_DT)
    AND (:P_END_ACCOUNTING_DT IS NULL OR V.ACCOUNTING_DT < :P_END_ACCOUNTING_DT + 1)
    AND (:P_BATCH_NBR IS NULL OR FP.BATCH_NBR = :P_BATCH_NBR)
    AND (
      :P_ACCT_ID_LIST IS NULL
      OR TRIM(V.ACCT_ID) IN (SELECT AF.ACCT_ID FROM ACCT_FILTER AF)
    )
),
SCORED AS (
  SELECT
    B.*,
    MAX(B.BATCH_NBR) OVER () AS LATEST_BATCH_NBR,
    CASE
      WHEN B.GL_ACCT IS NULL OR TRIM(B.GL_ACCT) = '' THEN 1
      ELSE 0
    END AS MISSING_GL_ACCT_FLG,
    CASE
      WHEN NVL(B.AMOUNT, 0) = 0 THEN 1
      ELSE 0
    END AS ZERO_AMOUNT_FLG,
    CASE
      WHEN B.GL_DISTRIB_STATUS_DESC IS NULL
        OR (
          UPPER(B.GL_DISTRIB_STATUS_DESC) NOT LIKE '%DISTRIBUT%'
          AND UPPER(B.GL_DISTRIB_STATUS_DESC) NOT LIKE '%COMPLETE%'
          AND UPPER(B.GL_DISTRIB_STATUS_DESC) NOT LIKE '%POST%'
        )
      THEN 1
      ELSE 0
    END AS STATUS_ISSUE_FLG,
    CASE
      WHEN B.GL_ACCT IS NOT NULL
       AND TRIM(B.GL_ACCT) <> ''
       AND (B.FUND_CD IS NULL OR TRIM(B.FUND_CD) = '')
      THEN 1
      ELSE 0
    END AS MISSING_FUND_MAP_FLG
  FROM BASE B
)
SELECT
  S.BATCH_NBR,
  CASE
    WHEN S.BATCH_NBR IS NOT NULL AND S.BATCH_NBR = S.LATEST_BATCH_NBR THEN 'Y'
    ELSE 'N'
  END AS IS_LATEST_BATCH_NBR,
  S.FT_ID,
  S.ACCT_ID,
  S.DST_ID,
  S.GL_DISTRIB_STATUS_DESC,
  S.GL_ACCT,
  S.FUND_CD,
  S.FUND_DESCR,
  S.FUND_TYPE_FLG,
  S.FUND_TYPE_FLG_DESC,
  S.AMOUNT,
  S.CREDIT_AMOUNT,
  S.DEBIT_AMOUNT,
  S.ACCOUNTING_DT,
  S.FREEZE_DTTM,
  S.GL_DIVISION,
  S.CIS_DIVISION,
  S.FT_TYPE_FLG_DESC,
  S.ENTITY_NAME_UPR,
  S.ADDRESS1,
  S.CITY,
  S.STATE,
  S.POSTAL,
  CASE
    WHEN S.MISSING_GL_ACCT_FLG = 1 OR S.ZERO_AMOUNT_FLG = 1 THEN 'ERROR'
    WHEN S.STATUS_ISSUE_FLG = 1 OR S.MISSING_FUND_MAP_FLG = 1 THEN 'WARN'
    ELSE 'OK'
  END AS SEVERITY_FLAG
FROM SCORED S
WHERE (NVL(:P_ONLY_LATEST_BATCH, 'N') = 'N'
       OR (S.BATCH_NBR IS NOT NULL AND S.BATCH_NBR = S.LATEST_BATCH_NBR))
  AND (:P_MIN_ABS_AMOUNT IS NULL OR ABS(NVL(S.AMOUNT, 0)) >= :P_MIN_ABS_AMOUNT)
  AND (NVL(:P_ONLY_EXCEPTIONS, 'N') = 'N'
       OR (
            S.MISSING_GL_ACCT_FLG = 1
         OR S.ZERO_AMOUNT_FLG = 1
         OR S.STATUS_ISSUE_FLG = 1
         OR S.MISSING_FUND_MAP_FLG = 1
       ))
ORDER BY
  S.BATCH_NBR DESC NULLS LAST,
  S.ACCOUNTING_DT DESC,
  S.FT_ID;
