-- Purpose:
--   Roll up GL/fund balances by account and GL account.
--   Useful for verifying specific accounts against expected balances.
--
-- Parameters:
--   :P_START_ACCOUNTING_DT   DATE     -- optional inclusive lower bound
--   :P_END_ACCOUNTING_DT     DATE     -- optional inclusive upper bound
--   :P_BATCH_NBR             NUMBER   -- optional exact batch filter
--   :P_ONLY_LATEST_BATCH     CHAR     -- 'Y' or 'N' (default 'Y')
--   :P_ACCT_ID_LIST          VARCHAR2 -- optional comma-separated ACCT_ID list

WITH ACCT_FILTER AS (
  SELECT TRIM(REGEXP_SUBSTR(:P_ACCT_ID_LIST, '[^,]+', 1, LEVEL)) AS ACCT_ID
  FROM DUAL
  CONNECT BY REGEXP_SUBSTR(:P_ACCT_ID_LIST, '[^,]+', 1, LEVEL) IS NOT NULL
),
FT_PROC_LATEST AS (
  SELECT
    P.FT_ID,
    MAX(P.BATCH_NBR) AS BATCH_NBR
  FROM CISADM.CI_FT_PROC P
  GROUP BY
    P.FT_ID
),
BASE AS (
  SELECT
    FP.BATCH_NBR,
    V.FT_ID,
    V.ACCT_ID,
    V.GL_ACCT,
    D.FUND_CD,
    FDL.DESCR AS FUND_DESCR,
    NVL(V.FT_GL_AMT, 0) AS AMOUNT,
    NVL(V.FT_GL_CREDIT_AMT, 0) AS CREDIT_AMOUNT,
    NVL(V.FT_GL_DEBIT_AMT, 0) AS DEBIT_AMOUNT,
    V.ACCOUNTING_DT
  FROM CISADM.C1_BI_FTGL_VW V
  LEFT JOIN FT_PROC_LATEST FP
    ON FP.FT_ID = V.FT_ID
  LEFT JOIN CISADM.CI_DST_CODE_EFF D
    ON D.DST_ID = V.DST_ID
   AND D.GL_ACCT = V.GL_ACCT
   AND D.EFF_STATUS = 'A'
  LEFT JOIN CISADM.CI_FUND_L FDL
    ON FDL.FUND_CD = D.FUND_CD
   AND FDL.LANGUAGE_CD = 'ENG'
  WHERE (:P_START_ACCOUNTING_DT IS NULL OR V.ACCOUNTING_DT >= :P_START_ACCOUNTING_DT)
    AND (:P_END_ACCOUNTING_DT IS NULL OR V.ACCOUNTING_DT < :P_END_ACCOUNTING_DT + 1)
    AND (:P_BATCH_NBR IS NULL OR FP.BATCH_NBR = :P_BATCH_NBR)
    AND (
      :P_ACCT_ID_LIST IS NULL
      OR TRIM(V.ACCT_ID) IN (SELECT AF.ACCT_ID FROM ACCT_FILTER AF)
    )
),
SCOPED AS (
  SELECT
    B.*,
    MAX(B.BATCH_NBR) OVER () AS LATEST_BATCH_NBR
  FROM BASE B
)
SELECT
  S.ACCT_ID,
  S.GL_ACCT,
  S.FUND_CD,
  S.FUND_DESCR,
  MAX(S.BATCH_NBR) AS BATCH_NBR,
  SUM(S.AMOUNT) AS NET_AMOUNT,
  SUM(S.CREDIT_AMOUNT) AS CREDIT_AMOUNT,
  SUM(S.DEBIT_AMOUNT) AS DEBIT_AMOUNT,
  COUNT(*) AS GL_LINE_COUNT,
  COUNT(DISTINCT S.FT_ID) AS FT_COUNT,
  MIN(S.ACCOUNTING_DT) AS FIRST_ACCOUNTING_DT,
  MAX(S.ACCOUNTING_DT) AS LAST_ACCOUNTING_DT
FROM SCOPED S
WHERE (NVL(:P_ONLY_LATEST_BATCH, 'Y') = 'N'
       OR (S.BATCH_NBR IS NOT NULL AND S.BATCH_NBR = S.LATEST_BATCH_NBR))
GROUP BY
  S.ACCT_ID,
  S.GL_ACCT,
  S.FUND_CD,
  S.FUND_DESCR
ORDER BY
  S.ACCT_ID,
  S.GL_ACCT,
  S.FUND_CD;
