-- Purpose:
--   Reconcile fund-balance GL amounts between:
--   - View source: CISADM.C1_BI_FTGL_VW.FT_GL_AMT
--   - Raw source:  CISADM.CI_FT_GL.AMOUNT (joined to CI_FT for accounting date)
--
-- Parameters:
--   :P_START_ACCOUNTING_DT   DATE     -- optional inclusive lower bound
--   :P_END_ACCOUNTING_DT     DATE     -- optional inclusive upper bound
--   :P_BATCH_NBR             NUMBER   -- optional exact batch filter
--   :P_ONLY_LATEST_BATCH     CHAR     -- 'Y' or 'N' (default 'Y')
--   :P_ACCT_ID_LIST          VARCHAR2 -- optional comma-separated ACCT_ID list

WITH ACCT_FILTER AS (
  SELECT TRIM(REGEXP_SUBSTR(:P_ACCT_ID_LIST, '[^,]+', 1, LEVEL)) AS ACCT_ID
  FROM DUAL
  CONNECT BY REGEXP_SUBSTR(:P_ACCT_ID_LIST, '[^,]+', 1, LEVEL) IS NOT NULL
),
FT_PROC_LATEST AS (
  SELECT
    P.FT_ID,
    MAX(P.BATCH_NBR) AS BATCH_NBR
  FROM CISADM.CI_FT_PROC P
  GROUP BY
    P.FT_ID
),
RAW_AGG AS (
  SELECT
    FP.BATCH_NBR,
    G.GL_ACCT,
    D.FUND_CD,
    FDL.DESCR AS FUND_DESCR,
    SUM(NVL(G.AMOUNT, 0)) AS RAW_AMOUNT
  FROM CISADM.CI_FT_GL G
  JOIN CISADM.CI_FT F
    ON F.FT_ID = G.FT_ID
  LEFT JOIN FT_PROC_LATEST FP
    ON FP.FT_ID = G.FT_ID
  LEFT JOIN CISADM.CI_DST_CODE_EFF D
    ON D.DST_ID = G.DST_ID
   AND D.GL_ACCT = G.GL_ACCT
   AND D.EFF_STATUS = 'A'
  LEFT JOIN CISADM.CI_FUND_L FDL
    ON FDL.FUND_CD = D.FUND_CD
   AND FDL.LANGUAGE_CD = 'ENG'
  WHERE (:P_START_ACCOUNTING_DT IS NULL OR F.ACCOUNTING_DT >= :P_START_ACCOUNTING_DT)
    AND (:P_END_ACCOUNTING_DT IS NULL OR F.ACCOUNTING_DT < :P_END_ACCOUNTING_DT + 1)
    AND (:P_BATCH_NBR IS NULL OR FP.BATCH_NBR = :P_BATCH_NBR)
    AND (
      :P_ACCT_ID_LIST IS NULL
      OR TRIM(F.ACCT_ID) IN (SELECT AF.ACCT_ID FROM ACCT_FILTER AF)
    )
  GROUP BY
    FP.BATCH_NBR,
    G.GL_ACCT,
    D.FUND_CD,
    FDL.DESCR
),
VW_AGG AS (
  SELECT
    FP.BATCH_NBR,
    V.GL_ACCT,
    D.FUND_CD,
    FDL.DESCR AS FUND_DESCR,
    SUM(NVL(V.FT_GL_AMT, 0)) AS VW_AMOUNT
  FROM CISADM.C1_BI_FTGL_VW V
  LEFT JOIN FT_PROC_LATEST FP
    ON FP.FT_ID = V.FT_ID
  LEFT JOIN CISADM.CI_DST_CODE_EFF D
    ON D.DST_ID = V.DST_ID
   AND D.GL_ACCT = V.GL_ACCT
   AND D.EFF_STATUS = 'A'
  LEFT JOIN CISADM.CI_FUND_L FDL
    ON FDL.FUND_CD = D.FUND_CD
   AND FDL.LANGUAGE_CD = 'ENG'
  WHERE (:P_START_ACCOUNTING_DT IS NULL OR V.ACCOUNTING_DT >= :P_START_ACCOUNTING_DT)
    AND (:P_END_ACCOUNTING_DT IS NULL OR V.ACCOUNTING_DT < :P_END_ACCOUNTING_DT + 1)
    AND (:P_BATCH_NBR IS NULL OR FP.BATCH_NBR = :P_BATCH_NBR)
    AND (
      :P_ACCT_ID_LIST IS NULL
      OR TRIM(V.ACCT_ID) IN (SELECT AF.ACCT_ID FROM ACCT_FILTER AF)
    )
  GROUP BY
    FP.BATCH_NBR,
    V.GL_ACCT,
    D.FUND_CD,
    FDL.DESCR
),
COMBINED AS (
  SELECT
    COALESCE(R.BATCH_NBR, V.BATCH_NBR) AS BATCH_NBR,
    COALESCE(R.GL_ACCT, V.GL_ACCT) AS GL_ACCT,
    COALESCE(R.FUND_CD, V.FUND_CD) AS FUND_CD,
    COALESCE(R.FUND_DESCR, V.FUND_DESCR) AS FUND_DESCR,
    NVL(R.RAW_AMOUNT, 0) AS RAW_AMOUNT,
    NVL(V.VW_AMOUNT, 0) AS VW_AMOUNT
  FROM RAW_AGG R
  FULL OUTER JOIN VW_AGG V
    ON V.BATCH_NBR = R.BATCH_NBR
   AND V.GL_ACCT = R.GL_ACCT
   AND NVL(V.FUND_CD, ' ') = NVL(R.FUND_CD, ' ')
),
SCOPED AS (
  SELECT
    C.*,
    MAX(C.BATCH_NBR) OVER () AS LATEST_BATCH_NBR
  FROM COMBINED C
)
SELECT
  S.BATCH_NBR,
  S.GL_ACCT,
  S.FUND_CD,
  S.FUND_DESCR,
  S.RAW_AMOUNT,
  S.VW_AMOUNT,
  ROUND(S.VW_AMOUNT - S.RAW_AMOUNT, 6) AS AMOUNT_DIFF
FROM SCOPED S
WHERE (NVL(:P_ONLY_LATEST_BATCH, 'Y') = 'N'
       OR (S.BATCH_NBR IS NOT NULL AND S.BATCH_NBR = S.LATEST_BATCH_NBR))
ORDER BY
  S.BATCH_NBR DESC NULLS LAST,
  S.GL_ACCT,
  S.FUND_CD;
