-- Purpose:
--   Executive summary of GL/fund-balance quality for the same dataset as
--   fund_balance_batch_detail.sql.
--
-- Parameters:
--   :P_START_ACCOUNTING_DT   DATE     -- optional inclusive lower bound
--   :P_END_ACCOUNTING_DT     DATE     -- optional inclusive upper bound
--   :P_BATCH_NBR             NUMBER   -- optional exact batch filter
--   :P_ONLY_LATEST_BATCH     CHAR     -- 'Y' or 'N' (default 'Y')
--   :P_MIN_ABS_AMOUNT        NUMBER   -- optional minimum abs(amount)
--   :P_ACCT_ID_LIST          VARCHAR2 -- optional comma-separated ACCT_ID list

WITH ACCT_FILTER AS (
  SELECT TRIM(REGEXP_SUBSTR(:P_ACCT_ID_LIST, '[^,]+', 1, LEVEL)) AS ACCT_ID
  FROM DUAL
  CONNECT BY REGEXP_SUBSTR(:P_ACCT_ID_LIST, '[^,]+', 1, LEVEL) IS NOT NULL
),
FT_PROC_LATEST AS (
  SELECT
    P.FT_ID,
    MAX(P.BATCH_NBR) AS BATCH_NBR
  FROM CISADM.CI_FT_PROC P
  GROUP BY
    P.FT_ID
),
BASE AS (
  SELECT
    FP.BATCH_NBR,
    V.FT_ID,
    V.ACCT_ID,
    V.DST_ID,
    NVL(V.FT_GL_AMT, 0) AS AMOUNT,
    NVL(V.FT_GL_CREDIT_AMT, 0) AS CREDIT_AMOUNT,
    NVL(V.FT_GL_DEBIT_AMT, 0) AS DEBIT_AMOUNT,
    V.ACCOUNTING_DT,
    NVL(L_GL.DESCR, TRIM(F.GL_DISTRIB_STATUS)) AS GL_DISTRIB_STATUS_DESC,
    V.GL_ACCT,
    D.FUND_CD,
    FDL.DESCR AS FUND_DESCR
  FROM CISADM.C1_BI_FTGL_VW V
  LEFT JOIN FT_PROC_LATEST FP
    ON FP.FT_ID = V.FT_ID
  LEFT JOIN CISADM.CI_FT F
    ON F.FT_ID = V.FT_ID
  LEFT JOIN CISADM.CI_LOOKUP_VAL_L L_GL
    ON TRIM(F.GL_DISTRIB_STATUS) = TRIM(L_GL.FIELD_VALUE)
   AND TRIM(L_GL.FIELD_NAME) = 'GL_DISTRIB_STATUS'
   AND L_GL.LANGUAGE_CD = 'ENG'
  LEFT JOIN CISADM.CI_DST_CODE_EFF D
    ON D.DST_ID = V.DST_ID
   AND D.GL_ACCT = V.GL_ACCT
   AND D.EFF_STATUS = 'A'
  LEFT JOIN CISADM.CI_FUND_L FDL
    ON FDL.FUND_CD = D.FUND_CD
   AND FDL.LANGUAGE_CD = 'ENG'
  WHERE (:P_START_ACCOUNTING_DT IS NULL OR V.ACCOUNTING_DT >= :P_START_ACCOUNTING_DT)
    AND (:P_END_ACCOUNTING_DT IS NULL OR V.ACCOUNTING_DT < :P_END_ACCOUNTING_DT + 1)
    AND (:P_BATCH_NBR IS NULL OR FP.BATCH_NBR = :P_BATCH_NBR)
    AND (
      :P_ACCT_ID_LIST IS NULL
      OR TRIM(V.ACCT_ID) IN (SELECT AF.ACCT_ID FROM ACCT_FILTER AF)
    )
    AND (:P_MIN_ABS_AMOUNT IS NULL OR ABS(NVL(V.FT_GL_AMT, 0)) >= :P_MIN_ABS_AMOUNT)
),
SCORED AS (
  SELECT
    B.*,
    MAX(B.BATCH_NBR) OVER () AS LATEST_BATCH_NBR,
    CASE
      WHEN B.GL_ACCT IS NULL OR TRIM(B.GL_ACCT) = '' THEN 1
      ELSE 0
    END AS MISSING_GL_ACCT_FLG,
    CASE
      WHEN NVL(B.AMOUNT, 0) = 0 THEN 1
      ELSE 0
    END AS ZERO_AMOUNT_FLG,
    CASE
      WHEN B.GL_DISTRIB_STATUS_DESC IS NULL
        OR (
          UPPER(B.GL_DISTRIB_STATUS_DESC) NOT LIKE '%DISTRIBUT%'
          AND UPPER(B.GL_DISTRIB_STATUS_DESC) NOT LIKE '%COMPLETE%'
          AND UPPER(B.GL_DISTRIB_STATUS_DESC) NOT LIKE '%POST%'
        )
      THEN 1
      ELSE 0
    END AS STATUS_ISSUE_FLG,
    CASE
      WHEN B.GL_ACCT IS NOT NULL
       AND TRIM(B.GL_ACCT) <> ''
       AND (B.FUND_CD IS NULL OR TRIM(B.FUND_CD) = '')
      THEN 1
      ELSE 0
    END AS MISSING_FUND_MAP_FLG
  FROM BASE B
)
SELECT
  MAX(S.LATEST_BATCH_NBR) AS LATEST_BATCH_NBR,
  COUNT(*) AS TOTAL_ROWS,
  COUNT(DISTINCT S.FT_ID) AS DISTINCT_FT_COUNT,
  COUNT(DISTINCT S.ACCT_ID) AS DISTINCT_ACCOUNT_COUNT,
  COUNT(DISTINCT S.FUND_CD) AS DISTINCT_FUND_COUNT,
  SUM(S.AMOUNT) AS TOTAL_AMOUNT,
  SUM(S.CREDIT_AMOUNT) AS TOTAL_CREDIT_AMOUNT,
  SUM(S.DEBIT_AMOUNT) AS TOTAL_DEBIT_AMOUNT,
  SUM(S.MISSING_GL_ACCT_FLG) AS MISSING_GL_ACCT_COUNT,
  SUM(S.ZERO_AMOUNT_FLG) AS ZERO_AMOUNT_COUNT,
  SUM(S.STATUS_ISSUE_FLG) AS STATUS_ISSUE_COUNT,
  SUM(S.MISSING_FUND_MAP_FLG) AS MISSING_FUND_MAP_COUNT,
  SUM(
    CASE
      WHEN S.MISSING_GL_ACCT_FLG = 1
        OR S.ZERO_AMOUNT_FLG = 1
        OR S.STATUS_ISSUE_FLG = 1
        OR S.MISSING_FUND_MAP_FLG = 1
      THEN 1
      ELSE 0
    END
  ) AS BAD_ROW_COUNT,
  MIN(S.ACCOUNTING_DT) AS MIN_ACCOUNTING_DT,
  MAX(S.ACCOUNTING_DT) AS MAX_ACCOUNTING_DT
FROM SCORED S
WHERE (NVL(:P_ONLY_LATEST_BATCH, 'Y') = 'N'
       OR (S.BATCH_NBR IS NOT NULL AND S.BATCH_NBR = S.LATEST_BATCH_NBR));
