SELECT
    CASE
        WHEN TRIM(X.BILL_CYC_CD) IS NULL OR LENGTH(TRIM(X.BILL_CYC_CD)) = 0 THEN 'UNASSIGNED'
        ELSE TRIM(X.BILL_CYC_CD)
    END AS BILL_CYCLE_CODE,
    NVL(
        C.BILL_CYCLE_DESCRIPTION,
        CASE
            WHEN TRIM(X.BILL_CYC_CD) IS NULL OR LENGTH(TRIM(X.BILL_CYC_CD)) = 0 THEN 'Unassigned Cycle'
            ELSE 'Cycle ' || TRIM(X.BILL_CYC_CD)
        END
    ) AS BILL_CYCLE_DESCRIPTION,
    X.BILL_DT AS BILL_DATE,
    X.BILL_CRE_DTTM AS BILL_CREATE_DATE,
    X.BSEG_CRE_DTTM AS BILL_SEGMENT_CREATE_DATE,
    TRUNC(NVL(X.BSEG_CRE_DTTM, NVL(X.BILL_CRE_DTTM, X.BILL_DT))) AS EVENT_DATE_FOR_FILTER,
    X.ACCT_ID AS ACCOUNT_ID,
    X.SA_ID AS SERVICE_AGREEMENT_ID,
    X.PREM_ID AS PREMISE_ID,
    X.BILL_ID AS BILL_ID,
    X.BILL_STAT_FLG AS BILL_STATUS_CODE,
    BSL.DESCR AS BILL_STATUS_DESCRIPTION,
    X.BSEG_ID AS BILL_SEGMENT_ID,
    X.BSEG_STAT_FLG AS BILL_SEGMENT_STATUS_CODE,
    SEGSL.DESCR AS BILL_SEGMENT_STATUS_DESCRIPTION,
    CASE
        WHEN X.BILL_ID IS NULL AND X.BSEG_ID IS NOT NULL THEN 'ORPHAN_BSEG'
        WHEN X.BILL_ID IS NOT NULL AND X.BSEG_ID IS NULL THEN 'MISSING_BSEG'
        ELSE 'PRESENT'
    END AS RECONCILIATION_RESULT
FROM (
    SELECT
        NVL(B.BILL_CYC_CD, NVL(AC.BILL_CYC_CD, S.BILL_CYC_CD)) AS BILL_CYC_CD,
        B.BILL_DT,
        B.BILL_CRE_DTTM,
        S.BSEG_CRE_DTTM,
        B.ACCT_ID,
        S.SA_ID,
        S.PREM_ID,
        NVL(B.BILL_ID, S.BILL_ID) AS BILL_ID,
        B.BILL_STAT_FLG,
        S.BSEG_ID,
        S.BSEG_STAT_FLG
    FROM (
        SELECT
            BILL_ID,
            ACCT_ID,
            BILL_CYC_CD,
            BILL_DT,
            CRE_DTTM AS BILL_CRE_DTTM,
            BILL_STAT_FLG
        FROM CISADM.CI_BILL
    ) B
    FULL OUTER JOIN (
        SELECT
            BILL_ID,
            BILL_CYC_CD,
            SA_ID,
            PREM_ID,
            BSEG_ID,
            BSEG_STAT_FLG,
            CRE_DTTM AS BSEG_CRE_DTTM
        FROM CISADM.CI_BSEG
    ) S
        ON S.BILL_ID = B.BILL_ID
    LEFT JOIN CISADM.CI_ACCT AC
        ON AC.ACCT_ID = B.ACCT_ID
) X
LEFT JOIN (
    SELECT
        BILL_CYC_CD,
        MAX(DESCR) AS BILL_CYCLE_DESCRIPTION
    FROM CISADM.CI_BILL_CYC_L
    WHERE LANGUAGE_CD IN ('ENG', 'EN')
    GROUP BY BILL_CYC_CD
) C
    ON TRIM(C.BILL_CYC_CD) = TRIM(X.BILL_CYC_CD)
LEFT JOIN CISADM.CI_LOOKUP_VAL_L BSL
    ON BSL.FIELD_NAME = 'BILL_STAT_FLG'
   AND BSL.FIELD_VALUE = X.BILL_STAT_FLG
   AND BSL.LANGUAGE_CD = 'ENG'
LEFT JOIN CISADM.CI_LOOKUP_VAL_L SEGSL
    ON SEGSL.FIELD_NAME = 'BSEG_STAT_FLG'
   AND SEGSL.FIELD_VALUE = X.BSEG_STAT_FLG
   AND SEGSL.LANGUAGE_CD = 'ENG'
