SELECT
    X.BILL_CYCLE_CODE,
    X.BILL_CYCLE_DESCRIPTION,
    X.BILL_DATE,
    X.BILL_CREATE_DATE,
    COUNT(*) AS GENERATED_BILL_COUNT,
    SUM(X.GENERATED_SEGMENT_COUNT) AS GENERATED_BILL_SEGMENT_COUNT,
    SUM(X.PREMISE_COUNT) AS DISTINCT_PREMISE_COUNT,
    SUM(CASE WHEN X.GENERATED_SEGMENT_COUNT = 0 THEN 1 ELSE 0 END) AS BILLS_WITHOUT_SEGMENT_COUNT,
    SUM(X.EXPECTED_SEGMENT_COUNT) AS EXPECTED_BILL_SEGMENT_COUNT,
    SUM(
        CASE
            WHEN X.EXPECTED_SEGMENT_COUNT > X.GENERATED_SEGMENT_COUNT
            THEN X.EXPECTED_SEGMENT_COUNT - X.GENERATED_SEGMENT_COUNT
            ELSE 0
        END
    ) AS MISSING_BILL_SEGMENT_COUNT,
    ROUND(
        100 * SUM(X.GENERATED_SEGMENT_COUNT) / NULLIF(SUM(X.EXPECTED_SEGMENT_COUNT), 0),
        2
    ) AS BILL_SEGMENT_COMPLETION_PCT
FROM (
    SELECT
        B.BILL_ID,
        CASE
            WHEN TRIM(NVL(B.BILL_CYC_CD, A.BILL_CYC_CD)) IS NULL OR LENGTH(TRIM(NVL(B.BILL_CYC_CD, A.BILL_CYC_CD))) = 0 THEN 'UNASSIGNED'
            ELSE TRIM(NVL(B.BILL_CYC_CD, A.BILL_CYC_CD))
        END AS BILL_CYCLE_CODE,
        NVL(
            C.BILL_CYCLE_DESCRIPTION,
            CASE
                WHEN TRIM(NVL(B.BILL_CYC_CD, A.BILL_CYC_CD)) IS NULL OR LENGTH(TRIM(NVL(B.BILL_CYC_CD, A.BILL_CYC_CD))) = 0 THEN 'Unassigned Cycle'
                ELSE 'Cycle ' || TRIM(NVL(B.BILL_CYC_CD, A.BILL_CYC_CD))
            END
        ) AS BILL_CYCLE_DESCRIPTION,
        TRUNC(NVL(B.BILL_DT, B.BILL_CRE_DTTM)) AS BILL_DATE,
        TRUNC(B.BILL_CRE_DTTM) AS BILL_CREATE_DATE,
        NVL(G.GENERATED_SEGMENT_COUNT, 0) AS GENERATED_SEGMENT_COUNT,
        NVL(G.PREMISE_COUNT, 0) AS PREMISE_COUNT,
        CASE
            WHEN NVL(E.EXPECTED_SEGMENT_COUNT, 0) > 0 THEN E.EXPECTED_SEGMENT_COUNT
            WHEN NVL(G.GENERATED_SEGMENT_COUNT, 0) > 0 THEN G.GENERATED_SEGMENT_COUNT
            ELSE 1
        END AS EXPECTED_SEGMENT_COUNT
    FROM (
        SELECT
            BILL_ID,
            ACCT_ID,
            BILL_CYC_CD,
            BILL_DT,
            CRE_DTTM AS BILL_CRE_DTTM
        FROM CISADM.CI_BILL
    ) B
    LEFT JOIN CISADM.CI_ACCT A
        ON A.ACCT_ID = B.ACCT_ID
    LEFT JOIN (
        SELECT
            BILL_ID,
            COUNT(DISTINCT BSEG_ID) AS GENERATED_SEGMENT_COUNT,
            COUNT(DISTINCT PREM_ID) AS PREMISE_COUNT
        FROM CISADM.CI_BSEG
        GROUP BY BILL_ID
    ) G
        ON G.BILL_ID = B.BILL_ID
    LEFT JOIN (
        SELECT
            B1.BILL_ID,
            COUNT(DISTINCT S.SA_ID) AS EXPECTED_SEGMENT_COUNT
        FROM CISADM.CI_BILL B1
        JOIN CISADM.CI_SA S
            ON S.ACCT_ID = B1.ACCT_ID
           AND S.SA_STATUS_FLG = '20'
        LEFT JOIN CISADM.CI_SA_SP SSP
            ON SSP.SA_ID = S.SA_ID
           AND SSP.START_DTTM <= NVL(B1.BILL_DT, B1.CRE_DTTM) + 1
           AND (SSP.STOP_DTTM IS NULL OR SSP.STOP_DTTM >= NVL(B1.BILL_DT, B1.CRE_DTTM))
        GROUP BY B1.BILL_ID
    ) E
        ON E.BILL_ID = B.BILL_ID
    LEFT JOIN (
        SELECT
            BILL_CYC_CD,
            MAX(DESCR) AS BILL_CYCLE_DESCRIPTION
        FROM CISADM.CI_BILL_CYC_L
        WHERE LANGUAGE_CD IN ('ENG', 'EN')
        GROUP BY BILL_CYC_CD
    ) C
        ON TRIM(C.BILL_CYC_CD) = TRIM(NVL(B.BILL_CYC_CD, A.BILL_CYC_CD))
) X
GROUP BY
    X.BILL_CYCLE_CODE,
    X.BILL_CYCLE_DESCRIPTION,
    X.BILL_DATE,
    X.BILL_CREATE_DATE
