CREATE TABLE cisadm.bseg_billed_usage_rpt_curr (
    -- Core bill and segment fields
    bseg_id                           VARCHAR2(30)    NOT NULL,
    bill_id                           VARCHAR2(30),
    acct_id                           VARCHAR2(30),
    customer_name                     VARCHAR2(200),
    sa_id                             VARCHAR2(30),
    sa_type_cd                        VARCHAR2(30),
    sa_type_desc                      VARCHAR2(100),
    utility_type_cd                   VARCHAR2(10),
    prem_id                           VARCHAR2(30),
    bseg_stat_flg                     VARCHAR2(10),
    bseg_stat_desc                    VARCHAR2(100),
    bill_stat_flg                     VARCHAR2(10),
    bill_stat_desc                    VARCHAR2(100),
    bill_dt                           DATE,
    due_dt                            DATE,
    bseg_start_dt                     DATE,
    bseg_end_dt                       DATE,
    win_start_dt                      DATE,
    bseg_bill_cyc_cd                  VARCHAR2(10),
    bseg_bill_cyc_desc                VARCHAR2(100),
    bill_bill_cyc_cd                  VARCHAR2(10),
    bill_bill_cyc_desc                VARCHAR2(100),
    load_dttm                         TIMESTAMP DEFAULT SYSTIMESTAMP,
    -- Account fields
    cust_cl_cd                        VARCHAR2(10),
    cust_cl_desc                      VARCHAR2(100),
    coll_cl_cd                        VARCHAR2(10),
    coll_cl_desc                      VARCHAR2(100),
    acct_mgmt_grp_cd                  VARCHAR2(10),
    acct_mgmt_grp_desc                VARCHAR2(100),
    bud_plan_cd                       VARCHAR2(10),
    bud_plan_desc                     VARCHAR2(100),
    -- Aggregated billed usage from CI_BSEG_SQ
    sq_line_count                     NUMBER(18,0),
    determinant_count                 NUMBER(18,0),
    total_init_sq                     NUMBER(22,6),
    total_bill_sq                     NUMBER(22,6),
    sole_uom_cd                       VARCHAR2(30),
    sole_uom_desc                     VARCHAR2(100),
    sole_tou_cd                       VARCHAR2(30),
    sole_tou_desc                     VARCHAR2(100),
    sole_sqi_cd                       VARCHAR2(30),
    sole_sqi_desc                     VARCHAR2(100),
    -- Aggregated read context from CI_BSEG_READ
    read_line_count                   NUMBER(18,0),
    total_msr_qty                     NUMBER(22,6),
    total_final_reg_qty               NUMBER(22,6),
    min_start_read_dttm               TIMESTAMP,
    max_end_read_dttm                 TIMESTAMP,
    -- Aggregated billed amount from CI_BSEG_CALC
    calc_header_count                 NUMBER(18,0),
    total_calc_amt                    NUMBER(15,2),
    rs_count                          NUMBER(18,0),
    sole_rs_cd                        VARCHAR2(30),
    sole_rs_desc                      VARCHAR2(100),
    min_calc_effdt                    DATE,
    max_calc_effdt                    DATE,
    -- Segment detail flags
    est_sw                            VARCHAR2(5),
    closing_bseg_sw                   VARCHAR2(5),
    sq_override_sw                    VARCHAR2(5),
    item_override_sw                  VARCHAR2(5),
    can_rsn_cd                        VARCHAR2(10),
    can_rsn_desc                      VARCHAR2(100),
    rebill_seg_id                     VARCHAR2(30),
    can_bseg_id                       VARCHAR2(30),
    master_bseg_id                    VARCHAR2(30)
);
