-- Purpose:
--   Reconcile calc-line tax split against FT/GL tax amounts.
--
-- Parameters (Oracle bind style):
--   :P_START_DATE           DATE   -- inclusive
--   :P_END_DATE             DATE   -- inclusive (query uses < end_date + 1)
--   :P_BILL_STAT_FLG        CHAR   -- default 'C' when null
--   :P_USE_SQI_TAX_RULE     CHAR   -- 'Y' enables fallback SQI tax classification
--
-- Output grain:
--   BILL_ID + BSEG_ID

WITH CALC_BASE AS (
  SELECT
    B.BILL_ID,
    S.BSEG_ID,
    LN.CALC_AMT,
    LN.SQI_CD,
    RC.RC_TYPE_FLG
  FROM CISADM.CI_BILL B
  JOIN CISADM.CI_BSEG S
    ON S.BILL_ID = B.BILL_ID
  JOIN CISADM.CI_BSEG_CALC C
    ON C.BSEG_ID = S.BSEG_ID
  JOIN CISADM.CI_BSEG_CALC_LN LN
    ON LN.BSEG_ID = C.BSEG_ID
   AND LN.HEADER_SEQ = C.HEADER_SEQ
  LEFT JOIN CISADM.CI_RC RC
    ON RC.RS_CD = C.RS_CD
   AND RC.EFFDT = C.EFFDT
   AND RC.RC_SEQ = LN.RC_SEQ
  WHERE B.BILL_DT >= :P_START_DATE
    AND B.BILL_DT <  :P_END_DATE + 1
    AND B.BILL_STAT_FLG = NVL(:P_BILL_STAT_FLG, 'C')
),
CALC_AGG AS (
  SELECT
    X.BILL_ID,
    X.BSEG_ID,
    SUM(NVL(X.CALC_AMT, 0)) AS CALC_TOTAL_CHARGES,
    SUM(
      CASE
        WHEN X.RC_TYPE_FLG = 'TX' THEN NVL(X.CALC_AMT, 0)
        WHEN :P_USE_SQI_TAX_RULE = 'Y' AND X.SQI_CD IN ('TAX', 'TX') THEN NVL(X.CALC_AMT, 0)
        ELSE 0
      END
    ) AS CALC_TAX_AMOUNT
  FROM CALC_BASE X
  GROUP BY
    X.BILL_ID,
    X.BSEG_ID
),
FT_AGG AS (
  SELECT
    F.BILL_ID,
    F.BSEG_ID,
    SUM(NVL(F.FT_GL_REV_AMT, 0)) AS FT_GL_REV_AMOUNT,
    SUM(NVL(F.FT_GL_TAX_AMT, 0)) AS FT_GL_TAX_AMOUNT
  FROM CISADM.C1_BI_FT_VW F
  WHERE F.ACCOUNTING_DT >= :P_START_DATE
    AND F.ACCOUNTING_DT <  :P_END_DATE + 1
    AND F.BILL_ID IS NOT NULL
  GROUP BY
    F.BILL_ID,
    F.BSEG_ID
)
SELECT
  COALESCE(C.BILL_ID, F.BILL_ID) AS BILL_ID,
  COALESCE(C.BSEG_ID, F.BSEG_ID) AS BSEG_ID,
  NVL(C.CALC_TOTAL_CHARGES, 0) AS CALC_TOTAL_CHARGES,
  NVL(C.CALC_TAX_AMOUNT, 0) AS CALC_TAX_AMOUNT,
  NVL(F.FT_GL_REV_AMOUNT, 0) AS FT_GL_REV_AMOUNT,
  NVL(F.FT_GL_TAX_AMOUNT, 0) AS FT_GL_TAX_AMOUNT,
  NVL(C.CALC_TAX_AMOUNT, 0) - NVL(F.FT_GL_TAX_AMOUNT, 0) AS TAX_DIFF_AMT
FROM CALC_AGG C
FULL OUTER JOIN FT_AGG F
  ON F.BILL_ID = C.BILL_ID
 AND F.BSEG_ID = C.BSEG_ID
ORDER BY
  COALESCE(C.BILL_ID, F.BILL_ID),
  COALESCE(C.BSEG_ID, F.BSEG_ID)
