-- Purpose:
--   Identify which code/description values are truly tax in this environment.
--
-- Why:
--   Descriptions on bill lines (DESCR_ON_BILL) can vary a lot.
--   This script profiles multiple candidate tax rules side-by-side.
--
-- Date Window:
--   Edit PARAMS CTE values once (defaults to last 30 days).
--   No bind variables required.

WITH PARAMS AS (
  SELECT
    TRUNC(SYSDATE) - 30 AS START_DATE,
    TRUNC(SYSDATE)      AS END_DATE
  FROM DUAL
)
SELECT
  START_DATE,
  END_DATE
FROM PARAMS;

prompt ===== 1) RC_TYPE_FLG dictionary values =====
SELECT
  L.FIELD_VALUE AS RC_TYPE_FLG,
  L.DESCR AS RC_TYPE_DESCR
FROM CISADM.CI_LOOKUP_VAL_L L
WHERE L.FIELD_NAME = 'RC_TYPE_FLG'
  AND L.LANGUAGE_CD = 'ENG'
ORDER BY L.FIELD_VALUE;

prompt ===== 2) FT_TYPE_FLG dictionary values (for reversal context) =====
SELECT
  L.FIELD_VALUE AS FT_TYPE_FLG,
  L.DESCR AS FT_TYPE_DESCR
FROM CISADM.CI_LOOKUP_VAL_L L
WHERE L.FIELD_NAME = 'FT_TYPE_FLG'
  AND L.LANGUAGE_CD = 'ENG'
ORDER BY L.FIELD_VALUE;

prompt ===== 3) RC_TYPE_FLG usage in billed calc lines for the date window =====
WITH PARAMS AS (
  SELECT
    TRUNC(SYSDATE) - 30 AS START_DATE,
    TRUNC(SYSDATE)      AS END_DATE
  FROM DUAL
),
BASE AS (
  SELECT
    B.BILL_ID,
    S.BSEG_ID,
    B.BILL_DT,
    NVL(LN.CALC_AMT, 0) AS CALC_AMT,
    LN.SQI_CD,
    LN.DESCR_ON_BILL,
    RC.RC_TYPE_FLG
  FROM CISADM.CI_BILL B
  JOIN CISADM.CI_BSEG S
    ON S.BILL_ID = B.BILL_ID
  JOIN CISADM.CI_BSEG_CALC C
    ON C.BSEG_ID = S.BSEG_ID
  JOIN CISADM.CI_BSEG_CALC_LN LN
    ON LN.BSEG_ID = C.BSEG_ID
   AND LN.HEADER_SEQ = C.HEADER_SEQ
  LEFT JOIN CISADM.CI_RC RC
    ON RC.RS_CD = C.RS_CD
   AND RC.EFFDT = C.EFFDT
   AND RC.RC_SEQ = LN.RC_SEQ
  JOIN PARAMS P
    ON 1 = 1
  WHERE B.BILL_DT >= P.START_DATE
    AND B.BILL_DT <  P.END_DATE + 1
)
SELECT
  X.RC_TYPE_FLG,
  NVL(L.DESCR, '<NO_LOOKUP_DESCR>') AS RC_TYPE_DESCR,
  COUNT(*) AS ROW_COUNT,
  SUM(X.CALC_AMT) AS TOTAL_COMPONENT_AMT,
  SUM(CASE WHEN X.RC_TYPE_FLG = 'TX' THEN X.CALC_AMT ELSE 0 END) AS TAX_AMT_BY_TX_RULE,
  SUM(CASE WHEN X.SQI_CD IN ('TAX','TX') THEN X.CALC_AMT ELSE 0 END) AS TAX_AMT_BY_SQI_RULE,
  SUM(CASE WHEN UPPER(NVL(X.DESCR_ON_BILL, '')) LIKE '%TAX%' THEN X.CALC_AMT ELSE 0 END) AS TAX_AMT_BY_DESCR_RULE
FROM BASE X
LEFT JOIN CISADM.CI_LOOKUP_VAL_L L
  ON L.FIELD_NAME = 'RC_TYPE_FLG'
 AND L.LANGUAGE_CD = 'ENG'
 AND L.FIELD_VALUE = X.RC_TYPE_FLG
GROUP BY
  X.RC_TYPE_FLG,
  NVL(L.DESCR, '<NO_LOOKUP_DESCR>')
ORDER BY
  ABS(SUM(X.CALC_AMT)) DESC,
  X.RC_TYPE_FLG;

prompt ===== 4) Most common tax line names (DESCR_ON_BILL) when RC_TYPE_FLG = 'TX' =====
WITH PARAMS AS (
  SELECT
    TRUNC(SYSDATE) - 30 AS START_DATE,
    TRUNC(SYSDATE)      AS END_DATE
  FROM DUAL
)
SELECT
  LN.DESCR_ON_BILL,
  RC.RC_TYPE_FLG,
  LN.SQI_CD,
  COUNT(*) AS ROW_COUNT,
  SUM(NVL(LN.CALC_AMT, 0)) AS TAX_AMT
FROM CISADM.CI_BILL B
JOIN CISADM.CI_BSEG S
  ON S.BILL_ID = B.BILL_ID
JOIN CISADM.CI_BSEG_CALC C
  ON C.BSEG_ID = S.BSEG_ID
JOIN CISADM.CI_BSEG_CALC_LN LN
  ON LN.BSEG_ID = C.BSEG_ID
 AND LN.HEADER_SEQ = C.HEADER_SEQ
LEFT JOIN CISADM.CI_RC RC
  ON RC.RS_CD = C.RS_CD
 AND RC.EFFDT = C.EFFDT
 AND RC.RC_SEQ = LN.RC_SEQ
JOIN PARAMS P
  ON 1 = 1
WHERE B.BILL_DT >= P.START_DATE
  AND B.BILL_DT <  P.END_DATE + 1
  AND (
    RC.RC_TYPE_FLG = 'TX'
    OR LN.SQI_CD IN ('TAX', 'TX')
    OR UPPER(NVL(LN.DESCR_ON_BILL, '')) LIKE '%TAX%'
  )
GROUP BY
  LN.DESCR_ON_BILL,
  RC.RC_TYPE_FLG,
  LN.SQI_CD
ORDER BY ABS(SUM(NVL(LN.CALC_AMT, 0))) DESC;

prompt ===== 5) SQI codes that look tax-like =====
WITH PARAMS AS (
  SELECT
    TRUNC(SYSDATE) - 30 AS START_DATE,
    TRUNC(SYSDATE)      AS END_DATE
  FROM DUAL
)
SELECT
  LN.SQI_CD,
  COUNT(*) AS ROW_COUNT,
  SUM(NVL(LN.CALC_AMT, 0)) AS TOTAL_AMT
FROM CISADM.CI_BILL B
JOIN CISADM.CI_BSEG S
  ON S.BILL_ID = B.BILL_ID
JOIN CISADM.CI_BSEG_CALC C
  ON C.BSEG_ID = S.BSEG_ID
JOIN CISADM.CI_BSEG_CALC_LN LN
  ON LN.BSEG_ID = C.BSEG_ID
 AND LN.HEADER_SEQ = C.HEADER_SEQ
JOIN PARAMS P
  ON 1 = 1
WHERE B.BILL_DT >= P.START_DATE
  AND B.BILL_DT <  P.END_DATE + 1
  AND (
    LN.SQI_CD IN ('TAX','TX')
    OR UPPER(NVL(LN.SQI_CD, '')) LIKE '%TAX%'
  )
GROUP BY LN.SQI_CD
ORDER BY ABS(SUM(NVL(LN.CALC_AMT, 0))) DESC;
