-- Purpose:
--   Diagnose why FT-tax based queries may return zero rows.
--   Uses C1_BI_FT_VW.FT_GL_TAX_AMT as the tax source.

prompt ===== 1) FT tax presence by time window =====
SELECT
  '30D' AS WINDOW_KEY,
  COUNT(*) AS TOTAL_ROWS,
  SUM(CASE WHEN NVL(FT_GL_TAX_AMT,0) <> 0 THEN 1 ELSE 0 END) AS TAX_ROWS,
  SUM(NVL(FT_GL_TAX_AMT,0)) AS TAX_AMT_NET
FROM CISADM.C1_BI_FT_VW
WHERE ACCOUNTING_DT >= TRUNC(SYSDATE) - 30
  AND ACCOUNTING_DT <  TRUNC(SYSDATE) + 1
UNION ALL
SELECT
  '180D' AS WINDOW_KEY,
  COUNT(*) AS TOTAL_ROWS,
  SUM(CASE WHEN NVL(FT_GL_TAX_AMT,0) <> 0 THEN 1 ELSE 0 END) AS TAX_ROWS,
  SUM(NVL(FT_GL_TAX_AMT,0)) AS TAX_AMT_NET
FROM CISADM.C1_BI_FT_VW
WHERE ACCOUNTING_DT >= TRUNC(SYSDATE) - 180
  AND ACCOUNTING_DT <  TRUNC(SYSDATE) + 1
UNION ALL
SELECT
  '365D' AS WINDOW_KEY,
  COUNT(*) AS TOTAL_ROWS,
  SUM(CASE WHEN NVL(FT_GL_TAX_AMT,0) <> 0 THEN 1 ELSE 0 END) AS TAX_ROWS,
  SUM(NVL(FT_GL_TAX_AMT,0)) AS TAX_AMT_NET
FROM CISADM.C1_BI_FT_VW
WHERE ACCOUNTING_DT >= TRUNC(SYSDATE) - 365
  AND ACCOUNTING_DT <  TRUNC(SYSDATE) + 1;

prompt ===== 2) Key nullability among tax rows (30D) =====
SELECT
  SUM(CASE WHEN BILL_ID IS NULL THEN 1 ELSE 0 END) AS BILL_ID_NULL_ROWS,
  SUM(CASE WHEN BSEG_ID IS NULL THEN 1 ELSE 0 END) AS BSEG_ID_NULL_ROWS,
  SUM(CASE WHEN RS_CD IS NULL THEN 1 ELSE 0 END)   AS RS_CD_NULL_ROWS,
  COUNT(*) AS TAX_ROWS
FROM CISADM.C1_BI_FT_VW
WHERE ACCOUNTING_DT >= TRUNC(SYSDATE) - 30
  AND ACCOUNTING_DT <  TRUNC(SYSDATE) + 1
  AND NVL(FT_GL_TAX_AMT,0) <> 0;

prompt ===== 3) FT type split of tax rows (30D) =====
SELECT
  F.FT_TYPE_FLG,
  NVL(L.DESCR, '<NO_LOOKUP_DESCR>') AS FT_TYPE_DESCR,
  COUNT(*) AS TAX_ROWS,
  SUM(NVL(F.FT_GL_TAX_AMT,0)) AS TAX_AMT_NET
FROM CISADM.C1_BI_FT_VW F
LEFT JOIN CISADM.CI_LOOKUP_VAL_L L
  ON L.FIELD_NAME = 'FT_TYPE_FLG'
 AND L.LANGUAGE_CD = 'ENG'
 AND L.FIELD_VALUE = F.FT_TYPE_FLG
WHERE F.ACCOUNTING_DT >= TRUNC(SYSDATE) - 30
  AND F.ACCOUNTING_DT <  TRUNC(SYSDATE) + 1
  AND NVL(F.FT_GL_TAX_AMT,0) <> 0
GROUP BY
  F.FT_TYPE_FLG,
  NVL(L.DESCR, '<NO_LOOKUP_DESCR>')
ORDER BY ABS(SUM(NVL(F.FT_GL_TAX_AMT,0))) DESC;

