CREATE TABLE cisadm.ft_gl_distribution_rpt_curr (
    -- Core FT GL fields
    ft_id                              VARCHAR2(30)    NOT NULL,
    gl_seq_nbr                         NUMBER(18,0)    NOT NULL,
    gl_acct                            VARCHAR2(100),
    dst_id                             VARCHAR2(30),
    dst_desc                           VARCHAR2(254),
    gl_amount                          NUMBER(15,2),
    statistic_amount                   NUMBER,
    tot_amt_sw                         VARCHAR2(5),
    char_type_cd                       VARCHAR2(30),
    char_val                           VARCHAR2(254),
    load_dttm                          TIMESTAMP DEFAULT SYSTIMESTAMP,
    -- Core FT fields
    ft_type_flg                        VARCHAR2(5),
    ft_type_flg_desc                   VARCHAR2(60),
    accounting_dt                      DATE,
    ars_dt                             DATE,
    ft_cre_dttm                        TIMESTAMP,
    freeze_sw                          VARCHAR2(5),
    freeze_dttm                        TIMESTAMP,
    freeze_user_id                     VARCHAR2(30),
    freeze_user_name                   VARCHAR2(200),
    cur_amt                            NUMBER(15,2),
    tot_amt                            NUMBER(15,2),
    currency_cd                        VARCHAR2(10),
    bill_id                            VARCHAR2(30),
    sa_id                              VARCHAR2(30),
    parent_id                          VARCHAR2(30),
    sibling_id                         VARCHAR2(30),
    gl_distrib_status                  VARCHAR2(5),
    gl_distrib_status_desc             VARCHAR2(60),
    gl_division                        VARCHAR2(30),
    gl_division_desc                   VARCHAR2(254),
    cis_division                       VARCHAR2(30),
    sched_distrib_dt                   DATE,
    xferred_out_sw                     VARCHAR2(5),
    xfer_to_gl_dt                      DATE,
    match_evt_id                       VARCHAR2(30),
    bal_ctl_grp_id                     NUMBER(18,0),
    correction_sw                      VARCHAR2(5),
    new_debit_sw                       VARCHAR2(5),
    show_on_bill_sw                    VARCHAR2(5),
    not_in_ars_sw                      VARCHAR2(5),
    -- SA and account fields
    acct_id                            VARCHAR2(30),
    per_id                             VARCHAR2(30),
    customer_name_upr                  VARCHAR2(200),
    sa_status_flg                      VARCHAR2(10),
    sa_status_desc                     VARCHAR2(100),
    sa_type_cd                         VARCHAR2(10),
    sa_type_desc                       VARCHAR2(100),
    char_prem_id                       VARCHAR2(30),
    bill_cyc_cd                        VARCHAR2(10),
    bill_cyc_desc                      VARCHAR2(100),
    cust_cl_cd                         VARCHAR2(10),
    cust_cl_desc                       VARCHAR2(100),
    coll_cl_cd                         VARCHAR2(10),
    coll_cl_desc                       VARCHAR2(100),
    acct_mgmt_grp_cd                   VARCHAR2(10),
    acct_mgmt_grp_desc                 VARCHAR2(100),
    -- Balance control group fields
    balancing_stat_flg                 VARCHAR2(10),
    balancing_stat_desc                VARCHAR2(100),
    bcg_cur_amt                        NUMBER(15,2),
    bcg_tot_amt                        NUMBER(15,2),
    bcg_cur_bal                        NUMBER(15,2),
    bcg_tot_bal                        NUMBER(15,2),
    bcg_cre_dttm                       TIMESTAMP,
    -- Bill segment fields
    bseg_id                            VARCHAR2(30),
    bseg_stat_flg                      VARCHAR2(10),
    bseg_stat_desc                     VARCHAR2(100),
    bseg_bill_cyc_cd                   VARCHAR2(10),
    bseg_bill_cyc_desc                 VARCHAR2(100),
    bseg_start_dt                      DATE,
    bseg_end_dt                        DATE,
    bseg_prem_id                       VARCHAR2(30),
    bseg_est_sw                        VARCHAR2(5),
    bseg_closing_sw                    VARCHAR2(5),
    bseg_can_rsn_cd                    VARCHAR2(10),
    bseg_can_rsn_desc                  VARCHAR2(100),
    -- Adjustment fields
    adj_id                             VARCHAR2(30),
    adj_status_flg                     VARCHAR2(10),
    adj_status_desc                    VARCHAR2(100),
    adj_type_cd                        VARCHAR2(10),
    adj_type_desc                      VARCHAR2(100),
    adj_can_rsn_cd                     VARCHAR2(10),
    adj_can_rsn_desc                   VARCHAR2(100),
    adj_amt                            NUMBER(15,2),
    xfer_adj_id                        VARCHAR2(30),
    behalf_sa_id                       VARCHAR2(30),
    base_amt                           NUMBER(15,2),
    gen_ref_dt                         DATE,
    appr_req_id                        VARCHAR2(30),
    -- Payment fields
    pay_seg_id                         VARCHAR2(30),
    pay_id                             VARCHAR2(30),
    pay_seg_amt                        NUMBER(15,2),
    pay_match_evt_id                   VARCHAR2(30)
);
