CREATE TABLE cisadm.ft_rpt_curr (
    -- Core FT fields
    ft_id                  VARCHAR2(30)    NOT NULL,
    ft_type_flg            VARCHAR2(5),
    ft_type_flg_desc       VARCHAR2(60),
    accounting_dt          DATE,
    cre_dttm               TIMESTAMP,
    freeze_dttm            TIMESTAMP,
    freeze_user_id         VARCHAR2(30),
    freeze_user_name       VARCHAR2(200),
    cur_amt                NUMBER(15,2),
    tot_amt                NUMBER(15,2),
    currency_cd            VARCHAR2(10),
    bill_id                VARCHAR2(30),
    sa_id                  VARCHAR2(30),
    parent_id              VARCHAR2(30),
    sibling_id             VARCHAR2(30),
    gl_distrib_status      VARCHAR2(5),
    gl_distrib_status_desc VARCHAR2(60),
    acct_id                VARCHAR2(30),
    load_dttm              TIMESTAMP DEFAULT SYSTIMESTAMP,
    -- SA fields
    sa_status_flg          VARCHAR2(10),
    sa_status_desc         VARCHAR2(100),
    sa_type_cd             VARCHAR2(10),
    sa_type_desc           VARCHAR2(100),
    cust_cl_cd             VARCHAR2(10),
    cust_cl_desc           VARCHAR2(100),
    coll_cl_cd             VARCHAR2(10),
    coll_cl_desc           VARCHAR2(100),
    bill_cyc_cd            VARCHAR2(10),
    bill_cyc_desc          VARCHAR2(100),
    acct_mgmt_grp_cd       VARCHAR2(10),
    acct_mgmt_grp_desc     VARCHAR2(100),
    -- Bill Segment fields
    bseg_id                VARCHAR2(30),
    bseg_stat_flg          VARCHAR2(10),
    bseg_stat_desc         VARCHAR2(100),
    start_dt               DATE,
    end_dt                 DATE,
    -- Adjustment fields
    adj_id                 VARCHAR2(30),
    adj_status_flg         VARCHAR2(10),
    adj_status_desc        VARCHAR2(100),
    adj_type_cd            VARCHAR2(10),
    adj_type_desc          VARCHAR2(100),
    adj_amt                NUMBER(15,2),
    -- Payment fields
    pay_seg_id             VARCHAR2(30),
    pay_id                 VARCHAR2(30),
    pay_seg_amt            NUMBER(15,2)
);
