-- Purpose:
--   Read-only checks for unbilled snapshot quality and reasonableness.
--
-- Bind:
--   :P_AS_OF_DATE DATE default SYSDATE

-- 1) Topline totals
SELECT
  S.AS_OF_DT,
  COUNT(*) AS SA_ROWS,
  COUNT(DISTINCT S.ACCT_ID) AS ACCT_COUNT,
  SUM(NVL(S.UNBILLED_USAGE_QTY, 0)) AS TOTAL_UNBILLED_QTY,
  SUM(NVL(S.EST_USAGE_AMT, 0)) AS TOTAL_EST_USAGE_AMT,
  SUM(NVL(S.EST_OTHER_AMT, 0)) AS TOTAL_EST_OTHER_AMT,
  SUM(NVL(S.EST_TAX_AMT, 0)) AS TOTAL_EST_TAX_AMT,
  SUM(NVL(S.EST_TOTAL_AMT, 0)) AS TOTAL_EST_UNBILLED_AMT
FROM CISADM.C1_BI_UNBILLED_REV_SNAP S
WHERE S.AS_OF_DT = TRUNC(NVL(:P_AS_OF_DATE, SYSDATE))
GROUP BY S.AS_OF_DT;

-- 2) Sanity checks (unexpected negatives / null anchors)
SELECT
  SUM(CASE WHEN UNBILLED_DAYS < 0 THEN 1 ELSE 0 END) AS NEG_DAY_ROWS,
  SUM(CASE WHEN EST_TOTAL_AMT < 0 THEN 1 ELSE 0 END) AS NEG_TOTAL_ROWS,
  SUM(CASE WHEN LAST_BSEG_END_DT IS NULL THEN 1 ELSE 0 END) AS NULL_LAST_BILL_ROWS
FROM CISADM.C1_BI_UNBILLED_REV_SNAP
WHERE AS_OF_DT = TRUNC(NVL(:P_AS_OF_DATE, SYSDATE));

-- 3) Largest accounts by estimated unbilled amount
SELECT *
FROM (
  SELECT
    S.ACCT_ID,
    SUM(NVL(S.EST_TOTAL_AMT, 0)) AS EST_TOTAL_AMT,
    SUM(NVL(S.EST_USAGE_AMT, 0)) AS EST_USAGE_AMT,
    SUM(NVL(S.EST_OTHER_AMT, 0)) AS EST_OTHER_AMT,
    SUM(NVL(S.EST_TAX_AMT, 0)) AS EST_TAX_AMT
  FROM CISADM.C1_BI_UNBILLED_REV_SNAP S
  WHERE S.AS_OF_DT = TRUNC(NVL(:P_AS_OF_DATE, SYSDATE))
  GROUP BY S.ACCT_ID
  ORDER BY EST_TOTAL_AMT DESC
)
WHERE ROWNUM <= 50;

-- 4) Day-over-day movement (current day vs prior day)
SELECT
  CURR.ACCT_ID,
  CURR.EST_TOTAL_AMT AS CURR_EST_TOTAL_AMT,
  NVL(PRIOR.EST_TOTAL_AMT, 0) AS PRIOR_EST_TOTAL_AMT,
  CURR.EST_TOTAL_AMT - NVL(PRIOR.EST_TOTAL_AMT, 0) AS DELTA_EST_TOTAL_AMT
FROM (
  SELECT
    ACCT_ID,
    SUM(NVL(EST_TOTAL_AMT, 0)) AS EST_TOTAL_AMT
  FROM CISADM.C1_BI_UNBILLED_REV_SNAP
  WHERE AS_OF_DT = TRUNC(NVL(:P_AS_OF_DATE, SYSDATE))
  GROUP BY ACCT_ID
) CURR
LEFT JOIN (
  SELECT
    ACCT_ID,
    SUM(NVL(EST_TOTAL_AMT, 0)) AS EST_TOTAL_AMT
  FROM CISADM.C1_BI_UNBILLED_REV_SNAP
  WHERE AS_OF_DT = TRUNC(NVL(:P_AS_OF_DATE, SYSDATE)) - 1
  GROUP BY ACCT_ID
) PRIOR
  ON PRIOR.ACCT_ID = CURR.ACCT_ID
ORDER BY DELTA_EST_TOTAL_AMT DESC
FETCH FIRST 100 ROWS ONLY;
