-- Generated by scripts/build_workstream_table_health_sql.py
-- Read-only COUNT(*) for physical workstream tables (no custom views).
-- Run: python3 scripts/local/run_client_oracle_sql.py --client demo --file sql/diagnostics/cisadm_workstream_table_health.sql

SELECT 'BSEG_BILLED_USAGE_RPT_CURR' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'BSEG_BILLED_USAGE_RPT_CURR') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'BSEG_BILLED_USAGE_RPT_CURR') THEN (SELECT COUNT(*) FROM cisadm.bseg_billed_usage_rpt_curr) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'BSEG_SQ_USAGE_RPT_CURR' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'BSEG_SQ_USAGE_RPT_CURR') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'BSEG_SQ_USAGE_RPT_CURR') THEN (SELECT COUNT(*) FROM cisadm.bseg_sq_usage_rpt_curr) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'C1_PA_RQST' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'C1_PA_RQST') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'C1_PA_RQST') THEN (SELECT COUNT(*) FROM cisadm.c1_pa_rqst) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'C1_PA_RQST_REL_OBJ' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'C1_PA_RQST_REL_OBJ') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'C1_PA_RQST_REL_OBJ') THEN (SELECT COUNT(*) FROM cisadm.c1_pa_rqst_rel_obj) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'C1_PER_CONTDET' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'C1_PER_CONTDET') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'C1_PER_CONTDET') THEN (SELECT COUNT(*) FROM cisadm.c1_per_contdet) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'C1_REPRESENTATIVE' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'C1_REPRESENTATIVE') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'C1_REPRESENTATIVE') THEN (SELECT COUNT(*) FROM cisadm.c1_representative) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'C1_REPRESENTATIVE_L' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'C1_REPRESENTATIVE_L') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'C1_REPRESENTATIVE_L') THEN (SELECT COUNT(*) FROM cisadm.c1_representative_l) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'C1_USAGE' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'C1_USAGE') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'C1_USAGE') THEN (SELECT COUNT(*) FROM cisadm.c1_usage) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_ACCT' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_ACCT') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_ACCT') THEN (SELECT COUNT(*) FROM cisadm.ci_acct) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_ACCT_ALERT' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_ACCT_ALERT') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_ACCT_ALERT') THEN (SELECT COUNT(*) FROM cisadm.ci_acct_alert) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_ACCT_MGMT_GR_L' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_ACCT_MGMT_GR_L') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_ACCT_MGMT_GR_L') THEN (SELECT COUNT(*) FROM cisadm.ci_acct_mgmt_gr_l) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_ACCT_PER' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_ACCT_PER') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_ACCT_PER') THEN (SELECT COUNT(*) FROM cisadm.ci_acct_per) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_ACC_GRP_L' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_ACC_GRP_L') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_ACC_GRP_L') THEN (SELECT COUNT(*) FROM cisadm.ci_acc_grp_l) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_ADJ' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_ADJ') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_ADJ') THEN (SELECT COUNT(*) FROM cisadm.ci_adj) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_ADJ_CAN_RSN_L' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_ADJ_CAN_RSN_L') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_ADJ_CAN_RSN_L') THEN (SELECT COUNT(*) FROM cisadm.ci_adj_can_rsn_l) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_ADJ_TYPE_L' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_ADJ_TYPE_L') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_ADJ_TYPE_L') THEN (SELECT COUNT(*) FROM cisadm.ci_adj_type_l) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_ALERT_TYPE_L' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_ALERT_TYPE_L') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_ALERT_TYPE_L') THEN (SELECT COUNT(*) FROM cisadm.ci_alert_type_l) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_BAL_CTL_GRP' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_BAL_CTL_GRP') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_BAL_CTL_GRP') THEN (SELECT COUNT(*) FROM cisadm.ci_bal_ctl_grp) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_BANK_ACCOUNT_L' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_BANK_ACCOUNT_L') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_BANK_ACCOUNT_L') THEN (SELECT COUNT(*) FROM cisadm.ci_bank_account_l) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_BANK_L' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_BANK_L') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_BANK_L') THEN (SELECT COUNT(*) FROM cisadm.ci_bank_l) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_BATCH_CTRL' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_BATCH_CTRL') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_BATCH_CTRL') THEN (SELECT COUNT(*) FROM cisadm.ci_batch_ctrl) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_BATCH_CTRL_L' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_BATCH_CTRL_L') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_BATCH_CTRL_L') THEN (SELECT COUNT(*) FROM cisadm.ci_batch_ctrl_l) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_BATCH_INST' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_BATCH_INST') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_BATCH_INST') THEN (SELECT COUNT(*) FROM cisadm.ci_batch_inst) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_BATCH_RUN' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_BATCH_RUN') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_BATCH_RUN') THEN (SELECT COUNT(*) FROM cisadm.ci_batch_run) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_BATCH_THD' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_BATCH_THD') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_BATCH_THD') THEN (SELECT COUNT(*) FROM cisadm.ci_batch_thd) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_BILL' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_BILL') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_BILL') THEN (SELECT COUNT(*) FROM cisadm.ci_bill) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_BILL_CAN_RSN_L' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_BILL_CAN_RSN_L') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_BILL_CAN_RSN_L') THEN (SELECT COUNT(*) FROM cisadm.ci_bill_can_rsn_l) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_BILL_CHG' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_BILL_CHG') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_BILL_CHG') THEN (SELECT COUNT(*) FROM cisadm.ci_bill_chg) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_BILL_CYC_L' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_BILL_CYC_L') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_BILL_CYC_L') THEN (SELECT COUNT(*) FROM cisadm.ci_bill_cyc_l) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_BSEG' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_BSEG') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_BSEG') THEN (SELECT COUNT(*) FROM cisadm.ci_bseg) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_BSEG_CALC' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_BSEG_CALC') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_BSEG_CALC') THEN (SELECT COUNT(*) FROM cisadm.ci_bseg_calc) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_BSEG_CALC_LN' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_BSEG_CALC_LN') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_BSEG_CALC_LN') THEN (SELECT COUNT(*) FROM cisadm.ci_bseg_calc_ln) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_BSEG_EXCP' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_BSEG_EXCP') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_BSEG_EXCP') THEN (SELECT COUNT(*) FROM cisadm.ci_bseg_excp) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_BSEG_ITEM' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_BSEG_ITEM') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_BSEG_ITEM') THEN (SELECT COUNT(*) FROM cisadm.ci_bseg_item) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_BSEG_READ' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_BSEG_READ') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_BSEG_READ') THEN (SELECT COUNT(*) FROM cisadm.ci_bseg_read) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_BSEG_SQ' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_BSEG_SQ') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_BSEG_SQ') THEN (SELECT COUNT(*) FROM cisadm.ci_bseg_sq) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_BUD_PLAN_L' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_BUD_PLAN_L') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_BUD_PLAN_L') THEN (SELECT COUNT(*) FROM cisadm.ci_bud_plan_l) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_B_CHG_LINE' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_B_CHG_LINE') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_B_CHG_LINE') THEN (SELECT COUNT(*) FROM cisadm.ci_b_chg_line) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_CASE' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_CASE') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_CASE') THEN (SELECT COUNT(*) FROM cisadm.ci_case) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_CASE_STATUS_L' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_CASE_STATUS_L') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_CASE_STATUS_L') THEN (SELECT COUNT(*) FROM cisadm.ci_case_status_l) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_CASE_TYPE_L' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_CASE_TYPE_L') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_CASE_TYPE_L') THEN (SELECT COUNT(*) FROM cisadm.ci_case_type_l) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_CC' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_CC') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_CC') THEN (SELECT COUNT(*) FROM cisadm.ci_cc) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_CC_CL_L' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_CC_CL_L') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_CC_CL_L') THEN (SELECT COUNT(*) FROM cisadm.ci_cc_cl_l) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_CC_TYPE_L' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_CC_TYPE_L') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_CC_TYPE_L') THEN (SELECT COUNT(*) FROM cisadm.ci_cc_type_l) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_CHAR_VAL_L' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_CHAR_VAL_L') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_CHAR_VAL_L') THEN (SELECT COUNT(*) FROM cisadm.ci_char_val_l) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_CIS_DIVISION_L' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_CIS_DIVISION_L') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_CIS_DIVISION_L') THEN (SELECT COUNT(*) FROM cisadm.ci_cis_division_l) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_COLL_CL_L' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_COLL_CL_L') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_COLL_CL_L') THEN (SELECT COUNT(*) FROM cisadm.ci_coll_cl_l) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_COLL_PROC' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_COLL_PROC') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_COLL_PROC') THEN (SELECT COUNT(*) FROM cisadm.ci_coll_proc) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_CUST_CL_L' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_CUST_CL_L') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_CUST_CL_L') THEN (SELECT COUNT(*) FROM cisadm.ci_cust_cl_l) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_DEBT_CL_L' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_DEBT_CL_L') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_DEBT_CL_L') THEN (SELECT COUNT(*) FROM cisadm.ci_debt_cl_l) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_DEP_CL_L' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_DEP_CL_L') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_DEP_CL_L') THEN (SELECT COUNT(*) FROM cisadm.ci_dep_cl_l) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_DEP_CTL' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_DEP_CTL') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_DEP_CTL') THEN (SELECT COUNT(*) FROM cisadm.ci_dep_ctl) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_ENRL' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_ENRL') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_ENRL') THEN (SELECT COUNT(*) FROM cisadm.ci_enrl) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_FT' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_FT') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_FT') THEN (SELECT COUNT(*) FROM cisadm.ci_ft) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_FT_GL' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_FT_GL') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_FT_GL') THEN (SELECT COUNT(*) FROM cisadm.ci_ft_gl) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_FT_PROC' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_FT_PROC') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_FT_PROC') THEN (SELECT COUNT(*) FROM cisadm.ci_ft_proc) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_GEO_TYPE_L' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_GEO_TYPE_L') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_GEO_TYPE_L') THEN (SELECT COUNT(*) FROM cisadm.ci_geo_type_l) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_GL_DIVISION_L' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_GL_DIVISION_L') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_GL_DIVISION_L') THEN (SELECT COUNT(*) FROM cisadm.ci_gl_division_l) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_LANDLORD' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_LANDLORD') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_LANDLORD') THEN (SELECT COUNT(*) FROM cisadm.ci_landlord) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_LETTER_TMPL_L' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_LETTER_TMPL_L') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_LETTER_TMPL_L') THEN (SELECT COUNT(*) FROM cisadm.ci_letter_tmpl_l) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_LL_DETAIL' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_LL_DETAIL') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_LL_DETAIL') THEN (SELECT COUNT(*) FROM cisadm.ci_ll_detail) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_LOOKUP_VAL_L' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_LOOKUP_VAL_L') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_LOOKUP_VAL_L') THEN (SELECT COUNT(*) FROM cisadm.ci_lookup_val_l) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_MATCH_TYPE_L' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_MATCH_TYPE_L') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_MATCH_TYPE_L') THEN (SELECT COUNT(*) FROM cisadm.ci_match_type_l) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_MR_INSTR_L' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_MR_INSTR_L') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_MR_INSTR_L') THEN (SELECT COUNT(*) FROM cisadm.ci_mr_instr_l) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_MR_WARN_L' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_MR_WARN_L') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_MR_WARN_L') THEN (SELECT COUNT(*) FROM cisadm.ci_mr_warn_l) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_MSG_L' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_MSG_L') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_MSG_L') THEN (SELECT COUNT(*) FROM cisadm.ci_msg_l) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_NB_RULE_L' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_NB_RULE_L') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_NB_RULE_L') THEN (SELECT COUNT(*) FROM cisadm.ci_nb_rule_l) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_NT_XID_L' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_NT_XID_L') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_NT_XID_L') THEN (SELECT COUNT(*) FROM cisadm.ci_nt_xid_l) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_PAY' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_PAY') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_PAY') THEN (SELECT COUNT(*) FROM cisadm.ci_pay) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_PAY_CAN_RSN_L' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_PAY_CAN_RSN_L') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_PAY_CAN_RSN_L') THEN (SELECT COUNT(*) FROM cisadm.ci_pay_can_rsn_l) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_PAY_EVENT' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_PAY_EVENT') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_PAY_EVENT') THEN (SELECT COUNT(*) FROM cisadm.ci_pay_event) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_PAY_METH_L' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_PAY_METH_L') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_PAY_METH_L') THEN (SELECT COUNT(*) FROM cisadm.ci_pay_meth_l) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_PAY_SEG' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_PAY_SEG') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_PAY_SEG') THEN (SELECT COUNT(*) FROM cisadm.ci_pay_seg) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_PAY_TNDR' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_PAY_TNDR') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_PAY_TNDR') THEN (SELECT COUNT(*) FROM cisadm.ci_pay_tndr) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_PER' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_PER') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_PER') THEN (SELECT COUNT(*) FROM cisadm.ci_per) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_PER_NAME' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_PER_NAME') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_PER_NAME') THEN (SELECT COUNT(*) FROM cisadm.ci_per_name) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_PER_PER' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_PER_PER') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_PER_PER') THEN (SELECT COUNT(*) FROM cisadm.ci_per_per) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_PER_REL_TYPE_L' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_PER_REL_TYPE_L') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_PER_REL_TYPE_L') THEN (SELECT COUNT(*) FROM cisadm.ci_per_rel_type_l) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_PHONE_TYPE_L' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_PHONE_TYPE_L') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_PHONE_TYPE_L') THEN (SELECT COUNT(*) FROM cisadm.ci_phone_type_l) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_PP' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_PP') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_PP') THEN (SELECT COUNT(*) FROM cisadm.ci_pp) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_PP_SCHED_PAY' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_PP_SCHED_PAY') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_PP_SCHED_PAY') THEN (SELECT COUNT(*) FROM cisadm.ci_pp_sched_pay) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_PP_TYPE_L' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_PP_TYPE_L') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_PP_TYPE_L') THEN (SELECT COUNT(*) FROM cisadm.ci_pp_type_l) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_PREM' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_PREM') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_PREM') THEN (SELECT COUNT(*) FROM cisadm.ci_prem) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_PREM_CHAR' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_PREM_CHAR') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_PREM_CHAR') THEN (SELECT COUNT(*) FROM cisadm.ci_prem_char) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_PREM_GEO' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_PREM_GEO') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_PREM_GEO') THEN (SELECT COUNT(*) FROM cisadm.ci_prem_geo) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_PREM_TYPE_L' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_PREM_TYPE_L') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_PREM_TYPE_L') THEN (SELECT COUNT(*) FROM cisadm.ci_prem_type_l) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_PROP_DCL_RSN_L' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_PROP_DCL_RSN_L') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_PROP_DCL_RSN_L') THEN (SELECT COUNT(*) FROM cisadm.ci_prop_dcl_rsn_l) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_REV_CL_L' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_REV_CL_L') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_REV_CL_L') THEN (SELECT COUNT(*) FROM cisadm.ci_rev_cl_l) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_ROLE_L' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_ROLE_L') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_ROLE_L') THEN (SELECT COUNT(*) FROM cisadm.ci_role_l) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_RS_L' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_RS_L') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_RS_L') THEN (SELECT COUNT(*) FROM cisadm.ci_rs_l) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_SA' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_SA') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_SA') THEN (SELECT COUNT(*) FROM cisadm.ci_sa) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_SA_SP' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_SA_SP') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_SA_SP') THEN (SELECT COUNT(*) FROM cisadm.ci_sa_sp) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_SA_TYPE' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_SA_TYPE') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_SA_TYPE') THEN (SELECT COUNT(*) FROM cisadm.ci_sa_type) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_SA_TYPE_L' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_SA_TYPE_L') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_SA_TYPE_L') THEN (SELECT COUNT(*) FROM cisadm.ci_sa_type_l) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_SEV_EVT' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_SEV_EVT') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_SEV_EVT') THEN (SELECT COUNT(*) FROM cisadm.ci_sev_evt) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_SEV_EVT_TYPE_L' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_SEV_EVT_TYPE_L') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_SEV_EVT_TYPE_L') THEN (SELECT COUNT(*) FROM cisadm.ci_sev_evt_type_l) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_SEV_PROC' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_SEV_PROC') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_SEV_PROC') THEN (SELECT COUNT(*) FROM cisadm.ci_sev_proc) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_SEV_PROC_TMP_L' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_SEV_PROC_TMP_L') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_SEV_PROC_TMP_L') THEN (SELECT COUNT(*) FROM cisadm.ci_sev_proc_tmp_l) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_SIC_L' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_SIC_L') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_SIC_L') THEN (SELECT COUNT(*) FROM cisadm.ci_sic_l) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_SP' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_SP') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_SP') THEN (SELECT COUNT(*) FROM cisadm.ci_sp) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_SP_TYPE_L' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_SP_TYPE_L') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_SP_TYPE_L') THEN (SELECT COUNT(*) FROM cisadm.ci_sp_type_l) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_SQI_L' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_SQI_L') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_SQI_L') THEN (SELECT COUNT(*) FROM cisadm.ci_sqi_l) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_SS_OPT_L' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_SS_OPT_L') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_SS_OPT_L') THEN (SELECT COUNT(*) FROM cisadm.ci_ss_opt_l) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_STATE_L' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_STATE_L') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_STATE_L') THEN (SELECT COUNT(*) FROM cisadm.ci_state_l) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_SVC_TYPE_L' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_SVC_TYPE_L') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_SVC_TYPE_L') THEN (SELECT COUNT(*) FROM cisadm.ci_svc_type_l) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_TD_DRLKEY' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_TD_DRLKEY') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_TD_DRLKEY') THEN (SELECT COUNT(*) FROM cisadm.ci_td_drlkey) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_TD_DRLKEY_TY' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_TD_DRLKEY_TY') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_TD_DRLKEY_TY') THEN (SELECT COUNT(*) FROM cisadm.ci_td_drlkey_ty) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_TD_ENTRY' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_TD_ENTRY') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_TD_ENTRY') THEN (SELECT COUNT(*) FROM cisadm.ci_td_entry) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_TD_TYPE_L' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_TD_TYPE_L') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_TD_TYPE_L') THEN (SELECT COUNT(*) FROM cisadm.ci_td_type_l) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_TENDER_TYPE_L' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_TENDER_TYPE_L') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_TENDER_TYPE_L') THEN (SELECT COUNT(*) FROM cisadm.ci_tender_type_l) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_THRD_PTY_L' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_THRD_PTY_L') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_THRD_PTY_L') THEN (SELECT COUNT(*) FROM cisadm.ci_thrd_pty_l) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_TIME_ZONE_L' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_TIME_ZONE_L') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_TIME_ZONE_L') THEN (SELECT COUNT(*) FROM cisadm.ci_time_zone_l) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_TNDR_CTL' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_TNDR_CTL') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_TNDR_CTL') THEN (SELECT COUNT(*) FROM cisadm.ci_tndr_ctl) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_TNDR_DEP' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_TNDR_DEP') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_TNDR_DEP') THEN (SELECT COUNT(*) FROM cisadm.ci_tndr_dep) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_TNDR_END_BAL' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_TNDR_END_BAL') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_TNDR_END_BAL') THEN (SELECT COUNT(*) FROM cisadm.ci_tndr_end_bal) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_TNDR_SRCE_L' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_TNDR_SRCE_L') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_TNDR_SRCE_L') THEN (SELECT COUNT(*) FROM cisadm.ci_tndr_srce_l) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_TOU_L' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_TOU_L') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_TOU_L') THEN (SELECT COUNT(*) FROM cisadm.ci_tou_l) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_TREND_AREA_L' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_TREND_AREA_L') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_TREND_AREA_L') THEN (SELECT COUNT(*) FROM cisadm.ci_trend_area_l) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_UOM_L' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_UOM_L') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_UOM_L') THEN (SELECT COUNT(*) FROM cisadm.ci_uom_l) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_WO_CNTL_L' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_WO_CNTL_L') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_WO_CNTL_L') THEN (SELECT COUNT(*) FROM cisadm.ci_wo_cntl_l) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_WO_DEBT_CL_L' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_WO_DEBT_CL_L') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_WO_DEBT_CL_L') THEN (SELECT COUNT(*) FROM cisadm.ci_wo_debt_cl_l) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_WO_EVT' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_WO_EVT') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_WO_EVT') THEN (SELECT COUNT(*) FROM cisadm.ci_wo_evt) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_WO_EVT_TYP_L' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_WO_EVT_TYP_L') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_WO_EVT_TYP_L') THEN (SELECT COUNT(*) FROM cisadm.ci_wo_evt_typ_l) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_WO_PROC' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_WO_PROC') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_WO_PROC') THEN (SELECT COUNT(*) FROM cisadm.ci_wo_proc) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_WO_PROC_SA' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_WO_PROC_SA') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_WO_PROC_SA') THEN (SELECT COUNT(*) FROM cisadm.ci_wo_proc_sa) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'CI_WO_PROC_TMPL_L' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_WO_PROC_TMPL_L') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'CI_WO_PROC_TMPL_L') THEN (SELECT COUNT(*) FROM cisadm.ci_wo_proc_tmpl_l) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'D1_ACTIVITY' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'D1_ACTIVITY') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'D1_ACTIVITY') THEN (SELECT COUNT(*) FROM cisadm.d1_activity) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'D1_ACTIVITY_CHAR' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'D1_ACTIVITY_CHAR') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'D1_ACTIVITY_CHAR') THEN (SELECT COUNT(*) FROM cisadm.d1_activity_char) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'D1_ACTIVITY_REL' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'D1_ACTIVITY_REL') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'D1_ACTIVITY_REL') THEN (SELECT COUNT(*) FROM cisadm.d1_activity_rel) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'D1_ACTIVITY_REL_OBJ' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'D1_ACTIVITY_REL_OBJ') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'D1_ACTIVITY_REL_OBJ') THEN (SELECT COUNT(*) FROM cisadm.d1_activity_rel_obj) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'D1_ACTIVITY_TYPE' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'D1_ACTIVITY_TYPE') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'D1_ACTIVITY_TYPE') THEN (SELECT COUNT(*) FROM cisadm.d1_activity_type) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'D1_ACTIVITY_TYPE_L' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'D1_ACTIVITY_TYPE_L') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'D1_ACTIVITY_TYPE_L') THEN (SELECT COUNT(*) FROM cisadm.d1_activity_type_l) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'D1_COMMAND_SET_L' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'D1_COMMAND_SET_L') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'D1_COMMAND_SET_L') THEN (SELECT COUNT(*) FROM cisadm.d1_command_set_l) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'D1_CONTACT_IDENTIFIER' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'D1_CONTACT_IDENTIFIER') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'D1_CONTACT_IDENTIFIER') THEN (SELECT COUNT(*) FROM cisadm.d1_contact_identifier) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'D1_DIVISION_L' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'D1_DIVISION_L') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'D1_DIVISION_L') THEN (SELECT COUNT(*) FROM cisadm.d1_division_l) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'D1_DVC' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'D1_DVC') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'D1_DVC') THEN (SELECT COUNT(*) FROM cisadm.d1_dvc) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'D1_DVC_CFG' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'D1_DVC_CFG') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'D1_DVC_CFG') THEN (SELECT COUNT(*) FROM cisadm.d1_dvc_cfg) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'D1_DVC_CFG_TYPE_L' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'D1_DVC_CFG_TYPE_L') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'D1_DVC_CFG_TYPE_L') THEN (SELECT COUNT(*) FROM cisadm.d1_dvc_cfg_type_l) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'D1_DVC_EVT' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'D1_DVC_EVT') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'D1_DVC_EVT') THEN (SELECT COUNT(*) FROM cisadm.d1_dvc_evt) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'D1_DVC_EVT_TYPE_L' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'D1_DVC_EVT_TYPE_L') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'D1_DVC_EVT_TYPE_L') THEN (SELECT COUNT(*) FROM cisadm.d1_dvc_evt_type_l) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'D1_DVC_TYPE_L' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'D1_DVC_TYPE_L') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'D1_DVC_TYPE_L') THEN (SELECT COUNT(*) FROM cisadm.d1_dvc_type_l) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'D1_EXCP_TYPE_L' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'D1_EXCP_TYPE_L') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'D1_EXCP_TYPE_L') THEN (SELECT COUNT(*) FROM cisadm.d1_excp_type_l) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'D1_INIT_MSRMT_DATA' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'D1_INIT_MSRMT_DATA') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'D1_INIT_MSRMT_DATA') THEN (SELECT COUNT(*) FROM cisadm.d1_init_msrmt_data) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'D1_INSTALL_EVT' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'D1_INSTALL_EVT') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'D1_INSTALL_EVT') THEN (SELECT COUNT(*) FROM cisadm.d1_install_evt) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'D1_MANUFACTURER_L' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'D1_MANUFACTURER_L') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'D1_MANUFACTURER_L') THEN (SELECT COUNT(*) FROM cisadm.d1_manufacturer_l) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'D1_MEASR_COMP' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'D1_MEASR_COMP') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'D1_MEASR_COMP') THEN (SELECT COUNT(*) FROM cisadm.d1_measr_comp) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'D1_MKT_L' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'D1_MKT_L') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'D1_MKT_L') THEN (SELECT COUNT(*) FROM cisadm.d1_mkt_l) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'D1_MODEL_L' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'D1_MODEL_L') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'D1_MODEL_L') THEN (SELECT COUNT(*) FROM cisadm.d1_model_l) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'D1_MSRMT_CYC_L' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'D1_MSRMT_CYC_L') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'D1_MSRMT_CYC_L') THEN (SELECT COUNT(*) FROM cisadm.d1_msrmt_cyc_l) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'D1_MSRMT_CYC_RTE_L' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'D1_MSRMT_CYC_RTE_L') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'D1_MSRMT_CYC_RTE_L') THEN (SELECT COUNT(*) FROM cisadm.d1_msrmt_cyc_rte_l) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'D1_MSRMT_RPT_CURR' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'D1_MSRMT_RPT_CURR') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'D1_MSRMT_RPT_CURR') THEN (SELECT COUNT(*) FROM cisadm.d1_msrmt_rpt_curr) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'D1_SP' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'D1_SP') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'D1_SP') THEN (SELECT COUNT(*) FROM cisadm.d1_sp) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'D1_SPR_L' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'D1_SPR_L') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'D1_SPR_L') THEN (SELECT COUNT(*) FROM cisadm.d1_spr_l) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'D1_SP_EQPMNT' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'D1_SP_EQPMNT') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'D1_SP_EQPMNT') THEN (SELECT COUNT(*) FROM cisadm.d1_sp_eqpmnt) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'D1_SP_TYPE_L' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'D1_SP_TYPE_L') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'D1_SP_TYPE_L') THEN (SELECT COUNT(*) FROM cisadm.d1_sp_type_l) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'D1_USAGE' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'D1_USAGE') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'D1_USAGE') THEN (SELECT COUNT(*) FROM cisadm.d1_usage) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'D1_USAGE_EXCP' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'D1_USAGE_EXCP') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'D1_USAGE_EXCP') THEN (SELECT COUNT(*) FROM cisadm.d1_usage_excp) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'D1_USAGE_EXCP_TYPE_L' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'D1_USAGE_EXCP_TYPE_L') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'D1_USAGE_EXCP_TYPE_L') THEN (SELECT COUNT(*) FROM cisadm.d1_usage_excp_type_l) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'D1_USAGE_PERIOD_SQ' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'D1_USAGE_PERIOD_SQ') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'D1_USAGE_PERIOD_SQ') THEN (SELECT COUNT(*) FROM cisadm.d1_usage_period_sq) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'D1_USAGE_RPT_CURR' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'D1_USAGE_RPT_CURR') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'D1_USAGE_RPT_CURR') THEN (SELECT COUNT(*) FROM cisadm.d1_usage_rpt_curr) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'D1_USAGE_SCALAR_DTL' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'D1_USAGE_SCALAR_DTL') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'D1_USAGE_SCALAR_DTL') THEN (SELECT COUNT(*) FROM cisadm.d1_usage_scalar_dtl) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'D1_USAGE_SCALAR_DTL_RPT_CURR' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'D1_USAGE_SCALAR_DTL_RPT_CURR') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'D1_USAGE_SCALAR_DTL_RPT_CURR') THEN (SELECT COUNT(*) FROM cisadm.d1_usage_scalar_dtl_rpt_curr) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'D1_USG_GRP_L' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'D1_USG_GRP_L') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'D1_USG_GRP_L') THEN (SELECT COUNT(*) FROM cisadm.d1_usg_grp_l) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'D1_USG_RULE_L' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'D1_USG_RULE_L') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'D1_USG_RULE_L') THEN (SELECT COUNT(*) FROM cisadm.d1_usg_rule_l) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'D1_US_CONTACT' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'D1_US_CONTACT') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'D1_US_CONTACT') THEN (SELECT COUNT(*) FROM cisadm.d1_us_contact) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'D1_US_SP' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'D1_US_SP') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'D1_US_SP') THEN (SELECT COUNT(*) FROM cisadm.d1_us_sp) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'D1_VEE_EXCP' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'D1_VEE_EXCP') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'D1_VEE_EXCP') THEN (SELECT COUNT(*) FROM cisadm.d1_vee_excp) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'D1_VEE_GRP_L' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'D1_VEE_GRP_L') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'D1_VEE_GRP_L') THEN (SELECT COUNT(*) FROM cisadm.d1_vee_grp_l) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'D1_VEE_RULE_L' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'D1_VEE_RULE_L') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'D1_VEE_RULE_L') THEN (SELECT COUNT(*) FROM cisadm.d1_vee_rule_l) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'F1_BUS_OBJ_L' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'F1_BUS_OBJ_L') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'F1_BUS_OBJ_L') THEN (SELECT COUNT(*) FROM cisadm.f1_bus_obj_l) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'F1_BUS_OBJ_STATUS_L' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'F1_BUS_OBJ_STATUS_L') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'F1_BUS_OBJ_STATUS_L') THEN (SELECT COUNT(*) FROM cisadm.f1_bus_obj_status_l) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'F1_BUS_OBJ_STATUS_RSN_L' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'F1_BUS_OBJ_STATUS_RSN_L') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'F1_BUS_OBJ_STATUS_RSN_L') THEN (SELECT COUNT(*) FROM cisadm.f1_bus_obj_status_rsn_l) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'F1_EXT_LOOKUP_VAL_L' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'F1_EXT_LOOKUP_VAL_L') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'F1_EXT_LOOKUP_VAL_L') THEN (SELECT COUNT(*) FROM cisadm.f1_ext_lookup_val_l) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'F1_TSK' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'F1_TSK') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'F1_TSK') THEN (SELECT COUNT(*) FROM cisadm.f1_tsk) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'F1_TSK_LOG' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'F1_TSK_LOG') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'F1_TSK_LOG') THEN (SELECT COUNT(*) FROM cisadm.f1_tsk_log) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'FT_GL_DISTRIBUTION_RPT_CURR' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'FT_GL_DISTRIBUTION_RPT_CURR') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'FT_GL_DISTRIBUTION_RPT_CURR') THEN (SELECT COUNT(*) FROM cisadm.ft_gl_distribution_rpt_curr) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'FT_RPT_CURR' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'FT_RPT_CURR') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'FT_RPT_CURR') THEN (SELECT COUNT(*) FROM cisadm.ft_rpt_curr) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'SC_USER' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'SC_USER') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'SC_USER') THEN (SELECT COUNT(*) FROM cisadm.sc_user) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'W1_APPROVAL_PROF_L' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'W1_APPROVAL_PROF_L') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'W1_APPROVAL_PROF_L') THEN (SELECT COUNT(*) FROM cisadm.w1_approval_prof_l) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'W1_ASSET' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'W1_ASSET') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'W1_ASSET') THEN (SELECT COUNT(*) FROM cisadm.w1_asset) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'W1_ASSET_CHAR' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'W1_ASSET_CHAR') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'W1_ASSET_CHAR') THEN (SELECT COUNT(*) FROM cisadm.w1_asset_char) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'W1_ASSET_IDENTIFIER' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'W1_ASSET_IDENTIFIER') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'W1_ASSET_IDENTIFIER') THEN (SELECT COUNT(*) FROM cisadm.w1_asset_identifier) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'W1_ASSET_NODE' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'W1_ASSET_NODE') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'W1_ASSET_NODE') THEN (SELECT COUNT(*) FROM cisadm.w1_asset_node) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'W1_ASSET_TYPE_L' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'W1_ASSET_TYPE_L') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'W1_ASSET_TYPE_L') THEN (SELECT COUNT(*) FROM cisadm.w1_asset_type_l) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'W1_BOM_PART' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'W1_BOM_PART') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'W1_BOM_PART') THEN (SELECT COUNT(*) FROM cisadm.w1_bom_part) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'W1_BUYER_L' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'W1_BUYER_L') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'W1_BUYER_L') THEN (SELECT COUNT(*) FROM cisadm.w1_buyer_l) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'W1_COST_CENTER_L' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'W1_COST_CENTER_L') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'W1_COST_CENTER_L') THEN (SELECT COUNT(*) FROM cisadm.w1_cost_center_l) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'W1_EXPENSE_CD_L' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'W1_EXPENSE_CD_L') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'W1_EXPENSE_CD_L') THEN (SELECT COUNT(*) FROM cisadm.w1_expense_cd_l) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'W1_MAINTMGR_L' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'W1_MAINTMGR_L') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'W1_MAINTMGR_L') THEN (SELECT COUNT(*) FROM cisadm.w1_maintmgr_l) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'W1_NODE' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'W1_NODE') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'W1_NODE') THEN (SELECT COUNT(*) FROM cisadm.w1_node) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'W1_NODE_TYPE_L' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'W1_NODE_TYPE_L') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'W1_NODE_TYPE_L') THEN (SELECT COUNT(*) FROM cisadm.w1_node_type_l) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'W1_PLANNER_L' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'W1_PLANNER_L') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'W1_PLANNER_L') THEN (SELECT COUNT(*) FROM cisadm.w1_planner_l) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'W1_PROPERTY_UNIT_L' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'W1_PROPERTY_UNIT_L') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'W1_PROPERTY_UNIT_L') THEN (SELECT COUNT(*) FROM cisadm.w1_property_unit_l) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'W1_SERVICE_AREA_L' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'W1_SERVICE_AREA_L') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'W1_SERVICE_AREA_L') THEN (SELECT COUNT(*) FROM cisadm.w1_service_area_l) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'W1_SPECIFICATION_L' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'W1_SPECIFICATION_L') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'W1_SPECIFICATION_L') THEN (SELECT COUNT(*) FROM cisadm.w1_specification_l) ELSE NULL END AS row_count FROM dual
UNION ALL
SELECT 'W1_VENDOR_LOC' AS table_name, (SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'W1_VENDOR_LOC') AS table_exists, CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = 'W1_VENDOR_LOC') THEN (SELECT COUNT(*) FROM cisadm.w1_vendor_loc) ELSE NULL END AS row_count FROM dual;
