-- RUN IN TEST. INCREASE SAMPLE LIMITS ONLY WITH DBA APPROVAL.
-- PURPOSE:
--   Non-destructive Oracle diagnostics to discover which join path links
--   CISADM.D1 usage header/detail to billing service agreements (CI_SA).
-- SAFETY:
--   SELECT / EXPLAIN PLAN ONLY. NO DDL/DML.
-- BINDS:
--   :P_START_DATE and :P_END_DATE are optional VARCHAR2 binds in YYYY-MM-DD format.
--   If not provided, defaults are used (2000-01-01 to 2099-12-31).
-- =====================================================================

-- SQL*PLUS / SQLCL BIND SAFETY (PREVENTS SP2-0552)
-- If you already set binds in SQL Developer, these defaults are harmless.
VAR P_START_DATE VARCHAR2(10);
VAR P_END_DATE VARCHAR2(10);
BEGIN
    IF :P_START_DATE IS NULL THEN
        :P_START_DATE := '2000-01-01';
    END IF;
    IF :P_END_DATE IS NULL THEN
        :P_END_DATE := '2099-12-31';
    END IF;
END;
/

-- =====================================================================
-- 0) TABLE/COLUMN PRESENCE CHECKS
-- WHY: Confirm expected objects exist and inspect uncertain join columns first.
-- =====================================================================
SELECT
    T.OWNER,
    T.TABLE_NAME
FROM ALL_TABLES T
WHERE T.OWNER = 'CISADM'
  AND T.TABLE_NAME IN (
      'D1_USAGE_SCALAR_DTL',
      'D1_USAGE',
      'D1_SP',
      'CI_SA_SP',
      'CI_SP',
      'CI_SA',
      'CI_ACCT',
      'CI_BSEG',
      'CI_BILL'
  )
ORDER BY T.TABLE_NAME;

SELECT
    C.OWNER,
    C.TABLE_NAME,
    C.COLUMN_NAME,
    C.DATA_TYPE
FROM ALL_TAB_COLUMNS C
WHERE C.OWNER = 'CISADM'
  AND C.TABLE_NAME IN ('D1_USAGE', 'D1_USAGE_SCALAR_DTL', 'D1_SP', 'CI_ACCT')
ORDER BY C.TABLE_NAME, C.COLUMN_ID;

-- Direct SA pointer candidate columns in D1_USAGE (Requirement E helper).
SELECT
    C.COLUMN_NAME,
    C.DATA_TYPE
FROM ALL_TAB_COLUMNS C
WHERE C.OWNER = 'CISADM'
  AND C.TABLE_NAME = 'D1_USAGE'
  AND (
      (C.COLUMN_NAME = 'SA_ID' OR C.COLUMN_NAME LIKE 'SA\_%' ESCAPE '\' OR C.COLUMN_NAME LIKE '%\_SA\_%' ESCAPE '\')
      OR C.COLUMN_NAME LIKE '%SERVICE%AGREEMENT%'
      OR C.COLUMN_NAME LIKE '%USG_EXT_ID%'
  )
ORDER BY C.COLUMN_NAME;

-- =====================================================================
-- 1) SAFE SAMPLES (SMALL OUTPUT)
-- WHY: Verify data shape and values before running joins.
-- =====================================================================
SELECT *
FROM (
    SELECT
        U.D1_USAGE_ID,
        U.USG_EXT_ID,
        U.US_ID,
        U.START_DTTM,
        U.END_DTTM,
        U.USG_GRP_CD
    FROM CISADM.D1_USAGE U
    WHERE U.START_DTTM >= NVL(TO_DATE(:P_START_DATE, 'YYYY-MM-DD'), DATE '2026-01-01')
      AND U.START_DTTM <  NVL(TO_DATE(:P_END_DATE,   'YYYY-MM-DD'), DATE '2026-01-31') + 1
    ORDER BY U.START_DTTM DESC
)
WHERE ROWNUM <= 50;

SELECT *
FROM (
    SELECT
        D.D1_USAGE_ID,
        D.D1_SP_ID,
        D.SEQ_NUM,
        D.START_DTTM,
        D.END_DTTM,
        D.QUANTITY
    FROM CISADM.D1_USAGE_SCALAR_DTL D
    WHERE D.START_DTTM >= NVL(TO_DATE(:P_START_DATE, 'YYYY-MM-DD'), DATE '2026-01-01')
      AND D.START_DTTM <  NVL(TO_DATE(:P_END_DATE,   'YYYY-MM-DD'), DATE '2026-01-31') + 1
    ORDER BY D.START_DTTM DESC
)
WHERE ROWNUM <= 50;

-- Date profile helper (run this first if all mapping counts are zero).
-- Use results to set :P_START_DATE / :P_END_DATE to a window that actually has data.
SELECT 'D1_USAGE' AS SOURCE_TABLE, MIN(U.START_DTTM) AS MIN_DT, MAX(U.START_DTTM) AS MAX_DT, COUNT(*) AS ROW_COUNT
FROM CISADM.D1_USAGE U
UNION ALL
SELECT 'D1_USAGE_SCALAR_DTL' AS SOURCE_TABLE, MIN(D.START_DTTM) AS MIN_DT, MAX(D.START_DTTM) AS MAX_DT, COUNT(*) AS ROW_COUNT
FROM CISADM.D1_USAGE_SCALAR_DTL D
UNION ALL
SELECT 'CI_BILL' AS SOURCE_TABLE, MIN(NVL(B.BILL_DT, B.CRE_DTTM)) AS MIN_DT, MAX(NVL(B.BILL_DT, B.CRE_DTTM)) AS MAX_DT, COUNT(*) AS ROW_COUNT
FROM CISADM.CI_BILL B;

-- =====================================================================
-- 2) MAPPING DIAGNOSTICS (A-E)
-- WHY: Quantify which bridge key/path actually maps D1 usage to billing entities.
-- =====================================================================

-- A) D1_USAGE.USG_EXT_ID -> CI_SA.SA_ID
SELECT
    COUNT(*) AS MATCH_COUNT_A_USG_EXT_TO_SA_ID
FROM CISADM.D1_USAGE U
JOIN CISADM.CI_SA S
    ON TO_CHAR(U.USG_EXT_ID) = TO_CHAR(S.SA_ID)
WHERE U.USG_EXT_ID IS NOT NULL
  AND U.START_DTTM >= NVL(TO_DATE(:P_START_DATE, 'YYYY-MM-DD'), DATE '2026-01-01')
  AND U.START_DTTM <  NVL(TO_DATE(:P_END_DATE,   'YYYY-MM-DD'), DATE '2026-01-31') + 1;

-- B) D1_USAGE.USG_EXT_ID -> CI_ACCT.ACCT_ID (primary robust path)
SELECT
    COUNT(*) AS MATCH_COUNT_B_USG_EXT_TO_ACCT_ID
FROM CISADM.D1_USAGE U
JOIN CISADM.CI_ACCT A
    ON TO_CHAR(U.USG_EXT_ID) = TO_CHAR(A.ACCT_ID)
WHERE U.USG_EXT_ID IS NOT NULL
  AND U.START_DTTM >= NVL(TO_DATE(:P_START_DATE, 'YYYY-MM-DD'), DATE '2026-01-01')
  AND U.START_DTTM <  NVL(TO_DATE(:P_END_DATE,   'YYYY-MM-DD'), DATE '2026-01-31') + 1;

-- B-OPTIONAL) ONLY RUN IF CISADM.CI_ACCT.ACCT_NO EXISTS IN YOUR ENVIRONMENT.
-- SELECT
--     COUNT(*) AS MATCH_COUNT_B_USG_EXT_TO_ACCT_NO
-- FROM CISADM.D1_USAGE U
-- JOIN CISADM.CI_ACCT A
--     ON TO_CHAR(U.USG_EXT_ID) = TO_CHAR(A.ACCT_NO)
-- WHERE U.USG_EXT_ID IS NOT NULL
--   AND U.START_DTTM >= NVL(TO_DATE(:P_START_DATE, 'YYYY-MM-DD'), DATE '2026-01-01')
--   AND U.START_DTTM <  NVL(TO_DATE(:P_END_DATE,   'YYYY-MM-DD'), DATE '2026-01-31') + 1;

-- C) D1_USAGE_SCALAR_DTL.D1_SP_ID -> CI_SA_SP.SP_ID
SELECT
    COUNT(*) AS MATCH_COUNT_C_DTL_SP_TO_SA_SP
FROM CISADM.D1_USAGE_SCALAR_DTL D
JOIN CISADM.CI_SA_SP SAS
    ON TO_CHAR(D.D1_SP_ID) = TO_CHAR(SAS.SP_ID)
WHERE D.D1_SP_ID IS NOT NULL
  AND D.START_DTTM >= NVL(TO_DATE(:P_START_DATE, 'YYYY-MM-DD'), DATE '2026-01-01')
  AND D.START_DTTM <  NVL(TO_DATE(:P_END_DATE,   'YYYY-MM-DD'), DATE '2026-01-31') + 1;

-- D) D1_USAGE_SCALAR_DTL.D1_SP_ID -> D1_SP -> CI_SP -> CI_SA_SP -> SA_ID
-- NOTE: If CISADM.D1_SP is absent or has different key names, inspect section 0 first and adjust join columns.
SELECT
    COUNT(*) AS MATCH_COUNT_D_DTL_TO_D1SP_TO_CISP_TO_SASP_TO_SA
FROM CISADM.D1_USAGE_SCALAR_DTL D
JOIN CISADM.D1_SP DSP
    ON TO_CHAR(D.D1_SP_ID) = TO_CHAR(DSP.D1_SP_ID)
JOIN CISADM.CI_SP CSP
    ON TO_CHAR(CSP.SP_ID) = TO_CHAR(DSP.D1_SP_ID)
JOIN CISADM.CI_SA_SP SAS
    ON TO_CHAR(SAS.SP_ID) = TO_CHAR(CSP.SP_ID)
JOIN CISADM.CI_SA S
    ON TO_CHAR(S.SA_ID) = TO_CHAR(SAS.SA_ID)
WHERE D.D1_SP_ID IS NOT NULL
  AND D.START_DTTM >= NVL(TO_DATE(:P_START_DATE, 'YYYY-MM-DD'), DATE '2026-01-01')
  AND D.START_DTTM <  NVL(TO_DATE(:P_END_DATE,   'YYYY-MM-DD'), DATE '2026-01-31') + 1;

-- E) D1_USAGE direct SA pointer-like column count and names
SELECT
    COUNT(*) AS MATCH_COUNT_E_D1_USAGE_POINTER_COLUMNS
FROM ALL_TAB_COLUMNS C
WHERE C.OWNER = 'CISADM'
  AND C.TABLE_NAME = 'D1_USAGE'
  AND (
      (C.COLUMN_NAME = 'SA_ID' OR C.COLUMN_NAME LIKE 'SA\_%' ESCAPE '\' OR C.COLUMN_NAME LIKE '%\_SA\_%' ESCAPE '\')
      OR C.COLUMN_NAME LIKE '%SERVICE%AGREEMENT%'
  );

SELECT
    C.COLUMN_NAME,
    C.DATA_TYPE
FROM ALL_TAB_COLUMNS C
WHERE C.OWNER = 'CISADM'
  AND C.TABLE_NAME = 'D1_USAGE'
  AND (
      (C.COLUMN_NAME = 'SA_ID' OR C.COLUMN_NAME LIKE 'SA\_%' ESCAPE '\' OR C.COLUMN_NAME LIKE '%\_SA\_%' ESCAPE '\')
      OR C.COLUMN_NAME LIKE '%SERVICE%AGREEMENT%'
  )
ORDER BY C.COLUMN_NAME;

-- F) Bill cycle code/description coverage in billing tables
-- NOTE: This confirms whether final report can show cycle code + human description.
SELECT
    COUNT(*) AS TOTAL_BILLS_IN_WINDOW,
    COUNT(CASE WHEN TRIM(B.BILL_CYC_CD) IS NOT NULL THEN 1 END) AS BILLS_WITH_BILL_CYC_CD
FROM CISADM.CI_BILL B
WHERE NVL(B.BILL_DT, B.CRE_DTTM) >= NVL(TO_DATE(:P_START_DATE, 'YYYY-MM-DD'), DATE '2026-01-01')
  AND NVL(B.BILL_DT, B.CRE_DTTM) <  NVL(TO_DATE(:P_END_DATE,   'YYYY-MM-DD'), DATE '2026-01-31') + 1;

SELECT *
FROM (
    SELECT
        B.BILL_ID,
        B.ACCT_ID,
        TRIM(B.BILL_CYC_CD) AS BILL_CYCLE_CODE,
        L.DESCR AS BILL_CYCLE_DESCRIPTION,
        NVL(B.BILL_DT, B.CRE_DTTM) AS BILL_EVENT_DTTM
    FROM CISADM.CI_BILL B
    LEFT JOIN CISADM.CI_BILL_CYC_L L
        ON TRIM(L.BILL_CYC_CD) = TRIM(B.BILL_CYC_CD)
       AND L.LANGUAGE_CD IN ('ENG', 'EN')
    WHERE NVL(B.BILL_DT, B.CRE_DTTM) >= NVL(TO_DATE(:P_START_DATE, 'YYYY-MM-DD'), DATE '2026-01-01')
      AND NVL(B.BILL_DT, B.CRE_DTTM) <  NVL(TO_DATE(:P_END_DATE,   'YYYY-MM-DD'), DATE '2026-01-31') + 1
    ORDER BY NVL(B.BILL_DT, B.CRE_DTTM) DESC
)
WHERE ROWNUM <= 50;

-- G) D1_USAGE.D1_USAGE_ID -> C1_USAGE.USAGE_ID -> CI_SA.SA_ID
SELECT
    COUNT(*) AS MATCH_COUNT_G_D1_USAGE_TO_C1_USAGE_TO_SA
FROM CISADM.D1_USAGE U
JOIN CISADM.C1_USAGE CU
    ON TO_CHAR(CU.USAGE_ID) = TO_CHAR(U.D1_USAGE_ID)
JOIN CISADM.CI_SA S
    ON TO_CHAR(S.SA_ID) = TO_CHAR(CU.SA_ID)
WHERE U.D1_USAGE_ID IS NOT NULL
  AND (
      :P_START_DATE IS NULL OR U.START_DTTM >= TO_DATE(:P_START_DATE, 'YYYY-MM-DD')
  )
  AND (
      :P_END_DATE IS NULL OR U.START_DTTM < TO_DATE(:P_END_DATE, 'YYYY-MM-DD') + 1
  );

-- H) D1_USAGE_SCALAR_DTL.D1_SP_ID -> D1_SP_USG_SNAP_DL.D1_SP_ID -> CIS_EXT_SA_ID -> CI_SA.SA_ID
SELECT
    COUNT(*) AS MATCH_COUNT_H_DTL_TO_SNAP_TO_SA
FROM CISADM.D1_USAGE_SCALAR_DTL D
JOIN CISADM.D1_SP_USG_SNAP_DL SN
    ON TO_CHAR(SN.D1_SP_ID) = TO_CHAR(D.D1_SP_ID)
JOIN CISADM.CI_SA S
    ON TO_CHAR(S.SA_ID) = TO_CHAR(SN.CIS_EXT_SA_ID)
WHERE D.D1_SP_ID IS NOT NULL
  AND (
      :P_START_DATE IS NULL OR D.START_DTTM >= TO_DATE(:P_START_DATE, 'YYYY-MM-DD')
  )
  AND (
      :P_END_DATE IS NULL OR D.START_DTTM < TO_DATE(:P_END_DATE, 'YYYY-MM-DD') + 1
  );

-- I) D1_USAGE.USG_EXT_ID -> C1_BI_BILLED_USAGE_VW.SA_ID
SELECT
    COUNT(*) AS MATCH_COUNT_I_USG_EXT_TO_BILLED_USAGE_VW_SA
FROM CISADM.D1_USAGE U
JOIN CISADM.C1_BI_BILLED_USAGE_VW V
    ON TO_CHAR(V.SA_ID) = TO_CHAR(U.USG_EXT_ID)
WHERE U.USG_EXT_ID IS NOT NULL
  AND (
      :P_START_DATE IS NULL OR U.START_DTTM >= TO_DATE(:P_START_DATE, 'YYYY-MM-DD')
  )
  AND (
      :P_END_DATE IS NULL OR U.START_DTTM < TO_DATE(:P_END_DATE, 'YYYY-MM-DD') + 1
  );

-- =====================================================================
-- 3) COMBINED SUMMARY (CSV-FRIENDLY)
-- WHY: One view of A/B/C/D/E match counts and top candidate path.
-- OUTPUT COLUMNS: PATH, MATCH_COUNT, NOTES
-- =====================================================================
WITH
PARAMS AS (
    SELECT
        NVL(TO_DATE(:P_START_DATE, 'YYYY-MM-DD'), DATE '2026-01-01') AS START_DT,
        NVL(TO_DATE(:P_END_DATE,   'YYYY-MM-DD'), DATE '2026-01-31') AS END_DT
    FROM DUAL
),
A_CNT AS (
    SELECT COUNT(*) AS MATCH_COUNT
    FROM CISADM.D1_USAGE U
    JOIN CISADM.CI_SA S
        ON TO_CHAR(U.USG_EXT_ID) = TO_CHAR(S.SA_ID)
    CROSS JOIN PARAMS P
    WHERE U.USG_EXT_ID IS NOT NULL
      AND U.START_DTTM >= P.START_DT
      AND U.START_DTTM <  P.END_DT + 1
),
B_CNT AS (
    SELECT COUNT(*) AS MATCH_COUNT
    FROM CISADM.D1_USAGE U
    JOIN CISADM.CI_ACCT A
        ON TO_CHAR(U.USG_EXT_ID) = TO_CHAR(A.ACCT_ID)
    CROSS JOIN PARAMS P
    WHERE U.USG_EXT_ID IS NOT NULL
      AND U.START_DTTM >= P.START_DT
      AND U.START_DTTM <  P.END_DT + 1
),
C_CNT AS (
    SELECT COUNT(*) AS MATCH_COUNT
    FROM CISADM.D1_USAGE_SCALAR_DTL D
    JOIN CISADM.CI_SA_SP SAS
        ON TO_CHAR(D.D1_SP_ID) = TO_CHAR(SAS.SP_ID)
    CROSS JOIN PARAMS P
    WHERE D.D1_SP_ID IS NOT NULL
      AND D.START_DTTM >= P.START_DT
      AND D.START_DTTM <  P.END_DT + 1
),
D_CNT AS (
    SELECT COUNT(*) AS MATCH_COUNT
    FROM CISADM.D1_USAGE_SCALAR_DTL D
    JOIN CISADM.D1_SP DSP
        ON TO_CHAR(D.D1_SP_ID) = TO_CHAR(DSP.D1_SP_ID)
JOIN CISADM.CI_SP CSP
    ON TO_CHAR(CSP.SP_ID) = TO_CHAR(DSP.D1_SP_ID)
    JOIN CISADM.CI_SA_SP SAS
        ON TO_CHAR(SAS.SP_ID) = TO_CHAR(CSP.SP_ID)
    JOIN CISADM.CI_SA S
        ON TO_CHAR(S.SA_ID) = TO_CHAR(SAS.SA_ID)
    CROSS JOIN PARAMS P
    WHERE D.D1_SP_ID IS NOT NULL
      AND D.START_DTTM >= P.START_DT
      AND D.START_DTTM <  P.END_DT + 1
),
E_CNT AS (
    SELECT COUNT(*) AS MATCH_COUNT
    FROM ALL_TAB_COLUMNS C
WHERE C.OWNER = 'CISADM'
  AND C.TABLE_NAME = 'D1_USAGE'
  AND (
          (C.COLUMN_NAME = 'SA_ID' OR C.COLUMN_NAME LIKE 'SA\_%' ESCAPE '\' OR C.COLUMN_NAME LIKE '%\_SA\_%' ESCAPE '\')
          OR C.COLUMN_NAME LIKE '%SERVICE%AGREEMENT%'
      )
),
F_CNT AS (
    SELECT COUNT(*) AS MATCH_COUNT
    FROM CISADM.CI_BILL B
    LEFT JOIN CISADM.CI_BILL_CYC_L L
        ON TRIM(L.BILL_CYC_CD) = TRIM(B.BILL_CYC_CD)
       AND L.LANGUAGE_CD IN ('ENG', 'EN')
    CROSS JOIN PARAMS P
    WHERE NVL(B.BILL_DT, B.CRE_DTTM) >= P.START_DT
      AND NVL(B.BILL_DT, B.CRE_DTTM) <  P.END_DT + 1
      AND TRIM(B.BILL_CYC_CD) IS NOT NULL
      AND TRIM(L.DESCR) IS NOT NULL
),
G_CNT AS (
    SELECT COUNT(*) AS MATCH_COUNT
    FROM CISADM.D1_USAGE U
    JOIN CISADM.C1_USAGE CU
        ON TO_CHAR(CU.USAGE_ID) = TO_CHAR(U.D1_USAGE_ID)
    JOIN CISADM.CI_SA S
        ON TO_CHAR(S.SA_ID) = TO_CHAR(CU.SA_ID)
    CROSS JOIN PARAMS P
    WHERE U.D1_USAGE_ID IS NOT NULL
      AND U.START_DTTM >= P.START_DT
      AND U.START_DTTM <  P.END_DT + 1
),
H_CNT AS (
    SELECT COUNT(*) AS MATCH_COUNT
    FROM CISADM.D1_USAGE_SCALAR_DTL D
    JOIN CISADM.D1_SP_USG_SNAP_DL SN
        ON TO_CHAR(SN.D1_SP_ID) = TO_CHAR(D.D1_SP_ID)
    JOIN CISADM.CI_SA S
        ON TO_CHAR(S.SA_ID) = TO_CHAR(SN.CIS_EXT_SA_ID)
    CROSS JOIN PARAMS P
    WHERE D.D1_SP_ID IS NOT NULL
      AND D.START_DTTM >= P.START_DT
      AND D.START_DTTM <  P.END_DT + 1
),
I_CNT AS (
    SELECT COUNT(*) AS MATCH_COUNT
    FROM CISADM.D1_USAGE U
    JOIN CISADM.C1_BI_BILLED_USAGE_VW V
        ON TO_CHAR(V.SA_ID) = TO_CHAR(U.USG_EXT_ID)
    CROSS JOIN PARAMS P
    WHERE U.USG_EXT_ID IS NOT NULL
      AND U.START_DTTM >= P.START_DT
      AND U.START_DTTM <  P.END_DT + 1
),
PATH_COUNTS AS (
    SELECT 'A_USG_EXT_ID_TO_SA_ID' AS PATH, (SELECT MATCH_COUNT FROM A_CNT) AS MATCH_COUNT,
           'D1_USAGE.USG_EXT_ID = CI_SA.SA_ID' AS NOTES
    FROM DUAL
    UNION ALL
    SELECT 'B_USG_EXT_ID_TO_ACCT_ID' AS PATH, (SELECT MATCH_COUNT FROM B_CNT) AS MATCH_COUNT,
           'D1_USAGE.USG_EXT_ID = CI_ACCT.ACCT_ID (ACCT_NO CHECK IS OPTIONAL BLOCK)' AS NOTES
    FROM DUAL
    UNION ALL
    SELECT 'C_DTL_D1_SP_ID_TO_CI_SA_SP' AS PATH, (SELECT MATCH_COUNT FROM C_CNT) AS MATCH_COUNT,
           'D1_USAGE_SCALAR_DTL.D1_SP_ID = CI_SA_SP.SP_ID' AS NOTES
    FROM DUAL
    UNION ALL
    SELECT 'D_DTL_VIA_D1_SP_CI_SP_CI_SA_SP' AS PATH, (SELECT MATCH_COUNT FROM D_CNT) AS MATCH_COUNT,
           'D1_USAGE_SCALAR_DTL -> D1_SP -> CI_SP -> CI_SA_SP -> CI_SA' AS NOTES
    FROM DUAL
    UNION ALL
    SELECT 'E_D1_USAGE_DIRECT_SA_POINTER_COLS' AS PATH, (SELECT MATCH_COUNT FROM E_CNT) AS MATCH_COUNT,
           'COUNT OF SA-POINTER-LIKE COLUMNS IN D1_USAGE METADATA' AS NOTES
    FROM DUAL
    UNION ALL
    SELECT 'F_BILL_CYCLE_CODE_WITH_DESCRIPTION' AS PATH, (SELECT MATCH_COUNT FROM F_CNT) AS MATCH_COUNT,
           'CI_BILL.BILL_CYC_CD SUCCESSFULLY MAPS TO CI_BILL_CYC_L.DESCR' AS NOTES
    FROM DUAL
    UNION ALL
    SELECT 'G_D1_USAGE_TO_C1_USAGE_TO_SA' AS PATH, (SELECT MATCH_COUNT FROM G_CNT) AS MATCH_COUNT,
           'D1_USAGE.D1_USAGE_ID -> C1_USAGE.USAGE_ID -> C1_USAGE.SA_ID -> CI_SA.SA_ID' AS NOTES
    FROM DUAL
    UNION ALL
    SELECT 'H_DTL_TO_SP_USG_SNAP_TO_SA' AS PATH, (SELECT MATCH_COUNT FROM H_CNT) AS MATCH_COUNT,
           'D1_USAGE_SCALAR_DTL.D1_SP_ID -> D1_SP_USG_SNAP_DL.CIS_EXT_SA_ID -> CI_SA.SA_ID' AS NOTES
    FROM DUAL
    UNION ALL
    SELECT 'I_USG_EXT_TO_BILLED_USAGE_VW_SA' AS PATH, (SELECT MATCH_COUNT FROM I_CNT) AS MATCH_COUNT,
           'D1_USAGE.USG_EXT_ID -> C1_BI_BILLED_USAGE_VW.SA_ID' AS NOTES
    FROM DUAL
)
SELECT
    PC.PATH,
    PC.MATCH_COUNT,
    CASE
        WHEN PC.MATCH_COUNT = MAX(PC.MATCH_COUNT) OVER () AND PC.MATCH_COUNT > 0
            THEN PC.NOTES || ' | TOP_MATCH_PATH'
        WHEN PC.MATCH_COUNT = 0
            THEN PC.NOTES || ' | NO_MATCH_IN_WINDOW'
        ELSE PC.NOTES
    END AS NOTES
FROM PATH_COUNTS PC
ORDER BY PC.MATCH_COUNT DESC, PC.PATH;

-- =====================================================================
-- 4) EXPLAIN PLAN FOR COMBINED SUMMARY
-- WHY: Let DBA quickly inspect plan/cost for the heavy consolidated query.
-- =====================================================================
EXPLAIN PLAN FOR
WITH
PARAMS AS (
    SELECT
        NVL(TO_DATE(:P_START_DATE, 'YYYY-MM-DD'), DATE '2026-01-01') AS START_DT,
        NVL(TO_DATE(:P_END_DATE,   'YYYY-MM-DD'), DATE '2026-01-31') AS END_DT
    FROM DUAL
),
A_CNT AS (
    SELECT COUNT(*) AS MATCH_COUNT
    FROM CISADM.D1_USAGE U
    JOIN CISADM.CI_SA S
        ON TO_CHAR(U.USG_EXT_ID) = TO_CHAR(S.SA_ID)
    CROSS JOIN PARAMS P
    WHERE U.USG_EXT_ID IS NOT NULL
      AND U.START_DTTM >= P.START_DT
      AND U.START_DTTM <  P.END_DT + 1
),
B_CNT AS (
    SELECT COUNT(*) AS MATCH_COUNT
    FROM CISADM.D1_USAGE U
    JOIN CISADM.CI_ACCT A
        ON TO_CHAR(U.USG_EXT_ID) = TO_CHAR(A.ACCT_ID)
    CROSS JOIN PARAMS P
    WHERE U.USG_EXT_ID IS NOT NULL
      AND U.START_DTTM >= P.START_DT
      AND U.START_DTTM <  P.END_DT + 1
),
C_CNT AS (
    SELECT COUNT(*) AS MATCH_COUNT
    FROM CISADM.D1_USAGE_SCALAR_DTL D
    JOIN CISADM.CI_SA_SP SAS
        ON TO_CHAR(D.D1_SP_ID) = TO_CHAR(SAS.SP_ID)
    CROSS JOIN PARAMS P
    WHERE D.D1_SP_ID IS NOT NULL
      AND D.START_DTTM >= P.START_DT
      AND D.START_DTTM <  P.END_DT + 1
),
D_CNT AS (
    SELECT COUNT(*) AS MATCH_COUNT
    FROM CISADM.D1_USAGE_SCALAR_DTL D
    JOIN CISADM.D1_SP DSP
        ON TO_CHAR(D.D1_SP_ID) = TO_CHAR(DSP.D1_SP_ID)
JOIN CISADM.CI_SP CSP
        ON TO_CHAR(CSP.SP_ID) = TO_CHAR(DSP.D1_SP_ID)
    JOIN CISADM.CI_SA_SP SAS
        ON TO_CHAR(SAS.SP_ID) = TO_CHAR(CSP.SP_ID)
    JOIN CISADM.CI_SA S
        ON TO_CHAR(S.SA_ID) = TO_CHAR(SAS.SA_ID)
    CROSS JOIN PARAMS P
    WHERE D.D1_SP_ID IS NOT NULL
      AND D.START_DTTM >= P.START_DT
      AND D.START_DTTM <  P.END_DT + 1
),
E_CNT AS (
    SELECT COUNT(*) AS MATCH_COUNT
    FROM ALL_TAB_COLUMNS C
WHERE C.OWNER = 'CISADM'
  AND C.TABLE_NAME = 'D1_USAGE'
  AND (
          (C.COLUMN_NAME = 'SA_ID' OR C.COLUMN_NAME LIKE 'SA\_%' ESCAPE '\' OR C.COLUMN_NAME LIKE '%\_SA\_%' ESCAPE '\')
          OR C.COLUMN_NAME LIKE '%SERVICE%AGREEMENT%'
      )
),
F_CNT AS (
    SELECT COUNT(*) AS MATCH_COUNT
    FROM CISADM.CI_BILL B
    LEFT JOIN CISADM.CI_BILL_CYC_L L
        ON TRIM(L.BILL_CYC_CD) = TRIM(B.BILL_CYC_CD)
       AND L.LANGUAGE_CD IN ('ENG', 'EN')
    CROSS JOIN PARAMS P
    WHERE NVL(B.BILL_DT, B.CRE_DTTM) >= P.START_DT
      AND NVL(B.BILL_DT, B.CRE_DTTM) <  P.END_DT + 1
      AND TRIM(B.BILL_CYC_CD) IS NOT NULL
      AND TRIM(L.DESCR) IS NOT NULL
),
G_CNT AS (
    SELECT COUNT(*) AS MATCH_COUNT
    FROM CISADM.D1_USAGE U
    JOIN CISADM.C1_USAGE CU
        ON TO_CHAR(CU.USAGE_ID) = TO_CHAR(U.D1_USAGE_ID)
    JOIN CISADM.CI_SA S
        ON TO_CHAR(S.SA_ID) = TO_CHAR(CU.SA_ID)
    CROSS JOIN PARAMS P
    WHERE U.D1_USAGE_ID IS NOT NULL
      AND U.START_DTTM >= P.START_DT
      AND U.START_DTTM <  P.END_DT + 1
),
H_CNT AS (
    SELECT COUNT(*) AS MATCH_COUNT
    FROM CISADM.D1_USAGE_SCALAR_DTL D
    JOIN CISADM.D1_SP_USG_SNAP_DL SN
        ON TO_CHAR(SN.D1_SP_ID) = TO_CHAR(D.D1_SP_ID)
    JOIN CISADM.CI_SA S
        ON TO_CHAR(S.SA_ID) = TO_CHAR(SN.CIS_EXT_SA_ID)
    CROSS JOIN PARAMS P
    WHERE D.D1_SP_ID IS NOT NULL
      AND D.START_DTTM >= P.START_DT
      AND D.START_DTTM <  P.END_DT + 1
),
I_CNT AS (
    SELECT COUNT(*) AS MATCH_COUNT
    FROM CISADM.D1_USAGE U
    JOIN CISADM.C1_BI_BILLED_USAGE_VW V
        ON TO_CHAR(V.SA_ID) = TO_CHAR(U.USG_EXT_ID)
    CROSS JOIN PARAMS P
    WHERE U.USG_EXT_ID IS NOT NULL
      AND U.START_DTTM >= P.START_DT
      AND U.START_DTTM <  P.END_DT + 1
),
PATH_COUNTS AS (
    SELECT 'A_USG_EXT_ID_TO_SA_ID' AS PATH, (SELECT MATCH_COUNT FROM A_CNT) AS MATCH_COUNT,
           'D1_USAGE.USG_EXT_ID = CI_SA.SA_ID' AS NOTES
    FROM DUAL
    UNION ALL
    SELECT 'B_USG_EXT_ID_TO_ACCT_ID' AS PATH, (SELECT MATCH_COUNT FROM B_CNT) AS MATCH_COUNT,
           'D1_USAGE.USG_EXT_ID = CI_ACCT.ACCT_ID (ACCT_NO CHECK IS OPTIONAL BLOCK)' AS NOTES
    FROM DUAL
    UNION ALL
    SELECT 'C_DTL_D1_SP_ID_TO_CI_SA_SP' AS PATH, (SELECT MATCH_COUNT FROM C_CNT) AS MATCH_COUNT,
           'D1_USAGE_SCALAR_DTL.D1_SP_ID = CI_SA_SP.SP_ID' AS NOTES
    FROM DUAL
    UNION ALL
    SELECT 'D_DTL_VIA_D1_SP_CI_SP_CI_SA_SP' AS PATH, (SELECT MATCH_COUNT FROM D_CNT) AS MATCH_COUNT,
           'D1_USAGE_SCALAR_DTL -> D1_SP -> CI_SP -> CI_SA_SP -> CI_SA' AS NOTES
    FROM DUAL
    UNION ALL
    SELECT 'E_D1_USAGE_DIRECT_SA_POINTER_COLS' AS PATH, (SELECT MATCH_COUNT FROM E_CNT) AS MATCH_COUNT,
           'COUNT OF SA-POINTER-LIKE COLUMNS IN D1_USAGE METADATA' AS NOTES
    FROM DUAL
    UNION ALL
    SELECT 'F_BILL_CYCLE_CODE_WITH_DESCRIPTION' AS PATH, (SELECT MATCH_COUNT FROM F_CNT) AS MATCH_COUNT,
           'CI_BILL.BILL_CYC_CD SUCCESSFULLY MAPS TO CI_BILL_CYC_L.DESCR' AS NOTES
    FROM DUAL
    UNION ALL
    SELECT 'G_D1_USAGE_TO_C1_USAGE_TO_SA' AS PATH, (SELECT MATCH_COUNT FROM G_CNT) AS MATCH_COUNT,
           'D1_USAGE.D1_USAGE_ID -> C1_USAGE.USAGE_ID -> C1_USAGE.SA_ID -> CI_SA.SA_ID' AS NOTES
    FROM DUAL
    UNION ALL
    SELECT 'H_DTL_TO_SP_USG_SNAP_TO_SA' AS PATH, (SELECT MATCH_COUNT FROM H_CNT) AS MATCH_COUNT,
           'D1_USAGE_SCALAR_DTL.D1_SP_ID -> D1_SP_USG_SNAP_DL.CIS_EXT_SA_ID -> CI_SA.SA_ID' AS NOTES
    FROM DUAL
    UNION ALL
    SELECT 'I_USG_EXT_TO_BILLED_USAGE_VW_SA' AS PATH, (SELECT MATCH_COUNT FROM I_CNT) AS MATCH_COUNT,
           'D1_USAGE.USG_EXT_ID -> C1_BI_BILLED_USAGE_VW.SA_ID' AS NOTES
    FROM DUAL
)
SELECT
    PC.PATH,
    PC.MATCH_COUNT,
    CASE
        WHEN PC.MATCH_COUNT = MAX(PC.MATCH_COUNT) OVER () AND PC.MATCH_COUNT > 0
            THEN PC.NOTES || ' | TOP_MATCH_PATH'
        WHEN PC.MATCH_COUNT = 0
            THEN PC.NOTES || ' | NO_MATCH_IN_WINDOW'
        ELSE PC.NOTES
    END AS NOTES
FROM PATH_COUNTS PC
ORDER BY PC.MATCH_COUNT DESC, PC.PATH;

SELECT PLAN_TABLE_OUTPUT
FROM TABLE(DBMS_XPLAN.DISPLAY(NULL, NULL, 'BASIC +PREDICATE +COST'));

-- FALLBACK EXPLAIN PLAN (use when ORA-01039 occurs on combined summary explain).
-- This avoids data dictionary view references and still explains the heavy join portion.
EXPLAIN PLAN FOR
SELECT COUNT(*) AS MATCH_COUNT_D_DTL_TO_D1SP_TO_CISP_TO_SASP_TO_SA
FROM CISADM.D1_USAGE_SCALAR_DTL D
JOIN CISADM.D1_SP DSP
    ON TO_CHAR(D.D1_SP_ID) = TO_CHAR(DSP.D1_SP_ID)
JOIN CISADM.CI_SP CSP
    ON TO_CHAR(CSP.SP_ID) = TO_CHAR(DSP.D1_SP_ID)
JOIN CISADM.CI_SA_SP SAS
    ON TO_CHAR(SAS.SP_ID) = TO_CHAR(CSP.SP_ID)
JOIN CISADM.CI_SA S
    ON TO_CHAR(S.SA_ID) = TO_CHAR(SAS.SA_ID)
WHERE D.D1_SP_ID IS NOT NULL
  AND D.START_DTTM >= NVL(TO_DATE(:P_START_DATE, 'YYYY-MM-DD'), DATE '2026-01-01')
  AND D.START_DTTM <  NVL(TO_DATE(:P_END_DATE,   'YYYY-MM-DD'), DATE '2026-01-31') + 1;

SELECT PLAN_TABLE_OUTPUT
FROM TABLE(DBMS_XPLAN.DISPLAY(NULL, NULL, 'BASIC +PREDICATE +COST'));

-- =====================================================================
-- 5) TESTED SAMPLE JOINS FOR POSITIVE PATHS (AUTO-GATED)
-- WHY: Return up to 50 illustrative rows for each path only when that path has matches.
-- =====================================================================

-- Path A sample: USG_EXT_ID -> SA_ID
WITH
PARAMS AS (
    SELECT
        NVL(TO_DATE(:P_START_DATE, 'YYYY-MM-DD'), DATE '2026-01-01') AS START_DT,
        NVL(TO_DATE(:P_END_DATE,   'YYYY-MM-DD'), DATE '2026-01-31') AS END_DT
    FROM DUAL
),
A_CNT AS (
    SELECT COUNT(*) AS MATCH_COUNT
    FROM CISADM.D1_USAGE U
    JOIN CISADM.CI_SA S
        ON TO_CHAR(U.USG_EXT_ID) = TO_CHAR(S.SA_ID)
    CROSS JOIN PARAMS P
    WHERE U.USG_EXT_ID IS NOT NULL
      AND U.START_DTTM >= P.START_DT
      AND U.START_DTTM <  P.END_DT + 1
)
SELECT *
FROM (
    SELECT
        U.D1_USAGE_ID,
        U.USG_EXT_ID,
        U.START_DTTM AS USAGE_START_DTTM,
        S.SA_ID,
        S.ACCT_ID,
        S.SA_TYPE_CD,
        BL.BILL_ID,
        BL.BILL_CYCLE_CODE,
        BCL.DESCR AS BILL_CYCLE_DESCRIPTION
    FROM CISADM.D1_USAGE U
    JOIN CISADM.CI_SA S
        ON TO_CHAR(U.USG_EXT_ID) = TO_CHAR(S.SA_ID)
    LEFT JOIN (
        SELECT
            B.ACCT_ID,
            B.BILL_ID,
            TRIM(B.BILL_CYC_CD) AS BILL_CYCLE_CODE,
            ROW_NUMBER() OVER (
                PARTITION BY B.ACCT_ID
                ORDER BY NVL(B.BILL_DT, B.CRE_DTTM) DESC, B.BILL_ID DESC
            ) AS RN
        FROM CISADM.CI_BILL B
    ) BL
        ON BL.ACCT_ID = S.ACCT_ID
       AND BL.RN = 1
    LEFT JOIN CISADM.CI_BILL_CYC_L BCL
        ON TRIM(BCL.BILL_CYC_CD) = BL.BILL_CYCLE_CODE
       AND BCL.LANGUAGE_CD IN ('ENG', 'EN')
    CROSS JOIN PARAMS P
    WHERE U.USG_EXT_ID IS NOT NULL
      AND U.START_DTTM >= P.START_DT
      AND U.START_DTTM <  P.END_DT + 1
      AND EXISTS (SELECT 1 FROM A_CNT WHERE MATCH_COUNT > 0)
    ORDER BY U.START_DTTM DESC
)
WHERE ROWNUM <= 50;

-- Bill cycle sample (run regardless of path A/B/C/D to confirm reporting attributes).
SELECT *
FROM (
    SELECT
        B.BILL_ID,
        B.ACCT_ID,
        TRIM(B.BILL_CYC_CD) AS BILL_CYCLE_CODE,
        L.DESCR AS BILL_CYCLE_DESCRIPTION,
        NVL(B.BILL_DT, B.CRE_DTTM) AS BILL_EVENT_DTTM
    FROM CISADM.CI_BILL B
    LEFT JOIN CISADM.CI_BILL_CYC_L L
        ON TRIM(L.BILL_CYC_CD) = TRIM(B.BILL_CYC_CD)
       AND L.LANGUAGE_CD IN ('ENG', 'EN')
    WHERE NVL(B.BILL_DT, B.CRE_DTTM) >= NVL(TO_DATE(:P_START_DATE, 'YYYY-MM-DD'), DATE '2026-01-01')
      AND NVL(B.BILL_DT, B.CRE_DTTM) <  NVL(TO_DATE(:P_END_DATE,   'YYYY-MM-DD'), DATE '2026-01-31') + 1
    ORDER BY NVL(B.BILL_DT, B.CRE_DTTM) DESC
)
WHERE ROWNUM <= 50;

-- Path B sample: USG_EXT_ID -> ACCT_ID
WITH
PARAMS AS (
    SELECT
        NVL(TO_DATE(:P_START_DATE, 'YYYY-MM-DD'), DATE '2026-01-01') AS START_DT,
        NVL(TO_DATE(:P_END_DATE,   'YYYY-MM-DD'), DATE '2026-01-31') AS END_DT
    FROM DUAL
),
B_CNT AS (
    SELECT COUNT(*) AS MATCH_COUNT
    FROM CISADM.D1_USAGE U
    JOIN CISADM.CI_ACCT A
        ON TO_CHAR(U.USG_EXT_ID) = TO_CHAR(A.ACCT_ID)
    CROSS JOIN PARAMS P
    WHERE U.USG_EXT_ID IS NOT NULL
      AND U.START_DTTM >= P.START_DT
      AND U.START_DTTM <  P.END_DT + 1
)
SELECT *
FROM (
    SELECT
        U.D1_USAGE_ID,
        U.USG_EXT_ID,
        U.START_DTTM AS USAGE_START_DTTM,
        A.ACCT_ID,
        BL.BILL_ID,
        BL.BILL_CYCLE_CODE,
        BCL.DESCR AS BILL_CYCLE_DESCRIPTION
    FROM CISADM.D1_USAGE U
    JOIN CISADM.CI_ACCT A
        ON TO_CHAR(U.USG_EXT_ID) = TO_CHAR(A.ACCT_ID)
    LEFT JOIN (
        SELECT
            B.ACCT_ID,
            B.BILL_ID,
            TRIM(B.BILL_CYC_CD) AS BILL_CYCLE_CODE,
            ROW_NUMBER() OVER (
                PARTITION BY B.ACCT_ID
                ORDER BY NVL(B.BILL_DT, B.CRE_DTTM) DESC, B.BILL_ID DESC
            ) AS RN
        FROM CISADM.CI_BILL B
    ) BL
        ON BL.ACCT_ID = A.ACCT_ID
       AND BL.RN = 1
    LEFT JOIN CISADM.CI_BILL_CYC_L BCL
        ON TRIM(BCL.BILL_CYC_CD) = BL.BILL_CYCLE_CODE
       AND BCL.LANGUAGE_CD IN ('ENG', 'EN')
    CROSS JOIN PARAMS P
    WHERE U.USG_EXT_ID IS NOT NULL
      AND U.START_DTTM >= P.START_DT
      AND U.START_DTTM <  P.END_DT + 1
      AND EXISTS (SELECT 1 FROM B_CNT WHERE MATCH_COUNT > 0)
    ORDER BY U.START_DTTM DESC
)
WHERE ROWNUM <= 50;

-- Path C sample: D1_SP_ID -> CI_SA_SP -> CI_SA
WITH
PARAMS AS (
    SELECT
        NVL(TO_DATE(:P_START_DATE, 'YYYY-MM-DD'), DATE '2026-01-01') AS START_DT,
        NVL(TO_DATE(:P_END_DATE,   'YYYY-MM-DD'), DATE '2026-01-31') AS END_DT
    FROM DUAL
),
C_CNT AS (
    SELECT COUNT(*) AS MATCH_COUNT
    FROM CISADM.D1_USAGE_SCALAR_DTL D
    JOIN CISADM.CI_SA_SP SAS
        ON TO_CHAR(D.D1_SP_ID) = TO_CHAR(SAS.SP_ID)
    CROSS JOIN PARAMS P
    WHERE D.D1_SP_ID IS NOT NULL
      AND D.START_DTTM >= P.START_DT
      AND D.START_DTTM <  P.END_DT + 1
)
SELECT *
FROM (
    SELECT
        D.D1_USAGE_ID,
        D.D1_SP_ID,
        D.SEQ_NUM,
        D.START_DTTM AS DTL_START_DTTM,
        SAS.SP_ID,
        SAS.SA_ID,
        S.ACCT_ID,
        BL.BILL_ID,
        BL.BILL_CYCLE_CODE,
        BCL.DESCR AS BILL_CYCLE_DESCRIPTION
    FROM CISADM.D1_USAGE_SCALAR_DTL D
    JOIN CISADM.CI_SA_SP SAS
        ON TO_CHAR(D.D1_SP_ID) = TO_CHAR(SAS.SP_ID)
    JOIN CISADM.CI_SA S
        ON TO_CHAR(S.SA_ID) = TO_CHAR(SAS.SA_ID)
    LEFT JOIN (
        SELECT
            B.ACCT_ID,
            B.BILL_ID,
            TRIM(B.BILL_CYC_CD) AS BILL_CYCLE_CODE,
            ROW_NUMBER() OVER (
                PARTITION BY B.ACCT_ID
                ORDER BY NVL(B.BILL_DT, B.CRE_DTTM) DESC, B.BILL_ID DESC
            ) AS RN
        FROM CISADM.CI_BILL B
    ) BL
        ON BL.ACCT_ID = S.ACCT_ID
       AND BL.RN = 1
    LEFT JOIN CISADM.CI_BILL_CYC_L BCL
        ON TRIM(BCL.BILL_CYC_CD) = BL.BILL_CYCLE_CODE
       AND BCL.LANGUAGE_CD IN ('ENG', 'EN')
    CROSS JOIN PARAMS P
    WHERE D.D1_SP_ID IS NOT NULL
      AND D.START_DTTM >= P.START_DT
      AND D.START_DTTM <  P.END_DT + 1
      AND EXISTS (SELECT 1 FROM C_CNT WHERE MATCH_COUNT > 0)
    ORDER BY D.START_DTTM DESC
)
WHERE ROWNUM <= 50;

-- Path D sample: D1_SP_ID -> D1_SP -> CI_SP -> CI_SA_SP -> CI_SA
WITH
PARAMS AS (
    SELECT
        NVL(TO_DATE(:P_START_DATE, 'YYYY-MM-DD'), DATE '2026-01-01') AS START_DT,
        NVL(TO_DATE(:P_END_DATE,   'YYYY-MM-DD'), DATE '2026-01-31') AS END_DT
    FROM DUAL
),
D_CNT AS (
    SELECT COUNT(*) AS MATCH_COUNT
    FROM CISADM.D1_USAGE_SCALAR_DTL D
    JOIN CISADM.D1_SP DSP
        ON TO_CHAR(D.D1_SP_ID) = TO_CHAR(DSP.D1_SP_ID)
    JOIN CISADM.CI_SP CSP
        ON TO_CHAR(CSP.SP_ID) = TO_CHAR(DSP.D1_SP_ID)
    JOIN CISADM.CI_SA_SP SAS
        ON TO_CHAR(SAS.SP_ID) = TO_CHAR(CSP.SP_ID)
    JOIN CISADM.CI_SA S
        ON TO_CHAR(S.SA_ID) = TO_CHAR(SAS.SA_ID)
    CROSS JOIN PARAMS P
    WHERE D.D1_SP_ID IS NOT NULL
      AND D.START_DTTM >= P.START_DT
      AND D.START_DTTM <  P.END_DT + 1
)
SELECT *
FROM (
    SELECT
        D.D1_USAGE_ID,
        D.D1_SP_ID,
        DSP.D1_SP_ID AS D1_SP_TO_CI_SP_ID,
        SAS.SA_ID,
        S.ACCT_ID,
        D.START_DTTM AS DTL_START_DTTM,
        BL.BILL_ID,
        BL.BILL_CYCLE_CODE,
        BCL.DESCR AS BILL_CYCLE_DESCRIPTION
    FROM CISADM.D1_USAGE_SCALAR_DTL D
    JOIN CISADM.D1_SP DSP
        ON TO_CHAR(D.D1_SP_ID) = TO_CHAR(DSP.D1_SP_ID)
    JOIN CISADM.CI_SP CSP
        ON TO_CHAR(CSP.SP_ID) = TO_CHAR(DSP.D1_SP_ID)
    JOIN CISADM.CI_SA_SP SAS
        ON TO_CHAR(SAS.SP_ID) = TO_CHAR(CSP.SP_ID)
    JOIN CISADM.CI_SA S
        ON TO_CHAR(S.SA_ID) = TO_CHAR(SAS.SA_ID)
    LEFT JOIN (
        SELECT
            B.ACCT_ID,
            B.BILL_ID,
            TRIM(B.BILL_CYC_CD) AS BILL_CYCLE_CODE,
            ROW_NUMBER() OVER (
                PARTITION BY B.ACCT_ID
                ORDER BY NVL(B.BILL_DT, B.CRE_DTTM) DESC, B.BILL_ID DESC
            ) AS RN
        FROM CISADM.CI_BILL B
    ) BL
        ON BL.ACCT_ID = S.ACCT_ID
       AND BL.RN = 1
    LEFT JOIN CISADM.CI_BILL_CYC_L BCL
        ON TRIM(BCL.BILL_CYC_CD) = BL.BILL_CYCLE_CODE
       AND BCL.LANGUAGE_CD IN ('ENG', 'EN')
    CROSS JOIN PARAMS P
    WHERE D.D1_SP_ID IS NOT NULL
      AND D.START_DTTM >= P.START_DT
      AND D.START_DTTM <  P.END_DT + 1
      AND EXISTS (SELECT 1 FROM D_CNT WHERE MATCH_COUNT > 0)
    ORDER BY D.START_DTTM DESC
)
WHERE ROWNUM <= 50;

-- Path G sample: D1_USAGE -> C1_USAGE -> CI_SA (with bill cycle code/description)
WITH
PARAMS AS (
    SELECT
        NVL(TO_DATE(:P_START_DATE, 'YYYY-MM-DD'), DATE '2026-01-01') AS START_DT,
        NVL(TO_DATE(:P_END_DATE,   'YYYY-MM-DD'), DATE '2026-01-31') AS END_DT
    FROM DUAL
),
G_CNT AS (
    SELECT COUNT(*) AS MATCH_COUNT
    FROM CISADM.D1_USAGE U
    JOIN CISADM.C1_USAGE CU
        ON TO_CHAR(CU.USAGE_ID) = TO_CHAR(U.D1_USAGE_ID)
    JOIN CISADM.CI_SA S
        ON TO_CHAR(S.SA_ID) = TO_CHAR(CU.SA_ID)
    CROSS JOIN PARAMS P
    WHERE U.D1_USAGE_ID IS NOT NULL
      AND U.START_DTTM >= P.START_DT
      AND U.START_DTTM <  P.END_DT + 1
)
SELECT *
FROM (
    SELECT
        U.D1_USAGE_ID,
        U.USG_EXT_ID,
        U.START_DTTM AS USAGE_START_DTTM,
        CU.USAGE_ID AS C1_USAGE_ID,
        CU.SA_ID,
        S.ACCT_ID,
        BL.BILL_ID,
        BL.BILL_CYCLE_CODE,
        BCL.DESCR AS BILL_CYCLE_DESCRIPTION
    FROM CISADM.D1_USAGE U
    JOIN CISADM.C1_USAGE CU
        ON TO_CHAR(CU.USAGE_ID) = TO_CHAR(U.D1_USAGE_ID)
    JOIN CISADM.CI_SA S
        ON TO_CHAR(S.SA_ID) = TO_CHAR(CU.SA_ID)
    LEFT JOIN (
        SELECT
            B.ACCT_ID,
            B.BILL_ID,
            TRIM(B.BILL_CYC_CD) AS BILL_CYCLE_CODE,
            ROW_NUMBER() OVER (
                PARTITION BY B.ACCT_ID
                ORDER BY NVL(B.BILL_DT, B.CRE_DTTM) DESC, B.BILL_ID DESC
            ) AS RN
        FROM CISADM.CI_BILL B
    ) BL
        ON BL.ACCT_ID = S.ACCT_ID
       AND BL.RN = 1
    LEFT JOIN CISADM.CI_BILL_CYC_L BCL
        ON TRIM(BCL.BILL_CYC_CD) = BL.BILL_CYCLE_CODE
       AND BCL.LANGUAGE_CD IN ('ENG', 'EN')
    CROSS JOIN PARAMS P
    WHERE U.D1_USAGE_ID IS NOT NULL
      AND U.START_DTTM >= P.START_DT
      AND U.START_DTTM <  P.END_DT + 1
      AND EXISTS (SELECT 1 FROM G_CNT WHERE MATCH_COUNT > 0)
    ORDER BY U.START_DTTM DESC
)
WHERE ROWNUM <= 50;

-- Path H sample: DTL -> D1_SP_USG_SNAP_DL -> CI_SA (with bill cycle code/description)
WITH
PARAMS AS (
    SELECT
        NVL(TO_DATE(:P_START_DATE, 'YYYY-MM-DD'), DATE '2026-01-01') AS START_DT,
        NVL(TO_DATE(:P_END_DATE,   'YYYY-MM-DD'), DATE '2026-01-31') AS END_DT
    FROM DUAL
),
H_CNT AS (
    SELECT COUNT(*) AS MATCH_COUNT
    FROM CISADM.D1_USAGE_SCALAR_DTL D
    JOIN CISADM.D1_SP_USG_SNAP_DL SN
        ON TO_CHAR(SN.D1_SP_ID) = TO_CHAR(D.D1_SP_ID)
    JOIN CISADM.CI_SA S
        ON TO_CHAR(S.SA_ID) = TO_CHAR(SN.CIS_EXT_SA_ID)
    CROSS JOIN PARAMS P
    WHERE D.D1_SP_ID IS NOT NULL
      AND D.START_DTTM >= P.START_DT
      AND D.START_DTTM <  P.END_DT + 1
)
SELECT *
FROM (
    SELECT
        D.D1_USAGE_ID,
        D.D1_SP_ID,
        D.START_DTTM AS DTL_START_DTTM,
        SN.CIS_EXT_SA_ID,
        S.SA_ID,
        S.ACCT_ID,
        BL.BILL_ID,
        BL.BILL_CYCLE_CODE,
        BCL.DESCR AS BILL_CYCLE_DESCRIPTION
    FROM CISADM.D1_USAGE_SCALAR_DTL D
    JOIN CISADM.D1_SP_USG_SNAP_DL SN
        ON TO_CHAR(SN.D1_SP_ID) = TO_CHAR(D.D1_SP_ID)
    JOIN CISADM.CI_SA S
        ON TO_CHAR(S.SA_ID) = TO_CHAR(SN.CIS_EXT_SA_ID)
    LEFT JOIN (
        SELECT
            B.ACCT_ID,
            B.BILL_ID,
            TRIM(B.BILL_CYC_CD) AS BILL_CYCLE_CODE,
            ROW_NUMBER() OVER (
                PARTITION BY B.ACCT_ID
                ORDER BY NVL(B.BILL_DT, B.CRE_DTTM) DESC, B.BILL_ID DESC
            ) AS RN
        FROM CISADM.CI_BILL B
    ) BL
        ON BL.ACCT_ID = S.ACCT_ID
       AND BL.RN = 1
    LEFT JOIN CISADM.CI_BILL_CYC_L BCL
        ON TRIM(BCL.BILL_CYC_CD) = BL.BILL_CYCLE_CODE
       AND BCL.LANGUAGE_CD IN ('ENG', 'EN')
    CROSS JOIN PARAMS P
    WHERE D.D1_SP_ID IS NOT NULL
      AND D.START_DTTM >= P.START_DT
      AND D.START_DTTM <  P.END_DT + 1
      AND EXISTS (SELECT 1 FROM H_CNT WHERE MATCH_COUNT > 0)
    ORDER BY D.START_DTTM DESC
)
WHERE ROWNUM <= 50;

-- Path I sample: USG_EXT_ID -> C1_BI_BILLED_USAGE_VW.SA_ID (with bill cycle code/description)
WITH
PARAMS AS (
    SELECT
        NVL(TO_DATE(:P_START_DATE, 'YYYY-MM-DD'), DATE '2026-01-01') AS START_DT,
        NVL(TO_DATE(:P_END_DATE,   'YYYY-MM-DD'), DATE '2026-01-31') AS END_DT
    FROM DUAL
),
I_CNT AS (
    SELECT COUNT(*) AS MATCH_COUNT
    FROM CISADM.D1_USAGE U
    JOIN CISADM.C1_BI_BILLED_USAGE_VW V
        ON TO_CHAR(V.SA_ID) = TO_CHAR(U.USG_EXT_ID)
    CROSS JOIN PARAMS P
    WHERE U.USG_EXT_ID IS NOT NULL
      AND U.START_DTTM >= P.START_DT
      AND U.START_DTTM <  P.END_DT + 1
)
SELECT *
FROM (
    SELECT
        U.D1_USAGE_ID,
        U.USG_EXT_ID,
        U.START_DTTM AS USAGE_START_DTTM,
        V.SA_ID,
        V.ACCT_ID,
        BL.BILL_ID,
        BL.BILL_CYCLE_CODE,
        BCL.DESCR AS BILL_CYCLE_DESCRIPTION
    FROM CISADM.D1_USAGE U
    JOIN CISADM.C1_BI_BILLED_USAGE_VW V
        ON TO_CHAR(V.SA_ID) = TO_CHAR(U.USG_EXT_ID)
    LEFT JOIN (
        SELECT
            B.ACCT_ID,
            B.BILL_ID,
            TRIM(B.BILL_CYC_CD) AS BILL_CYCLE_CODE,
            ROW_NUMBER() OVER (
                PARTITION BY B.ACCT_ID
                ORDER BY NVL(B.BILL_DT, B.CRE_DTTM) DESC, B.BILL_ID DESC
            ) AS RN
        FROM CISADM.CI_BILL B
    ) BL
        ON BL.ACCT_ID = V.ACCT_ID
       AND BL.RN = 1
    LEFT JOIN CISADM.CI_BILL_CYC_L BCL
        ON TRIM(BCL.BILL_CYC_CD) = BL.BILL_CYCLE_CODE
       AND BCL.LANGUAGE_CD IN ('ENG', 'EN')
    CROSS JOIN PARAMS P
    WHERE U.USG_EXT_ID IS NOT NULL
      AND U.START_DTTM >= P.START_DT
      AND U.START_DTTM <  P.END_DT + 1
      AND EXISTS (SELECT 1 FROM I_CNT WHERE MATCH_COUNT > 0)
    ORDER BY U.START_DTTM DESC
)
WHERE ROWNUM <= 50;

-- =====================================================================
-- 6) NO-MAP ESCALATION: STAGING/INTEGRATION TABLE HUNT (HEAVIER)
-- WHY: If A/B/C/D all return 0, locate where USG_EXT_ID might be translated.
-- WARNING: Heavier metadata scan. Run only with DBA approval.
-- =====================================================================

-- 6A) Identify likely integration tables/columns by naming pattern.
SELECT
    C.OWNER,
    C.TABLE_NAME,
    C.COLUMN_NAME,
    C.DATA_TYPE
FROM ALL_TAB_COLUMNS C
WHERE C.OWNER = 'CISADM'
  AND (
      C.TABLE_NAME LIKE 'INT\_%' ESCAPE '\'
      OR C.TABLE_NAME LIKE 'STG\_%' ESCAPE '\'
      OR C.TABLE_NAME LIKE 'BEACON\_%' ESCAPE '\'
      OR C.TABLE_NAME LIKE 'CMS\_%' ESCAPE '\'
      OR C.TABLE_NAME LIKE '%USG%'
      OR C.TABLE_NAME LIKE '%USAGE%'
  )
  AND (
      C.COLUMN_NAME LIKE '%USG_EXT_ID%'
      OR C.COLUMN_NAME LIKE '%EXT_ID%'
      OR C.COLUMN_NAME LIKE '%USAGE_ID%'
      OR C.COLUMN_NAME LIKE '%SA_ID%'
      OR C.COLUMN_NAME LIKE '%SP_ID%'
      OR C.COLUMN_NAME LIKE '%ACCOUNT%'
      OR C.COLUMN_NAME LIKE '%ACCT%'
  )
ORDER BY C.TABLE_NAME, C.COLUMN_NAME;

-- 6B) Build copy/paste probe SQL for one sampled USG_EXT_ID (does NOT execute probes).
WITH SAMPLE_EXT AS (
    SELECT U.USG_EXT_ID
    FROM CISADM.D1_USAGE U
    WHERE U.USG_EXT_ID IS NOT NULL
      AND U.START_DTTM >= NVL(TO_DATE(:P_START_DATE, 'YYYY-MM-DD'), DATE '2026-01-01')
      AND U.START_DTTM <  NVL(TO_DATE(:P_END_DATE,   'YYYY-MM-DD'), DATE '2026-01-31') + 1
      AND ROWNUM = 1
)
SELECT
    'SELECT ''' || C.TABLE_NAME || ''' AS TABLE_NAME, ''' || C.COLUMN_NAME || ''' AS COLUMN_NAME, COUNT(*) AS MATCH_COUNT ' ||
    'FROM CISADM.' || C.TABLE_NAME ||
    ' WHERE TRIM(TO_CHAR(' || C.COLUMN_NAME || ')) = ''' || REPLACE(TRIM(SE.USG_EXT_ID), '''', '''''') || ''' AND ROWNUM <= 500;' AS PROBE_SQL
FROM ALL_TAB_COLUMNS C
CROSS JOIN SAMPLE_EXT SE
WHERE C.OWNER = 'CISADM'
  AND (
      C.TABLE_NAME LIKE 'INT\_%' ESCAPE '\'
      OR C.TABLE_NAME LIKE 'STG\_%' ESCAPE '\'
      OR C.TABLE_NAME LIKE 'BEACON\_%' ESCAPE '\'
      OR C.TABLE_NAME LIKE 'CMS\_%' ESCAPE '\'
      OR C.TABLE_NAME LIKE '%USG%'
      OR C.TABLE_NAME LIKE '%USAGE%'
  )
  AND (
      C.COLUMN_NAME LIKE '%USG_EXT_ID%'
      OR C.COLUMN_NAME LIKE '%EXT_ID%'
      OR C.COLUMN_NAME LIKE '%USAGE_ID%'
      OR C.COLUMN_NAME LIKE '%SA_ID%'
      OR C.COLUMN_NAME LIKE '%SP_ID%'
      OR C.COLUMN_NAME LIKE '%ACCOUNT%'
      OR C.COLUMN_NAME LIKE '%ACCT%'
  )
  AND C.DATA_TYPE IN ('VARCHAR2', 'CHAR', 'NUMBER')
  AND ROWNUM <= 120
ORDER BY C.TABLE_NAME, C.COLUMN_NAME;

-- =====================================================================
-- 7) NORMALIZED WINNER BLOCK (TRIM-BASED + ALTERNATE C1_USAGE PATHS)
-- WHY: CHAR padding and alternate usage keys commonly cause false 0 matches.
-- RUN THIS BLOCK TO IDENTIFY THE REAL WORKING PATH QUICKLY.
-- =====================================================================

-- 7A) Bill cycle fallback coverage: use CI_BILL.BILL_CYC_CD else CI_ACCT.BILL_CYC_CD
SELECT
    COUNT(*) AS TOTAL_BILLS,
    COUNT(CASE WHEN TRIM(NVL(B.BILL_CYC_CD, A.BILL_CYC_CD)) IS NOT NULL THEN 1 END) AS BILLS_WITH_EFFECTIVE_CYCLE,
    COUNT(CASE WHEN TRIM(L.DESCR) IS NOT NULL THEN 1 END) AS BILLS_WITH_CYCLE_DESCRIPTION
FROM CISADM.CI_BILL B
LEFT JOIN CISADM.CI_ACCT A
    ON TRIM(A.ACCT_ID) = TRIM(B.ACCT_ID)
LEFT JOIN CISADM.CI_BILL_CYC_L L
    ON TRIM(L.BILL_CYC_CD) = TRIM(NVL(B.BILL_CYC_CD, A.BILL_CYC_CD))
   AND L.LANGUAGE_CD IN ('ENG', 'EN');

SELECT *
FROM (
    SELECT
        B.BILL_ID,
        B.ACCT_ID,
        TRIM(NVL(B.BILL_CYC_CD, A.BILL_CYC_CD)) AS BILL_CYCLE_CODE,
        L.DESCR AS BILL_CYCLE_DESCRIPTION,
        NVL(B.BILL_DT, B.CRE_DTTM) AS BILL_EVENT_DTTM
    FROM CISADM.CI_BILL B
    LEFT JOIN CISADM.CI_ACCT A
        ON TRIM(A.ACCT_ID) = TRIM(B.ACCT_ID)
    LEFT JOIN CISADM.CI_BILL_CYC_L L
        ON TRIM(L.BILL_CYC_CD) = TRIM(NVL(B.BILL_CYC_CD, A.BILL_CYC_CD))
       AND L.LANGUAGE_CD IN ('ENG', 'EN')
    ORDER BY NVL(B.BILL_DT, B.CRE_DTTM) DESC
)
WHERE ROWNUM <= 50;

-- 7A-ALT) Bill cycle fallback from D1 usage measurement cycle code.
SELECT
    COUNT(*) AS TOTAL_USAGE_ROWS,
    COUNT(CASE WHEN TRIM(U.MSRMT_CYC_CD) IS NOT NULL THEN 1 END) AS USAGE_ROWS_WITH_MSRMT_CYC_CD,
    COUNT(CASE WHEN TRIM(L.DESCR) IS NOT NULL THEN 1 END) AS USAGE_ROWS_WITH_CYCLE_DESCRIPTION
FROM CISADM.D1_USAGE U
LEFT JOIN CISADM.CI_BILL_CYC_L L
    ON TRIM(L.BILL_CYC_CD) = TRIM(U.MSRMT_CYC_CD)
   AND L.LANGUAGE_CD IN ('ENG', 'EN');

SELECT *
FROM (
    SELECT
        U.D1_USAGE_ID,
        TRIM(U.MSRMT_CYC_CD) AS BILL_CYCLE_CODE,
        L.DESCR AS BILL_CYCLE_DESCRIPTION,
        U.START_DTTM
    FROM CISADM.D1_USAGE U
    LEFT JOIN CISADM.CI_BILL_CYC_L L
        ON TRIM(L.BILL_CYC_CD) = TRIM(U.MSRMT_CYC_CD)
       AND L.LANGUAGE_CD IN ('ENG', 'EN')
    ORDER BY U.START_DTTM DESC
)
WHERE ROWNUM <= 50;

-- 7B) Winner summary with normalized joins and alternate usage bridges.
WITH
PARAMS AS (
    SELECT
        NVL(TO_DATE(:P_START_DATE, 'YYYY-MM-DD'), DATE '2000-01-01') AS START_DT,
        NVL(TO_DATE(:P_END_DATE,   'YYYY-MM-DD'), DATE '2099-12-31') AS END_DT
    FROM DUAL
),
P1 AS ( -- USG_EXT_ID -> SA_ID
    SELECT COUNT(*) AS MATCH_COUNT
    FROM CISADM.D1_USAGE U
    JOIN CISADM.CI_SA S
      ON TRIM(U.USG_EXT_ID) = TRIM(S.SA_ID)
    CROSS JOIN PARAMS P
    WHERE U.START_DTTM >= P.START_DT
      AND U.START_DTTM <  P.END_DT + 1
),
P2 AS ( -- USG_EXT_ID -> ACCT_ID
    SELECT COUNT(*) AS MATCH_COUNT
    FROM CISADM.D1_USAGE U
    JOIN CISADM.CI_ACCT A
      ON TRIM(U.USG_EXT_ID) = TRIM(A.ACCT_ID)
    CROSS JOIN PARAMS P
    WHERE U.START_DTTM >= P.START_DT
      AND U.START_DTTM <  P.END_DT + 1
),
P3 AS ( -- DTL.D1_SP_ID -> CI_SA_SP.SP_ID
    SELECT COUNT(*) AS MATCH_COUNT
    FROM CISADM.D1_USAGE_SCALAR_DTL D
    JOIN CISADM.CI_SA_SP SAS
      ON TRIM(D.D1_SP_ID) = TRIM(SAS.SP_ID)
    CROSS JOIN PARAMS P
    WHERE D.START_DTTM >= P.START_DT
      AND D.START_DTTM <  P.END_DT + 1
),
P4 AS ( -- D1_USAGE_ID -> C1_USAGE.USAGE_ID -> SA
    SELECT COUNT(*) AS MATCH_COUNT
    FROM CISADM.D1_USAGE U
    JOIN CISADM.C1_USAGE CU
      ON TRIM(U.D1_USAGE_ID) = TRIM(CU.USAGE_ID)
    JOIN CISADM.CI_SA S
      ON TRIM(S.SA_ID) = TRIM(CU.SA_ID)
    CROSS JOIN PARAMS P
    WHERE U.START_DTTM >= P.START_DT
      AND U.START_DTTM <  P.END_DT + 1
),
P5 AS ( -- D1_USAGE_ID -> C1_USAGE.MASTER_USAGE_ID -> SA
    SELECT COUNT(*) AS MATCH_COUNT
    FROM CISADM.D1_USAGE U
    JOIN CISADM.C1_USAGE CU
      ON TRIM(U.D1_USAGE_ID) = TRIM(CU.MASTER_USAGE_ID)
    JOIN CISADM.CI_SA S
      ON TRIM(S.SA_ID) = TRIM(CU.SA_ID)
    CROSS JOIN PARAMS P
    WHERE U.START_DTTM >= P.START_DT
      AND U.START_DTTM <  P.END_DT + 1
),
P6 AS ( -- US_ID -> C1_USAGE.USAGE_ID -> SA
    SELECT COUNT(*) AS MATCH_COUNT
    FROM CISADM.D1_USAGE U
    JOIN CISADM.C1_USAGE CU
      ON TRIM(U.US_ID) = TRIM(CU.USAGE_ID)
    JOIN CISADM.CI_SA S
      ON TRIM(S.SA_ID) = TRIM(CU.SA_ID)
    CROSS JOIN PARAMS P
    WHERE U.START_DTTM >= P.START_DT
      AND U.START_DTTM <  P.END_DT + 1
),
P7 AS ( -- US_ID -> C1_USAGE.MASTER_USAGE_ID -> SA
    SELECT COUNT(*) AS MATCH_COUNT
    FROM CISADM.D1_USAGE U
    JOIN CISADM.C1_USAGE CU
      ON TRIM(U.US_ID) = TRIM(CU.MASTER_USAGE_ID)
    JOIN CISADM.CI_SA S
      ON TRIM(S.SA_ID) = TRIM(CU.SA_ID)
    CROSS JOIN PARAMS P
    WHERE U.START_DTTM >= P.START_DT
      AND U.START_DTTM <  P.END_DT + 1
),
P8 AS ( -- DTL.D1_SP_ID -> C1_USAGE.SP_ID -> SA
    SELECT COUNT(*) AS MATCH_COUNT
    FROM CISADM.D1_USAGE_SCALAR_DTL D
    JOIN CISADM.C1_USAGE CU
      ON TRIM(D.D1_SP_ID) = TRIM(CU.SP_ID)
    JOIN CISADM.CI_SA S
      ON TRIM(S.SA_ID) = TRIM(CU.SA_ID)
    CROSS JOIN PARAMS P
    WHERE D.START_DTTM >= P.START_DT
      AND D.START_DTTM <  P.END_DT + 1
),
P9 AS ( -- DTL.D1_SP_ID -> D1_SP_USG_SNAP_DL.D1_SP_ID -> CIS_EXT_SA_ID -> SA
    SELECT COUNT(*) AS MATCH_COUNT
    FROM CISADM.D1_USAGE_SCALAR_DTL D
    JOIN CISADM.D1_SP_USG_SNAP_DL SN
      ON TRIM(D.D1_SP_ID) = TRIM(SN.D1_SP_ID)
    JOIN CISADM.CI_SA S
      ON TRIM(S.SA_ID) = TRIM(SN.CIS_EXT_SA_ID)
    CROSS JOIN PARAMS P
    WHERE D.START_DTTM >= P.START_DT
      AND D.START_DTTM <  P.END_DT + 1
),
P10 AS ( -- D1_USAGE_ID -> C1_USAGE.USAGE_ID -> C1_USAGE.BSEG_ID -> CI_BSEG.SA_ID
    SELECT COUNT(*) AS MATCH_COUNT
    FROM CISADM.D1_USAGE U
    JOIN CISADM.C1_USAGE CU
      ON TRIM(U.D1_USAGE_ID) = TRIM(CU.USAGE_ID)
    JOIN CISADM.CI_BSEG BS
      ON TRIM(BS.BSEG_ID) = TRIM(CU.BSEG_ID)
    JOIN CISADM.CI_SA S
      ON TRIM(S.SA_ID) = TRIM(BS.SA_ID)
    CROSS JOIN PARAMS P
    WHERE U.START_DTTM >= P.START_DT
      AND U.START_DTTM <  P.END_DT + 1
),
P11 AS ( -- D1_USAGE_ID -> C1_USAGE.MASTER_USAGE_ID -> C1_USAGE.BSEG_ID -> CI_BSEG.SA_ID
    SELECT COUNT(*) AS MATCH_COUNT
    FROM CISADM.D1_USAGE U
    JOIN CISADM.C1_USAGE CU
      ON TRIM(U.D1_USAGE_ID) = TRIM(CU.MASTER_USAGE_ID)
    JOIN CISADM.CI_BSEG BS
      ON TRIM(BS.BSEG_ID) = TRIM(CU.BSEG_ID)
    JOIN CISADM.CI_SA S
      ON TRIM(S.SA_ID) = TRIM(BS.SA_ID)
    CROSS JOIN PARAMS P
    WHERE U.START_DTTM >= P.START_DT
      AND U.START_DTTM <  P.END_DT + 1
),
P12 AS ( -- US_ID -> C1_USAGE.USAGE_ID -> C1_USAGE.BSEG_ID -> CI_BSEG.SA_ID
    SELECT COUNT(*) AS MATCH_COUNT
    FROM CISADM.D1_USAGE U
    JOIN CISADM.C1_USAGE CU
      ON TRIM(U.US_ID) = TRIM(CU.USAGE_ID)
    JOIN CISADM.CI_BSEG BS
      ON TRIM(BS.BSEG_ID) = TRIM(CU.BSEG_ID)
    JOIN CISADM.CI_SA S
      ON TRIM(S.SA_ID) = TRIM(BS.SA_ID)
    CROSS JOIN PARAMS P
    WHERE U.START_DTTM >= P.START_DT
      AND U.START_DTTM <  P.END_DT + 1
),
PATHS AS (
    SELECT 'P1_USG_EXT_TO_SA' AS PATH, (SELECT MATCH_COUNT FROM P1) AS MATCH_COUNT, 'D1_USAGE.USG_EXT_ID = CI_SA.SA_ID (TRIM)' AS NOTES FROM DUAL
    UNION ALL SELECT 'P2_USG_EXT_TO_ACCT', (SELECT MATCH_COUNT FROM P2), 'D1_USAGE.USG_EXT_ID = CI_ACCT.ACCT_ID (TRIM)' FROM DUAL
    UNION ALL SELECT 'P3_DTL_SP_TO_SA_SP', (SELECT MATCH_COUNT FROM P3), 'D1_USAGE_SCALAR_DTL.D1_SP_ID = CI_SA_SP.SP_ID (TRIM)' FROM DUAL
    UNION ALL SELECT 'P4_D1_USAGEID_TO_C1_USAGEID', (SELECT MATCH_COUNT FROM P4), 'D1_USAGE.D1_USAGE_ID = C1_USAGE.USAGE_ID -> SA_ID' FROM DUAL
    UNION ALL SELECT 'P5_D1_USAGEID_TO_MASTER_USAGE', (SELECT MATCH_COUNT FROM P5), 'D1_USAGE.D1_USAGE_ID = C1_USAGE.MASTER_USAGE_ID -> SA_ID' FROM DUAL
    UNION ALL SELECT 'P6_USID_TO_C1_USAGEID', (SELECT MATCH_COUNT FROM P6), 'D1_USAGE.US_ID = C1_USAGE.USAGE_ID -> SA_ID' FROM DUAL
    UNION ALL SELECT 'P7_USID_TO_MASTER_USAGE', (SELECT MATCH_COUNT FROM P7), 'D1_USAGE.US_ID = C1_USAGE.MASTER_USAGE_ID -> SA_ID' FROM DUAL
    UNION ALL SELECT 'P8_DTLSP_TO_C1SP', (SELECT MATCH_COUNT FROM P8), 'D1_USAGE_SCALAR_DTL.D1_SP_ID = C1_USAGE.SP_ID -> SA_ID' FROM DUAL
    UNION ALL SELECT 'P9_DTLSP_TO_SNAP_SA', (SELECT MATCH_COUNT FROM P9), 'D1_SP_USG_SNAP_DL.CIS_EXT_SA_ID -> CI_SA.SA_ID' FROM DUAL
    UNION ALL SELECT 'P10_D1USAGE_TO_C1USAGE_TO_BSEG_TO_SA', (SELECT MATCH_COUNT FROM P10), 'D1_USAGE.D1_USAGE_ID -> C1_USAGE.USAGE_ID -> C1_USAGE.BSEG_ID -> CI_BSEG.SA_ID' FROM DUAL
    UNION ALL SELECT 'P11_D1USAGE_TO_C1MASTER_TO_BSEG_TO_SA', (SELECT MATCH_COUNT FROM P11), 'D1_USAGE.D1_USAGE_ID -> C1_USAGE.MASTER_USAGE_ID -> C1_USAGE.BSEG_ID -> CI_BSEG.SA_ID' FROM DUAL
    UNION ALL SELECT 'P12_USID_TO_C1USAGE_TO_BSEG_TO_SA', (SELECT MATCH_COUNT FROM P12), 'D1_USAGE.US_ID -> C1_USAGE.USAGE_ID -> C1_USAGE.BSEG_ID -> CI_BSEG.SA_ID' FROM DUAL
)
SELECT
    PATH,
    MATCH_COUNT,
    CASE
        WHEN MATCH_COUNT = MAX(MATCH_COUNT) OVER () AND MATCH_COUNT > 0
            THEN NOTES || ' | TOP_MATCH_PATH'
        WHEN MATCH_COUNT = 0
            THEN NOTES || ' | NO_MATCH'
        ELSE NOTES
    END AS NOTES
FROM PATHS
ORDER BY MATCH_COUNT DESC, PATH;

-- 7C) Sample output for likely winner path: D1_USAGE -> C1_USAGE.BSEG_ID -> CI_BSEG.SA_ID
SELECT *
FROM (
    SELECT
        U.D1_USAGE_ID,
        U.US_ID,
        U.USG_EXT_ID,
        CU.USAGE_ID,
        CU.MASTER_USAGE_ID,
        CU.BSEG_ID,
        BS.SA_ID AS BSEG_SA_ID,
        CU.SA_ID,
        S.ACCT_ID,
        TRIM(U.MSRMT_CYC_CD) AS USAGE_MSRMT_CYC_CD,
        TRIM(NVL(B.BILL_CYC_CD, A.BILL_CYC_CD)) AS BILL_CYCLE_CODE,
        L.DESCR AS BILL_CYCLE_DESCRIPTION
    FROM CISADM.D1_USAGE U
    JOIN CISADM.C1_USAGE CU
      ON TRIM(U.D1_USAGE_ID) = TRIM(CU.USAGE_ID)
    JOIN CISADM.CI_BSEG BS
      ON TRIM(BS.BSEG_ID) = TRIM(CU.BSEG_ID)
    JOIN CISADM.CI_SA S
      ON TRIM(S.SA_ID) = TRIM(BS.SA_ID)
    LEFT JOIN CISADM.CI_BILL B
      ON TRIM(B.BILL_ID) = TRIM(BS.BILL_ID)
    LEFT JOIN CISADM.CI_ACCT A
      ON TRIM(A.ACCT_ID) = TRIM(S.ACCT_ID)
    LEFT JOIN CISADM.CI_BILL_CYC_L L
      ON TRIM(L.BILL_CYC_CD) = TRIM(NVL(B.BILL_CYC_CD, A.BILL_CYC_CD, U.MSRMT_CYC_CD))
     AND L.LANGUAGE_CD IN ('ENG', 'EN')
    ORDER BY U.START_DTTM DESC
)
WHERE ROWNUM <= 50;

-- =====================================================================
-- END OF SCRIPT
-- =====================================================================
