#!/usr/bin/env python3
"""
Generate read-only workstream table health SQL from physical workstream catalog.

Usage:
  python3 scripts/build_workstream_table_health_sql.py
"""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
PHYSICAL_CATALOG = ROOT / "output" / "workstream_physical_catalog.json"
WORKSTREAM_DICT = ROOT / "output" / "workstream_reporting_dictionary.json"
OUT_SQL = ROOT / "sql" / "diagnostics" / "cisadm_workstream_table_health.sql"


def _workstream_tables() -> list[str]:
    if PHYSICAL_CATALOG.exists():
        payload = json.loads(PHYSICAL_CATALOG.read_text(encoding="utf-8"))
        tables = set()
        for ws in (payload.get("workstreams") or {}).values():
            for t in ws.get("tables") or []:
                tables.add(t.upper())
        return sorted(tables)
    payload = json.loads(WORKSTREAM_DICT.read_text(encoding="utf-8"))
    return sorted(
        {
            table_name.upper()
            for ws_name, ws in payload.items()
            for table_name in ((ws or {}).get("tables") or {}).keys()
            if ws_name != "field_tasks"
        }
        | {
            table_name.upper()
            for table_name in ((payload.get("field_tasks") or {}).get("tables") or {}).keys()
        }
    )


def main() -> int:
    tables = _workstream_tables()
    lines = [
        "-- Generated by scripts/build_workstream_table_health_sql.py",
        "-- Read-only COUNT(*) for physical workstream tables (no custom views).",
        "-- Run: python3 scripts/local/run_client_oracle_sql.py --client demo --file sql/diagnostics/cisadm_workstream_table_health.sql",
        "",
    ]

    union_parts = []
    for table in tables:
        union_parts.append(
            f"SELECT '{table}' AS table_name, "
            f"(SELECT COUNT(*) FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = '{table}') AS table_exists, "
            f"CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE owner = 'CISADM' AND table_name = '{table}') "
            f"THEN (SELECT COUNT(*) FROM cisadm.{table.lower()}) ELSE NULL END AS row_count "
            f"FROM dual"
        )

    lines.append("\nUNION ALL\n".join(union_parts) + ";\n")
    OUT_SQL.parent.mkdir(parents=True, exist_ok=True)
    OUT_SQL.write_text("\n".join(lines), encoding="utf-8")
    print(f"[PASS] Health SQL written: {OUT_SQL} ({len(tables)} tables)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
