-- Purpose:
--   Trend of write-off process effectiveness over time.
--
-- Metric:
--   RECOVERY_RATE_EST = SUM(GREATEST(ARS_AT_START - ARS_AT_END, 0)) / SUM(ARS_AT_START)
--
-- Hard-coded date window:
--   Process start date >= DATE '2025-09-01'
--
-- Parameters:
--   :P_ONLY_COMPLETED      CHAR  -- 'Y' or 'N'
--   :P_ACCT_ID_LIST        VARCHAR2 -- optional comma-separated ACCT_ID list

WITH ACCT_FILTER AS (
  SELECT TRIM(REGEXP_SUBSTR(:P_ACCT_ID_LIST, '[^,]+', 1, LEVEL)) AS ACCT_ID
  FROM DUAL
  CONNECT BY REGEXP_SUBSTR(:P_ACCT_ID_LIST, '[^,]+', 1, LEVEL) IS NOT NULL
),
BASE AS (
  SELECT
    TRUNC(W.CRE_DTTM, 'MM') AS START_MONTH,
    NVL(W.ARS_AT_START, 0) AS ARS_AT_START,
    NVL(W.ARS_AT_END, 0) AS ARS_AT_END,
    W.WO_PROC_COMPL_DT
  FROM CISADM.C1_BI_WOPROC_VW W
  WHERE W.CRE_DTTM >= DATE '2025-09-01'
    AND (
      :P_ACCT_ID_LIST IS NULL
      OR TRIM(W.ACCT_ID) IN (SELECT AF.ACCT_ID FROM ACCT_FILTER AF)
    )
)
SELECT
  B.START_MONTH,
  COUNT(*) AS PROCESS_COUNT,
  SUM(B.ARS_AT_START) AS INIT_OUTSTANDING_AMT_TOTAL,
  SUM(B.ARS_AT_END) AS END_OUTSTANDING_AMT_TOTAL,
  SUM(GREATEST(B.ARS_AT_START - B.ARS_AT_END, 0)) AS AMOUNT_RECOVERED_EST,
  CASE
    WHEN SUM(B.ARS_AT_START) = 0 THEN 0
    ELSE ROUND(SUM(GREATEST(B.ARS_AT_START - B.ARS_AT_END, 0)) / SUM(B.ARS_AT_START), 6)
  END AS RECOVERY_RATE_EST
FROM BASE B
WHERE :P_ONLY_COMPLETED = 'N'
   OR B.WO_PROC_COMPL_DT IS NOT NULL
GROUP BY
  B.START_MONTH
ORDER BY
  B.START_MONTH
