-- Purpose:
--   Active write-off process count and initiated outstanding debt.
--
-- Hard-coded date window:
--   Process start date >= DATE '2025-09-01'
--
-- Parameters:
--   :P_ONLY_ACTIVE     CHAR  -- 'Y' or 'N'
--   :P_ACCT_ID_LIST    VARCHAR2 -- optional comma-separated ACCT_ID list

WITH ACCT_FILTER AS (
  SELECT TRIM(REGEXP_SUBSTR(:P_ACCT_ID_LIST, '[^,]+', 1, LEVEL)) AS ACCT_ID
  FROM DUAL
  CONNECT BY REGEXP_SUBSTR(:P_ACCT_ID_LIST, '[^,]+', 1, LEVEL) IS NOT NULL
),

BASE AS (
  SELECT
    W.UNCOLL_PROC_ID,
    W.ACCT_ID,
    W.CRE_DTTM AS START_DTTM,
    W.ARS_AT_START,
    W.WO_STATUS_FLG,
    W.UNCOLL_PROC_STAT_FLG,
    NVL(W.ACTIVE_WO_PROC_CNT, 0) AS ACTIVE_WO_PROC_CNT
  FROM CISADM.C1_BI_WOPROC_VW W
  WHERE W.CRE_DTTM >= DATE '2025-09-01'
    AND (
      :P_ACCT_ID_LIST IS NULL
      OR TRIM(W.ACCT_ID) IN (SELECT AF.ACCT_ID FROM ACCT_FILTER AF)
    )
)
SELECT
  COUNT(DISTINCT B.UNCOLL_PROC_ID) AS WRITE_OFF_PROCESS_COUNT,
  SUM(B.ACTIVE_WO_PROC_CNT) AS ACTIVE_WRITE_OFF_PROCESS_COUNT,
  SUM(NVL(B.ARS_AT_START, 0)) AS INIT_OUTSTANDING_AMT_TOTAL,
  AVG(NVL(B.ARS_AT_START, 0)) AS INIT_OUTSTANDING_AMT_AVG
FROM BASE B
WHERE :P_ONLY_ACTIVE = 'N'
   OR B.ACTIVE_WO_PROC_CNT > 0
