-- Purpose:
--   Detailed write-off rows for specific accounts.
--
-- Hard-coded date window:
--   Process start date >= DATE '2025-09-01'
--
-- Parameters:
--   :P_ACCT_ID_LIST    VARCHAR2 -- optional comma-separated ACCT_ID list

WITH ACCT_FILTER AS (
  SELECT TRIM(REGEXP_SUBSTR(:P_ACCT_ID_LIST, '[^,]+', 1, LEVEL)) AS ACCT_ID
  FROM DUAL
  CONNECT BY REGEXP_SUBSTR(:P_ACCT_ID_LIST, '[^,]+', 1, LEVEL) IS NOT NULL
)
SELECT
  W.UNCOLL_PROC_ID AS WRITE_OFF_PROCESS_ID,
  W.ACCT_ID,
  W.CRE_DTTM AS START_DTTM,
  W.WO_PROC_COMPL_DT,
  W.WO_STATUS_FLG,
  W.UNCOLL_PROC_STAT_FLG,
  W.WO_STAT_RSN_FLG,
  NVL(W.ARS_AT_START, 0) AS INIT_OUTSTANDING_AMT,
  NVL(W.ARS_AT_END, 0) AS END_OUTSTANDING_AMT,
  NVL(W.ARS_DIFF, 0) AS OUTSTANDING_DIFF_AMT,
  NVL(W.UNCOLL_PROC_DUR, 0) AS PROCESS_DURATION_DAYS,
  NVL(W.ACTIVE_WO_PROC_CNT, 0) AS ACTIVE_WO_PROC_CNT,
  NVL(W.COMPL_WO_PROC_CNT, 0) AS COMPL_WO_PROC_CNT
FROM CISADM.C1_BI_WOPROC_VW W
WHERE W.CRE_DTTM >= DATE '2025-09-01'
  AND (
    :P_ACCT_ID_LIST IS NULL
    OR TRIM(W.ACCT_ID) IN (SELECT AF.ACCT_ID FROM ACCT_FILTER AF)
  )
ORDER BY
  W.ACCT_ID,
  W.CRE_DTTM DESC,
  W.UNCOLL_PROC_ID;
