-- Purpose:
--   Trend of time-to-close for write-off processes.
--
-- Metric:
--   DAYS_TO_CLOSE = UNCOLL_PROC_DUR (source-provided duration)
--
-- Hard-coded date window:
--   Process start date >= DATE '2025-09-01'
--
-- Parameters:
--   :P_ONLY_CLOSED         CHAR  -- 'Y' or 'N'
--   :P_ACCT_ID_LIST        VARCHAR2 -- optional comma-separated ACCT_ID list

WITH ACCT_FILTER AS (
  SELECT TRIM(REGEXP_SUBSTR(:P_ACCT_ID_LIST, '[^,]+', 1, LEVEL)) AS ACCT_ID
  FROM DUAL
  CONNECT BY REGEXP_SUBSTR(:P_ACCT_ID_LIST, '[^,]+', 1, LEVEL) IS NOT NULL
),
BASE AS (
  SELECT
    TRUNC(W.CRE_DTTM, 'MM') AS START_MONTH,
    W.UNCOLL_PROC_DUR,
    W.WO_PROC_COMPL_DT
  FROM CISADM.C1_BI_WOPROC_VW W
  WHERE W.CRE_DTTM >= DATE '2025-09-01'
    AND (
      :P_ACCT_ID_LIST IS NULL
      OR TRIM(W.ACCT_ID) IN (SELECT AF.ACCT_ID FROM ACCT_FILTER AF)
    )
)
SELECT
  B.START_MONTH,
  COUNT(*) AS PROCESS_COUNT,
  AVG(B.UNCOLL_PROC_DUR) AS AVG_DAYS_TO_CLOSE,
  MEDIAN(B.UNCOLL_PROC_DUR) AS MEDIAN_DAYS_TO_CLOSE,
  MIN(B.UNCOLL_PROC_DUR) AS MIN_DAYS_TO_CLOSE,
  MAX(B.UNCOLL_PROC_DUR) AS MAX_DAYS_TO_CLOSE
FROM BASE B
WHERE B.UNCOLL_PROC_DUR IS NOT NULL
  AND (
    :P_ONLY_CLOSED = 'N'
    OR B.WO_PROC_COMPL_DT IS NOT NULL
  )
GROUP BY
  B.START_MONTH
ORDER BY
  B.START_MONTH
