-- Purpose:
--   Estimate post-initiation recovery using payments linked to process SAs.
--
-- Recovery logic (estimate):
--   1) Use write-off process start from C1_BI_WOPROC_VW.CRE_DTTM.
--   2) Link process to SAs via CI_COLL_PROC_SA.
--   3) Link SA payments via CI_PAY_SEG -> CI_PAY_TNDR -> CI_PAY_EVENT.
--   4) Include only payments with PAY_DT >= process start date.
--
-- Hard-coded date window:
--   Process start date >= DATE '2025-09-01'
--   Payment date >= DATE '2025-09-01'
--
-- Parameters:
--   :P_ACCT_ID_LIST    VARCHAR2 -- optional comma-separated ACCT_ID list

WITH ACCT_FILTER AS (
  SELECT TRIM(REGEXP_SUBSTR(:P_ACCT_ID_LIST, '[^,]+', 1, LEVEL)) AS ACCT_ID
  FROM DUAL
  CONNECT BY REGEXP_SUBSTR(:P_ACCT_ID_LIST, '[^,]+', 1, LEVEL) IS NOT NULL
),
WO_BASE AS (
  SELECT
    W.UNCOLL_PROC_ID AS COLL_PROC_ID,
    W.ACCT_ID,
    W.CRE_DTTM AS START_DTTM,
    NVL(W.ARS_AT_START, 0) AS INIT_OUTSTANDING_AMT
  FROM CISADM.C1_BI_WOPROC_VW W
  WHERE W.CRE_DTTM >= DATE '2025-09-01'
    AND (
      :P_ACCT_ID_LIST IS NULL
      OR TRIM(W.ACCT_ID) IN (SELECT AF.ACCT_ID FROM ACCT_FILTER AF)
    )
),
WO_SA AS (
  SELECT
    S.COLL_PROC_ID,
    S.SA_ID
  FROM CISADM.CI_COLL_PROC_SA S
),
PAY_SA AS (
  SELECT
    PS.SA_ID,
    PE.PAY_DT,
    NVL(PS.PAY_SEG_AMT, 0) AS PAY_SEG_AMT
  FROM CISADM.CI_PAY_SEG PS
  JOIN CISADM.CI_PAY_TNDR PT
    ON PT.PAY_TENDER_ID = PS.PAY_ID
  JOIN CISADM.CI_PAY_EVENT PE
    ON PE.PAY_EVENT_ID = PT.PAY_EVENT_ID
  WHERE PE.PAY_DT >= DATE '2025-09-01'
),
PROC_PAY AS (
  SELECT
    W.COLL_PROC_ID,
    W.ACCT_ID,
    W.START_DTTM,
    W.INIT_OUTSTANDING_AMT,
    SUM(
      CASE
        WHEN P.PAY_DT >= W.START_DTTM THEN P.PAY_SEG_AMT
        ELSE 0
      END
    ) AS AMOUNT_RECOVERED_EST
  FROM WO_BASE W
  LEFT JOIN WO_SA WS
    ON WS.COLL_PROC_ID = W.COLL_PROC_ID
  LEFT JOIN PAY_SA P
    ON P.SA_ID = WS.SA_ID
  GROUP BY
    W.COLL_PROC_ID,
    W.ACCT_ID,
    W.START_DTTM,
    W.INIT_OUTSTANDING_AMT
)
SELECT
  PP.COLL_PROC_ID,
  PP.ACCT_ID,
  PP.START_DTTM,
  PP.INIT_OUTSTANDING_AMT,
  NVL(PP.AMOUNT_RECOVERED_EST, 0) AS AMOUNT_RECOVERED_EST,
  CASE
    WHEN PP.INIT_OUTSTANDING_AMT = 0 THEN 0
    ELSE ROUND(NVL(PP.AMOUNT_RECOVERED_EST, 0) / PP.INIT_OUTSTANDING_AMT, 6)
  END AS RECOVERY_RATE_EST
FROM PROC_PAY PP
ORDER BY
  PP.START_DTTM,
  PP.COLL_PROC_ID
