-- Purpose:
--   Trend of write-off process creation counts and initiating debt.
--
-- Hard-coded date window:
--   Process start date >= DATE '2025-09-01'
--
-- Parameters:
--   :P_ACCT_ID_LIST    VARCHAR2 -- optional comma-separated ACCT_ID list

WITH ACCT_FILTER AS (
  SELECT TRIM(REGEXP_SUBSTR(:P_ACCT_ID_LIST, '[^,]+', 1, LEVEL)) AS ACCT_ID
  FROM DUAL
  CONNECT BY REGEXP_SUBSTR(:P_ACCT_ID_LIST, '[^,]+', 1, LEVEL) IS NOT NULL
)

SELECT
  TRUNC(W.CRE_DTTM, 'MM') AS START_MONTH,
  COUNT(DISTINCT W.UNCOLL_PROC_ID) AS WRITE_OFF_PROCESS_COUNT,
  SUM(NVL(W.ARS_AT_START, 0)) AS INIT_OUTSTANDING_AMT_TOTAL,
  AVG(NVL(W.ARS_AT_START, 0)) AS INIT_OUTSTANDING_AMT_AVG
FROM CISADM.C1_BI_WOPROC_VW W
WHERE W.CRE_DTTM >= DATE '2025-09-01'
  AND (
    :P_ACCT_ID_LIST IS NULL
    OR TRIM(W.ACCT_ID) IN (SELECT AF.ACCT_ID FROM ACCT_FILTER AF)
  )
GROUP BY
  TRUNC(W.CRE_DTTM, 'MM')
ORDER BY
  START_MONTH
