-- 1020-row smoke dataset: 10 meters + 1000 readings + 10 field work rows
DELETE FROM CISADM.FIELD_WORK_LOG WHERE CLIENT_ID = 'SMOKE_CITY_01' AND WORK_ID BETWEEN 900001 AND 900010;
DELETE FROM CISADM.METER_READINGS WHERE METER_ID BETWEEN 700001 AND 700010;
DELETE FROM CISADM.METERS WHERE CLIENT_ID = 'SMOKE_CITY_01' AND METER_ID BETWEEN 700001 AND 700010;

INSERT INTO CISADM.METERS (METER_ID, ADDRESS, LAT, LON, CLIENT_ID, SERVICE_POINT_ID, WORK_REGION)
SELECT 700000 + LEVEL, 'SMOKE ADDRESS ' || LEVEL, 40.70 + (LEVEL * 0.01), -74.00 - (LEVEL * 0.01), 'SMOKE_CITY_01', 880000 + LEVEL,
       CASE WHEN LEVEL <= 4 THEN 'NORTH' WHEN LEVEL <= 7 THEN 'CENTRAL' ELSE 'SOUTH' END
FROM DUAL CONNECT BY LEVEL <= 10;

INSERT INTO CISADM.METER_READINGS (METER_ID, READING_TS, READING_VALUE, LATITUDE, LONGITUDE, CITY)
SELECT 700000 + MOD(LEVEL - 1, 10) + 1,
       SYSTIMESTAMP - NUMTODSINTERVAL(MOD(LEVEL, 96), 'HOUR'),
       100 + (LEVEL * 0.05),
       40.70 + (MOD(LEVEL - 1, 10) + 1) * 0.01,
       -74.00 - (MOD(LEVEL - 1, 10) + 1) * 0.01,
       'SMOKE_CITY'
FROM DUAL CONNECT BY LEVEL <= 1000;

UPDATE CISADM.METER_READINGS
   SET READING_TS = SYSTIMESTAMP - NUMTODSINTERVAL(72, 'HOUR')
 WHERE METER_ID IN (700009, 700010)
   AND ROWNUM <= 20;

INSERT INTO CISADM.FIELD_WORK_LOG (WORK_ID, METER_ID, WORK_STATUS, ASSIGNED_DATE, COMPLETED_DATE, TECHNICIAN_ID, WORK_REGION, CLIENT_ID)
SELECT 900000 + LEVEL, 700000 + LEVEL,
       CASE WHEN LEVEL <= 4 THEN 'Assigned' WHEN LEVEL <= 7 THEN 'In Progress' ELSE 'Completed' END,
       SYSTIMESTAMP - NUMTODSINTERVAL(LEVEL * 2, 'HOUR'),
       CASE WHEN LEVEL >= 8 THEN SYSTIMESTAMP - NUMTODSINTERVAL(1, 'HOUR') END,
       'TECH_' || LEVEL,
       CASE WHEN LEVEL <= 4 THEN 'NORTH' WHEN LEVEL <= 7 THEN 'CENTRAL' ELSE 'SOUTH' END,
       'SMOKE_CITY_01'
FROM DUAL CONNECT BY LEVEL <= 10;

COMMIT;

SELECT
  (SELECT COUNT(*) FROM CISADM.METERS WHERE CLIENT_ID = 'SMOKE_CITY_01' AND METER_ID BETWEEN 700001 AND 700010) AS METERS_CNT,
  (SELECT COUNT(*) FROM CISADM.METER_READINGS WHERE METER_ID BETWEEN 700001 AND 700010) AS READINGS_CNT,
  (SELECT COUNT(*) FROM CISADM.FIELD_WORK_LOG WHERE CLIENT_ID = 'SMOKE_CITY_01' AND WORK_ID BETWEEN 900001 AND 900010) AS FIELDWORK_CNT
FROM DUAL;
