PROMPT ============================================================
PROMPT High-level client snapshot data quality checks
PROMPT ============================================================
PROMPT Coverage:
PROMPT   1) Row counts and load freshness for active 7 snapshots
PROMPT   2) Required field-name presence check
PROMPT   3) Null-rate checks for critical columns

PROMPT
PROMPT 1) Row counts and freshness
SELECT 'FT_RPT_CURR' AS table_name,
       COUNT(*) AS row_count,
       MIN(load_dttm) AS min_load_dttm,
       MAX(load_dttm) AS max_load_dttm
FROM cisadm.ft_rpt_curr
UNION ALL
SELECT 'BSEG_BILLED_USAGE_RPT_CURR',
       COUNT(*),
       MIN(load_dttm),
       MAX(load_dttm)
FROM cisadm.bseg_billed_usage_rpt_curr
UNION ALL
SELECT 'BSEG_SQ_USAGE_RPT_CURR',
       COUNT(*),
       MIN(load_dttm),
       MAX(load_dttm)
FROM cisadm.bseg_sq_usage_rpt_curr
UNION ALL
SELECT 'D1_MSRMT_RPT_CURR',
       COUNT(*),
       MIN(load_dttm),
       MAX(load_dttm)
FROM cisadm.d1_msrmt_rpt_curr
UNION ALL
SELECT 'FT_GL_DISTRIBUTION_RPT_CURR',
       COUNT(*),
       MIN(load_dttm),
       MAX(load_dttm)
FROM cisadm.ft_gl_distribution_rpt_curr
UNION ALL
SELECT 'D1_USAGE_RPT_CURR',
       COUNT(*),
       MIN(load_dttm),
       MAX(load_dttm)
FROM cisadm.d1_usage_rpt_curr
UNION ALL
SELECT 'D1_USAGE_SCALAR_DTL_RPT_CURR',
       COUNT(*),
       MIN(load_dttm),
       MAX(load_dttm)
FROM cisadm.d1_usage_scalar_dtl_rpt_curr;

PROMPT
PROMPT 2) Required field-name presence summary
WITH expected AS (
    SELECT 'FT_RPT_CURR' AS table_name, 'FT_ID' AS column_name FROM dual UNION ALL
    SELECT 'FT_RPT_CURR', 'ACCOUNTING_DT' FROM dual UNION ALL
    SELECT 'FT_RPT_CURR', 'LOAD_DTTM' FROM dual UNION ALL
    SELECT 'FT_RPT_CURR', 'CUR_AMT' FROM dual UNION ALL
    SELECT 'FT_RPT_CURR', 'TOT_AMT' FROM dual UNION ALL
    SELECT 'BSEG_BILLED_USAGE_RPT_CURR', 'BSEG_ID' FROM dual UNION ALL
    SELECT 'BSEG_BILLED_USAGE_RPT_CURR', 'BILL_DT' FROM dual UNION ALL
    SELECT 'BSEG_BILLED_USAGE_RPT_CURR', 'LOAD_DTTM' FROM dual UNION ALL
    SELECT 'BSEG_BILLED_USAGE_RPT_CURR', 'TOTAL_BILL_SQ' FROM dual UNION ALL
    SELECT 'BSEG_BILLED_USAGE_RPT_CURR', 'TOTAL_CALC_AMT' FROM dual UNION ALL
    SELECT 'BSEG_SQ_USAGE_RPT_CURR', 'BSEG_ID' FROM dual UNION ALL
    SELECT 'BSEG_SQ_USAGE_RPT_CURR', 'UOM_CD' FROM dual UNION ALL
    SELECT 'BSEG_SQ_USAGE_RPT_CURR', 'TOU_CD' FROM dual UNION ALL
    SELECT 'BSEG_SQ_USAGE_RPT_CURR', 'SQI_CD' FROM dual UNION ALL
    SELECT 'BSEG_SQ_USAGE_RPT_CURR', 'BILL_DT' FROM dual UNION ALL
    SELECT 'BSEG_SQ_USAGE_RPT_CURR', 'LOAD_DTTM' FROM dual UNION ALL
    SELECT 'D1_MSRMT_RPT_CURR', 'MEASR_COMP_ID' FROM dual UNION ALL
    SELECT 'D1_MSRMT_RPT_CURR', 'MSRMT_DTTM' FROM dual UNION ALL
    SELECT 'D1_MSRMT_RPT_CURR', 'LOAD_DTTM' FROM dual UNION ALL
    SELECT 'D1_MSRMT_RPT_CURR', 'MSRMT_VAL' FROM dual UNION ALL
    SELECT 'FT_GL_DISTRIBUTION_RPT_CURR', 'FT_ID' FROM dual UNION ALL
    SELECT 'FT_GL_DISTRIBUTION_RPT_CURR', 'GL_SEQ_NBR' FROM dual UNION ALL
    SELECT 'FT_GL_DISTRIBUTION_RPT_CURR', 'ACCOUNTING_DT' FROM dual UNION ALL
    SELECT 'FT_GL_DISTRIBUTION_RPT_CURR', 'LOAD_DTTM' FROM dual UNION ALL
    SELECT 'FT_GL_DISTRIBUTION_RPT_CURR', 'GL_AMOUNT' FROM dual UNION ALL
    SELECT 'D1_USAGE_RPT_CURR', 'D1_USAGE_ID' FROM dual UNION ALL
    SELECT 'D1_USAGE_RPT_CURR', 'START_DTTM' FROM dual UNION ALL
    SELECT 'D1_USAGE_RPT_CURR', 'USAGE_CRE_DTTM' FROM dual UNION ALL
    SELECT 'D1_USAGE_RPT_CURR', 'STATUS_UPD_DTTM' FROM dual UNION ALL
    SELECT 'D1_USAGE_RPT_CURR', 'LOAD_DTTM' FROM dual UNION ALL
    SELECT 'D1_USAGE_SCALAR_DTL_RPT_CURR', 'D1_USAGE_ID' FROM dual UNION ALL
    SELECT 'D1_USAGE_SCALAR_DTL_RPT_CURR', 'SEQ_NUM' FROM dual UNION ALL
    SELECT 'D1_USAGE_SCALAR_DTL_RPT_CURR', 'USAGE_START_DTTM' FROM dual UNION ALL
    SELECT 'D1_USAGE_SCALAR_DTL_RPT_CURR', 'USAGE_CRE_DTTM' FROM dual UNION ALL
    SELECT 'D1_USAGE_SCALAR_DTL_RPT_CURR', 'USAGE_STATUS_UPD_DTTM' FROM dual UNION ALL
    SELECT 'D1_USAGE_SCALAR_DTL_RPT_CURR', 'LOAD_DTTM' FROM dual UNION ALL
    SELECT 'D1_USAGE_SCALAR_DTL_RPT_CURR', 'QUANTITY' FROM dual UNION ALL
    SELECT 'D1_USAGE_SCALAR_DTL_RPT_CURR', 'FINAL_QUANTITY' FROM dual
)
SELECT e.table_name,
       COUNT(*) AS expected_columns,
       SUM(CASE WHEN c.column_name IS NOT NULL THEN 1 ELSE 0 END) AS present_columns,
       SUM(CASE WHEN c.column_name IS NULL THEN 1 ELSE 0 END) AS missing_columns
FROM expected e
LEFT JOIN all_tab_columns c
  ON c.owner = 'CISADM'
 AND c.table_name = e.table_name
 AND c.column_name = e.column_name
GROUP BY e.table_name
ORDER BY e.table_name;

PROMPT
PROMPT 2b) Required field names missing details (should return no rows)
WITH expected AS (
    SELECT 'FT_RPT_CURR' AS table_name, 'FT_ID' AS column_name FROM dual UNION ALL
    SELECT 'FT_RPT_CURR', 'ACCOUNTING_DT' FROM dual UNION ALL
    SELECT 'FT_RPT_CURR', 'LOAD_DTTM' FROM dual UNION ALL
    SELECT 'FT_RPT_CURR', 'CUR_AMT' FROM dual UNION ALL
    SELECT 'FT_RPT_CURR', 'TOT_AMT' FROM dual UNION ALL
    SELECT 'BSEG_BILLED_USAGE_RPT_CURR', 'BSEG_ID' FROM dual UNION ALL
    SELECT 'BSEG_BILLED_USAGE_RPT_CURR', 'BILL_DT' FROM dual UNION ALL
    SELECT 'BSEG_BILLED_USAGE_RPT_CURR', 'LOAD_DTTM' FROM dual UNION ALL
    SELECT 'BSEG_BILLED_USAGE_RPT_CURR', 'TOTAL_BILL_SQ' FROM dual UNION ALL
    SELECT 'BSEG_BILLED_USAGE_RPT_CURR', 'TOTAL_CALC_AMT' FROM dual UNION ALL
    SELECT 'BSEG_SQ_USAGE_RPT_CURR', 'BSEG_ID' FROM dual UNION ALL
    SELECT 'BSEG_SQ_USAGE_RPT_CURR', 'UOM_CD' FROM dual UNION ALL
    SELECT 'BSEG_SQ_USAGE_RPT_CURR', 'TOU_CD' FROM dual UNION ALL
    SELECT 'BSEG_SQ_USAGE_RPT_CURR', 'SQI_CD' FROM dual UNION ALL
    SELECT 'BSEG_SQ_USAGE_RPT_CURR', 'BILL_DT' FROM dual UNION ALL
    SELECT 'BSEG_SQ_USAGE_RPT_CURR', 'LOAD_DTTM' FROM dual UNION ALL
    SELECT 'D1_MSRMT_RPT_CURR', 'MEASR_COMP_ID' FROM dual UNION ALL
    SELECT 'D1_MSRMT_RPT_CURR', 'MSRMT_DTTM' FROM dual UNION ALL
    SELECT 'D1_MSRMT_RPT_CURR', 'LOAD_DTTM' FROM dual UNION ALL
    SELECT 'D1_MSRMT_RPT_CURR', 'MSRMT_VAL' FROM dual UNION ALL
    SELECT 'FT_GL_DISTRIBUTION_RPT_CURR', 'FT_ID' FROM dual UNION ALL
    SELECT 'FT_GL_DISTRIBUTION_RPT_CURR', 'GL_SEQ_NBR' FROM dual UNION ALL
    SELECT 'FT_GL_DISTRIBUTION_RPT_CURR', 'ACCOUNTING_DT' FROM dual UNION ALL
    SELECT 'FT_GL_DISTRIBUTION_RPT_CURR', 'LOAD_DTTM' FROM dual UNION ALL
    SELECT 'FT_GL_DISTRIBUTION_RPT_CURR', 'GL_AMOUNT' FROM dual UNION ALL
    SELECT 'D1_USAGE_RPT_CURR', 'D1_USAGE_ID' FROM dual UNION ALL
    SELECT 'D1_USAGE_RPT_CURR', 'START_DTTM' FROM dual UNION ALL
    SELECT 'D1_USAGE_RPT_CURR', 'USAGE_CRE_DTTM' FROM dual UNION ALL
    SELECT 'D1_USAGE_RPT_CURR', 'STATUS_UPD_DTTM' FROM dual UNION ALL
    SELECT 'D1_USAGE_RPT_CURR', 'LOAD_DTTM' FROM dual UNION ALL
    SELECT 'D1_USAGE_SCALAR_DTL_RPT_CURR', 'D1_USAGE_ID' FROM dual UNION ALL
    SELECT 'D1_USAGE_SCALAR_DTL_RPT_CURR', 'SEQ_NUM' FROM dual UNION ALL
    SELECT 'D1_USAGE_SCALAR_DTL_RPT_CURR', 'USAGE_START_DTTM' FROM dual UNION ALL
    SELECT 'D1_USAGE_SCALAR_DTL_RPT_CURR', 'USAGE_CRE_DTTM' FROM dual UNION ALL
    SELECT 'D1_USAGE_SCALAR_DTL_RPT_CURR', 'USAGE_STATUS_UPD_DTTM' FROM dual UNION ALL
    SELECT 'D1_USAGE_SCALAR_DTL_RPT_CURR', 'LOAD_DTTM' FROM dual UNION ALL
    SELECT 'D1_USAGE_SCALAR_DTL_RPT_CURR', 'QUANTITY' FROM dual UNION ALL
    SELECT 'D1_USAGE_SCALAR_DTL_RPT_CURR', 'FINAL_QUANTITY' FROM dual
)
SELECT e.table_name, e.column_name
FROM expected e
LEFT JOIN all_tab_columns c
  ON c.owner = 'CISADM'
 AND c.table_name = e.table_name
 AND c.column_name = e.column_name
WHERE c.column_name IS NULL
ORDER BY e.table_name, e.column_name;

PROMPT
PROMPT 3) Null-rate checks for critical fields
SELECT 'FT_RPT_CURR' AS table_name, 'FT_ID' AS column_name, COUNT(*) AS total_rows,
       SUM(CASE WHEN ft_id IS NULL THEN 1 ELSE 0 END) AS null_rows,
       ROUND(SUM(CASE WHEN ft_id IS NULL THEN 1 ELSE 0 END) * 100 / NULLIF(COUNT(*), 0), 4) AS null_pct
FROM cisadm.ft_rpt_curr
UNION ALL
SELECT 'FT_RPT_CURR', 'ACCOUNTING_DT', COUNT(*),
       SUM(CASE WHEN accounting_dt IS NULL THEN 1 ELSE 0 END),
       ROUND(SUM(CASE WHEN accounting_dt IS NULL THEN 1 ELSE 0 END) * 100 / NULLIF(COUNT(*), 0), 4)
FROM cisadm.ft_rpt_curr
UNION ALL
SELECT 'BSEG_BILLED_USAGE_RPT_CURR', 'BSEG_ID', COUNT(*),
       SUM(CASE WHEN bseg_id IS NULL THEN 1 ELSE 0 END),
       ROUND(SUM(CASE WHEN bseg_id IS NULL THEN 1 ELSE 0 END) * 100 / NULLIF(COUNT(*), 0), 4)
FROM cisadm.bseg_billed_usage_rpt_curr
UNION ALL
SELECT 'BSEG_BILLED_USAGE_RPT_CURR', 'BILL_DT', COUNT(*),
       SUM(CASE WHEN bill_dt IS NULL THEN 1 ELSE 0 END),
       ROUND(SUM(CASE WHEN bill_dt IS NULL THEN 1 ELSE 0 END) * 100 / NULLIF(COUNT(*), 0), 4)
FROM cisadm.bseg_billed_usage_rpt_curr
UNION ALL
SELECT 'BSEG_SQ_USAGE_RPT_CURR', 'BSEG_ID', COUNT(*),
       SUM(CASE WHEN bseg_id IS NULL THEN 1 ELSE 0 END),
       ROUND(SUM(CASE WHEN bseg_id IS NULL THEN 1 ELSE 0 END) * 100 / NULLIF(COUNT(*), 0), 4)
FROM cisadm.bseg_sq_usage_rpt_curr
UNION ALL
SELECT 'BSEG_SQ_USAGE_RPT_CURR', 'UOM_CD', COUNT(*),
       SUM(CASE WHEN uom_cd IS NULL THEN 1 ELSE 0 END),
       ROUND(SUM(CASE WHEN uom_cd IS NULL THEN 1 ELSE 0 END) * 100 / NULLIF(COUNT(*), 0), 4)
FROM cisadm.bseg_sq_usage_rpt_curr
UNION ALL
SELECT 'BSEG_SQ_USAGE_RPT_CURR', 'TOU_CD', COUNT(*),
       SUM(CASE WHEN tou_cd IS NULL THEN 1 ELSE 0 END),
       ROUND(SUM(CASE WHEN tou_cd IS NULL THEN 1 ELSE 0 END) * 100 / NULLIF(COUNT(*), 0), 4)
FROM cisadm.bseg_sq_usage_rpt_curr
UNION ALL
SELECT 'BSEG_SQ_USAGE_RPT_CURR', 'SQI_CD', COUNT(*),
       SUM(CASE WHEN sqi_cd IS NULL THEN 1 ELSE 0 END),
       ROUND(SUM(CASE WHEN sqi_cd IS NULL THEN 1 ELSE 0 END) * 100 / NULLIF(COUNT(*), 0), 4)
FROM cisadm.bseg_sq_usage_rpt_curr
UNION ALL
SELECT 'D1_MSRMT_RPT_CURR', 'MEASR_COMP_ID', COUNT(*),
       SUM(CASE WHEN measr_comp_id IS NULL THEN 1 ELSE 0 END),
       ROUND(SUM(CASE WHEN measr_comp_id IS NULL THEN 1 ELSE 0 END) * 100 / NULLIF(COUNT(*), 0), 4)
FROM cisadm.d1_msrmt_rpt_curr
UNION ALL
SELECT 'D1_MSRMT_RPT_CURR', 'MSRMT_DTTM', COUNT(*),
       SUM(CASE WHEN msrmt_dttm IS NULL THEN 1 ELSE 0 END),
       ROUND(SUM(CASE WHEN msrmt_dttm IS NULL THEN 1 ELSE 0 END) * 100 / NULLIF(COUNT(*), 0), 4)
FROM cisadm.d1_msrmt_rpt_curr
UNION ALL
SELECT 'FT_GL_DISTRIBUTION_RPT_CURR', 'FT_ID', COUNT(*),
       SUM(CASE WHEN ft_id IS NULL THEN 1 ELSE 0 END),
       ROUND(SUM(CASE WHEN ft_id IS NULL THEN 1 ELSE 0 END) * 100 / NULLIF(COUNT(*), 0), 4)
FROM cisadm.ft_gl_distribution_rpt_curr
UNION ALL
SELECT 'FT_GL_DISTRIBUTION_RPT_CURR', 'GL_SEQ_NBR', COUNT(*),
       SUM(CASE WHEN gl_seq_nbr IS NULL THEN 1 ELSE 0 END),
       ROUND(SUM(CASE WHEN gl_seq_nbr IS NULL THEN 1 ELSE 0 END) * 100 / NULLIF(COUNT(*), 0), 4)
FROM cisadm.ft_gl_distribution_rpt_curr
UNION ALL
SELECT 'D1_USAGE_RPT_CURR', 'D1_USAGE_ID', COUNT(*),
       SUM(CASE WHEN d1_usage_id IS NULL THEN 1 ELSE 0 END),
       ROUND(SUM(CASE WHEN d1_usage_id IS NULL THEN 1 ELSE 0 END) * 100 / NULLIF(COUNT(*), 0), 4)
FROM cisadm.d1_usage_rpt_curr
UNION ALL
SELECT 'D1_USAGE_RPT_CURR', 'DRIVER_ALL_NULL', COUNT(*),
       SUM(CASE WHEN start_dttm IS NULL AND usage_cre_dttm IS NULL AND status_upd_dttm IS NULL THEN 1 ELSE 0 END),
       ROUND(SUM(CASE WHEN start_dttm IS NULL AND usage_cre_dttm IS NULL AND status_upd_dttm IS NULL THEN 1 ELSE 0 END) * 100 / NULLIF(COUNT(*), 0), 4)
FROM cisadm.d1_usage_rpt_curr
UNION ALL
SELECT 'D1_USAGE_SCALAR_DTL_RPT_CURR', 'D1_USAGE_ID', COUNT(*),
       SUM(CASE WHEN d1_usage_id IS NULL THEN 1 ELSE 0 END),
       ROUND(SUM(CASE WHEN d1_usage_id IS NULL THEN 1 ELSE 0 END) * 100 / NULLIF(COUNT(*), 0), 4)
FROM cisadm.d1_usage_scalar_dtl_rpt_curr
UNION ALL
SELECT 'D1_USAGE_SCALAR_DTL_RPT_CURR', 'SEQ_NUM', COUNT(*),
       SUM(CASE WHEN seq_num IS NULL THEN 1 ELSE 0 END),
       ROUND(SUM(CASE WHEN seq_num IS NULL THEN 1 ELSE 0 END) * 100 / NULLIF(COUNT(*), 0), 4)
FROM cisadm.d1_usage_scalar_dtl_rpt_curr
UNION ALL
SELECT 'D1_USAGE_SCALAR_DTL_RPT_CURR', 'DRIVER_ALL_NULL', COUNT(*),
       SUM(CASE WHEN usage_start_dttm IS NULL AND usage_cre_dttm IS NULL AND usage_status_upd_dttm IS NULL THEN 1 ELSE 0 END),
       ROUND(SUM(CASE WHEN usage_start_dttm IS NULL AND usage_cre_dttm IS NULL AND usage_status_upd_dttm IS NULL THEN 1 ELSE 0 END) * 100 / NULLIF(COUNT(*), 0), 4)
FROM cisadm.d1_usage_scalar_dtl_rpt_curr
;
