-- bill_cycle_active_validation.sql
-- Validates summary and drilldown report counts for active SA/account scope.
-- Date window must match report queries.

WITH active_sa AS (
    SELECT
        SA.SA_ID,
        SA.ACCT_ID
    FROM CISADM.CI_SA SA
    WHERE NULLIF(TRIM(SA.SA_STATUS_FLG), '') = '20'
),
base_bseg AS (
    SELECT
        TRIM(S.BILL_CYC_CD) AS BILL_CYCLE_CODE,
        S.BILL_ID,
        S.BSEG_ID,
        S.SA_ID
    FROM CISADM.CI_BSEG S
    WHERE TRIM(S.BILL_CYC_CD) IS NOT NULL
      AND S.CRE_DTTM >= DATE '2024-01-01'
      AND S.CRE_DTTM <  DATE '2026-01-01'
),
eligible_bseg AS (
    SELECT
        B.BILL_CYCLE_CODE,
        B.BILL_ID,
        B.BSEG_ID,
        B.SA_ID,
        A.ACCT_ID
    FROM base_bseg B
    JOIN active_sa A
      ON A.SA_ID = B.SA_ID
),
summary_counts AS (
    SELECT
        E.BILL_CYCLE_CODE,
        COUNT(*) AS SUMMARY_BILL_SEGMENT_COUNT,
        COUNT(DISTINCT E.BILL_ID) AS SUMMARY_BILL_COUNT,
        COUNT(DISTINCT E.SA_ID) AS SUMMARY_ACTIVE_SA_COUNT,
        COUNT(DISTINCT E.ACCT_ID) AS SUMMARY_ACTIVE_ACCOUNT_COUNT
    FROM eligible_bseg E
    GROUP BY E.BILL_CYCLE_CODE
),
drilldown_counts AS (
    SELECT
        E.BILL_CYCLE_CODE,
        COUNT(*) AS DRILL_BILL_SEGMENT_COUNT,
        COUNT(DISTINCT E.BILL_ID) AS DRILL_BILL_COUNT,
        COUNT(DISTINCT E.SA_ID) AS DRILL_ACTIVE_SA_COUNT,
        COUNT(DISTINCT E.ACCT_ID) AS DRILL_ACTIVE_ACCOUNT_COUNT
    FROM eligible_bseg E
    GROUP BY E.BILL_CYCLE_CODE
),
all_cycles AS (
    SELECT BILL_CYCLE_CODE FROM summary_counts
    UNION
    SELECT BILL_CYCLE_CODE FROM drilldown_counts
)
SELECT
    C.BILL_CYCLE_CODE,
    NVL(S.SUMMARY_BILL_SEGMENT_COUNT, 0) AS SUMMARY_BILL_SEGMENT_COUNT,
    NVL(D.DRILL_BILL_SEGMENT_COUNT, 0) AS DRILL_BILL_SEGMENT_COUNT,
    NVL(S.SUMMARY_BILL_SEGMENT_COUNT, 0) - NVL(D.DRILL_BILL_SEGMENT_COUNT, 0) AS DELTA_BILL_SEGMENT_COUNT,
    NVL(S.SUMMARY_BILL_COUNT, 0) AS SUMMARY_BILL_COUNT,
    NVL(D.DRILL_BILL_COUNT, 0) AS DRILL_BILL_COUNT,
    NVL(S.SUMMARY_BILL_COUNT, 0) - NVL(D.DRILL_BILL_COUNT, 0) AS DELTA_BILL_COUNT,
    NVL(S.SUMMARY_ACTIVE_SA_COUNT, 0) AS SUMMARY_ACTIVE_SA_COUNT,
    NVL(D.DRILL_ACTIVE_SA_COUNT, 0) AS DRILL_ACTIVE_SA_COUNT,
    NVL(S.SUMMARY_ACTIVE_SA_COUNT, 0) - NVL(D.DRILL_ACTIVE_SA_COUNT, 0) AS DELTA_ACTIVE_SA_COUNT,
    NVL(S.SUMMARY_ACTIVE_ACCOUNT_COUNT, 0) AS SUMMARY_ACTIVE_ACCOUNT_COUNT,
    NVL(D.DRILL_ACTIVE_ACCOUNT_COUNT, 0) AS DRILL_ACTIVE_ACCOUNT_COUNT,
    NVL(S.SUMMARY_ACTIVE_ACCOUNT_COUNT, 0) - NVL(D.DRILL_ACTIVE_ACCOUNT_COUNT, 0) AS DELTA_ACTIVE_ACCOUNT_COUNT,
    CASE
        WHEN NVL(S.SUMMARY_BILL_SEGMENT_COUNT, 0) = NVL(D.DRILL_BILL_SEGMENT_COUNT, 0)
         AND NVL(S.SUMMARY_BILL_COUNT, 0) = NVL(D.DRILL_BILL_COUNT, 0)
         AND NVL(S.SUMMARY_ACTIVE_SA_COUNT, 0) = NVL(D.DRILL_ACTIVE_SA_COUNT, 0)
         AND NVL(S.SUMMARY_ACTIVE_ACCOUNT_COUNT, 0) = NVL(D.DRILL_ACTIVE_ACCOUNT_COUNT, 0)
        THEN 'PASS'
        ELSE 'FAIL'
    END AS VALIDATION_STATUS
FROM all_cycles C
LEFT JOIN summary_counts S
  ON S.BILL_CYCLE_CODE = C.BILL_CYCLE_CODE
LEFT JOIN drilldown_counts D
  ON D.BILL_CYCLE_CODE = C.BILL_CYCLE_CODE
ORDER BY C.BILL_CYCLE_CODE;

