SELECT
  X.BILL_CYCLE_CODE,
  X.BILL_CYCLE_DESCRIPTION,
  COUNT(*) AS BILL_SEGMENT_COUNT,
  COUNT(DISTINCT X.BILL_ID) AS BILL_COUNT,
  COUNT(DISTINCT X.SA_ID) AS ACTIVE_SERVICE_AGREEMENT_COUNT,
  COUNT(DISTINCT X.ACCT_ID) AS ACTIVE_ACCOUNT_COUNT,
  MIN(X.EVENT_DATE) AS FIRST_BILL_DATE,
  MAX(X.EVENT_DATE) AS LAST_BILL_DATE,
  CASE
    WHEN MAX(X.CYCLE_LAST_EVENT_DATE) = MAX(MAX(X.CYCLE_LAST_EVENT_DATE)) OVER () THEN 'Y'
    ELSE 'N'
  END AS MOST_RECENT_BILL_CYCLE_SW,
  CASE
    WHEN MAX(X.CYCLE_LAST_EVENT_DATE) = MAX(MAX(X.CYCLE_LAST_EVENT_DATE)) OVER () THEN 'Y'
    ELSE 'N'
  END AS GLOBAL_MOST_RECENT_CYCLE_SW
FROM (
  SELECT
    NULLIF(TRIM(S.BILL_CYC_CD), '') AS BILL_CYCLE_CODE,
    NVL(L.BILL_CYCLE_DESCRIPTION, 'Cycle ' || NULLIF(TRIM(S.BILL_CYC_CD), '')) AS BILL_CYCLE_DESCRIPTION,
    S.BILL_ID,
    S.SA_ID,
    SA.ACCT_ID,
    TRUNC(NVL(B.BILL_DT, S.CRE_DTTM)) AS EVENT_DATE,
    MAX(TRUNC(NVL(B.BILL_DT, S.CRE_DTTM))) OVER (PARTITION BY NULLIF(TRIM(S.BILL_CYC_CD), '')) AS CYCLE_LAST_EVENT_DATE
  FROM CISADM.CI_BSEG S
  JOIN CISADM.CI_SA SA
    ON SA.SA_ID = S.SA_ID
   AND SA.SA_STATUS_FLG = '20'
  LEFT JOIN CISADM.CI_BILL B
    ON B.BILL_ID = S.BILL_ID
  LEFT JOIN (
    SELECT
      BILL_CYC_CD AS BILL_CYCLE_CODE,
      MAX(DESCR) AS BILL_CYCLE_DESCRIPTION
    FROM CISADM.CI_BILL_CYC_L
    WHERE LANGUAGE_CD IN ('ENG', 'EN')
    GROUP BY BILL_CYC_CD
  ) L
    ON L.BILL_CYCLE_CODE = NULLIF(TRIM(S.BILL_CYC_CD), '')
  WHERE NULLIF(TRIM(S.BILL_CYC_CD), '') IS NOT NULL
) X
WHERE X.EVENT_DATE = X.CYCLE_LAST_EVENT_DATE
GROUP BY
  X.BILL_CYCLE_CODE,
  X.BILL_CYCLE_DESCRIPTION
