SELECT
  E.BILL_CYCLE_CODE,
  E.BILL_CYCLE_DESCRIPTION,
  E.EXPECTED_ACTIVE_SA_COUNT,
  E.EXPECTED_ACTIVE_ACCOUNT_COUNT,
  NVL(A.ACTUAL_BILLED_SA_COUNT, 0) AS ACTUAL_BILLED_SA_COUNT,
  NVL(A.ACTUAL_BILLED_ACCOUNT_COUNT, 0) AS ACTUAL_BILLED_ACCOUNT_COUNT,
  NVL(A.ACTUAL_BILL_SEGMENT_COUNT, 0) AS ACTUAL_BILL_SEGMENT_COUNT,
  NVL(A.ACTUAL_BILL_COUNT, 0) AS ACTUAL_BILL_COUNT,
  E.EXPECTED_ACTIVE_SA_COUNT - NVL(A.ACTUAL_BILLED_SA_COUNT, 0) AS MISSING_ACTIVE_SA_COUNT,
  E.EXPECTED_ACTIVE_ACCOUNT_COUNT - NVL(A.ACTUAL_BILLED_ACCOUNT_COUNT, 0) AS MISSING_ACTIVE_ACCOUNT_COUNT,
  ROUND(
    100 * NVL(A.ACTUAL_BILLED_SA_COUNT, 0) / NULLIF(E.EXPECTED_ACTIVE_SA_COUNT, 0),
    2
  ) AS SA_COMPLETION_PCT,
  A.CYCLE_LAST_EVENT_DATE,
  CASE
    WHEN A.CYCLE_LAST_EVENT_DATE = MAX(A.CYCLE_LAST_EVENT_DATE) OVER () THEN 'Y'
    ELSE 'N'
  END AS MOST_RECENT_BILL_CYCLE_SW
FROM (
  SELECT
    NULLIF(TRIM(AC.BILL_CYC_CD), '') AS BILL_CYCLE_CODE,
    NVL(L.DESCR, 'Cycle ' || NULLIF(TRIM(AC.BILL_CYC_CD), '')) AS BILL_CYCLE_DESCRIPTION,
    COUNT(DISTINCT SA.SA_ID) AS EXPECTED_ACTIVE_SA_COUNT,
    COUNT(DISTINCT SA.ACCT_ID) AS EXPECTED_ACTIVE_ACCOUNT_COUNT
  FROM CISADM.CI_SA SA
  JOIN CISADM.CI_ACCT AC
    ON AC.ACCT_ID = SA.ACCT_ID
  LEFT JOIN (
    SELECT
      BILL_CYC_CD AS BILL_CYCLE_CODE,
      MAX(DESCR) AS DESCR
    FROM CISADM.CI_BILL_CYC_L
    WHERE LANGUAGE_CD IN ('ENG', 'EN')
    GROUP BY BILL_CYC_CD
  ) L
    ON L.BILL_CYCLE_CODE = NULLIF(TRIM(AC.BILL_CYC_CD), '')
  WHERE SA.SA_STATUS_FLG = '20'
    AND NULLIF(TRIM(AC.BILL_CYC_CD), '') IS NOT NULL
  GROUP BY NULLIF(TRIM(AC.BILL_CYC_CD), ''), NVL(L.DESCR, 'Cycle ' || NULLIF(TRIM(AC.BILL_CYC_CD), ''))
) E
LEFT JOIN (
  SELECT
    X.BILL_CYCLE_CODE,
    COUNT(*) AS ACTUAL_BILL_SEGMENT_COUNT,
    COUNT(DISTINCT X.BILL_ID) AS ACTUAL_BILL_COUNT,
    COUNT(DISTINCT X.SA_ID) AS ACTUAL_BILLED_SA_COUNT,
    COUNT(DISTINCT X.ACCT_ID) AS ACTUAL_BILLED_ACCOUNT_COUNT,
    MAX(X.CYCLE_LAST_EVENT_DATE) AS CYCLE_LAST_EVENT_DATE
  FROM (
    SELECT
      NULLIF(TRIM(S.BILL_CYC_CD), '') AS BILL_CYCLE_CODE,
      S.BILL_ID,
      S.SA_ID,
      SA.ACCT_ID,
      TRUNC(NVL(B.BILL_DT, S.CRE_DTTM)) AS EVENT_DATE,
      MAX(TRUNC(NVL(B.BILL_DT, S.CRE_DTTM))) OVER (PARTITION BY NULLIF(TRIM(S.BILL_CYC_CD), '')) AS CYCLE_LAST_EVENT_DATE
    FROM CISADM.CI_BSEG S
    JOIN CISADM.CI_SA SA
      ON SA.SA_ID = S.SA_ID
     AND SA.SA_STATUS_FLG = '20'
    LEFT JOIN CISADM.CI_BILL B
      ON B.BILL_ID = S.BILL_ID
    WHERE NULLIF(TRIM(S.BILL_CYC_CD), '') IS NOT NULL
  ) X
  WHERE X.EVENT_DATE = X.CYCLE_LAST_EVENT_DATE
  GROUP BY X.BILL_CYCLE_CODE
) A
  ON A.BILL_CYCLE_CODE = E.BILL_CYCLE_CODE
ORDER BY E.BILL_CYCLE_CODE
