SELECT
  X.BILL_CYCLE_CODE,
  NVL(C.BILL_CYCLE_DESCRIPTION, 'Cycle ' || X.BILL_CYCLE_CODE) AS BILL_CYCLE_DESCRIPTION,
  X.ACCT_ID AS ACCOUNT_ID,
  X.SA_ID AS SERVICE_AGREEMENT_ID,
  X.PREM_ID AS PREMISE_ID,
  X.BILL_ID,
  X.BSEG_ID AS BILL_SEGMENT_ID,
  X.BILL_DATE,
  X.BILL_CREATE_DATE,
  X.BSEG_CREATE_DATE,
  X.BILL_STAT_FLG AS BILL_STATUS_CODE,
  NVL(BS.STATUS_DESCRIPTION, 'BILL_STATUS_' || X.BILL_STAT_FLG) AS BILL_STATUS_DESCRIPTION,
  X.BSEG_STAT_FLG AS BSEG_STATUS_CODE,
  NVL(SS.STATUS_DESCRIPTION, 'BSEG_STATUS_' || X.BSEG_STAT_FLG) AS BSEG_STATUS_DESCRIPTION,
  CASE
    WHEN REGEXP_LIKE(UPPER(NVL(SS.STATUS_DESCRIPTION, '')), 'ERROR|EXCEPTION|FAIL|CANCEL')
      OR REGEXP_LIKE(UPPER(NVL(BS.STATUS_DESCRIPTION, '')), 'ERROR|EXCEPTION|FAIL|CANCEL')
    THEN 'Y'
    ELSE 'N'
  END AS IS_ERROR_SW,
  CASE
    WHEN REGEXP_LIKE(UPPER(NVL(SS.STATUS_DESCRIPTION, '')), 'ERROR|EXCEPTION|FAIL|CANCEL')
    THEN SS.STATUS_DESCRIPTION
    WHEN REGEXP_LIKE(UPPER(NVL(BS.STATUS_DESCRIPTION, '')), 'ERROR|EXCEPTION|FAIL|CANCEL')
    THEN BS.STATUS_DESCRIPTION
    ELSE NULL
  END AS ERROR_REASON,
  X.EVENT_DATE,
  X.CYCLE_LAST_EVENT_DATE,
  CASE
    WHEN X.CYCLE_LAST_EVENT_DATE = MAX(X.CYCLE_LAST_EVENT_DATE) OVER () THEN 'Y'
    ELSE 'N'
  END AS MOST_RECENT_BILL_CYCLE_SW
FROM (
  SELECT
    NULLIF(TRIM(S.BILL_CYC_CD), '') AS BILL_CYCLE_CODE,
    SA.ACCT_ID,
    S.SA_ID,
    S.PREM_ID,
    S.BILL_ID,
    S.BSEG_ID,
    B.BILL_STAT_FLG,
    S.BSEG_STAT_FLG,
    TRUNC(B.BILL_DT) AS BILL_DATE,
    TRUNC(B.CRE_DTTM) AS BILL_CREATE_DATE,
    TRUNC(S.CRE_DTTM) AS BSEG_CREATE_DATE,
    TRUNC(NVL(B.BILL_DT, S.CRE_DTTM)) AS EVENT_DATE,
    MAX(TRUNC(NVL(B.BILL_DT, S.CRE_DTTM))) OVER (PARTITION BY NULLIF(TRIM(S.BILL_CYC_CD), '')) AS CYCLE_LAST_EVENT_DATE
  FROM CISADM.CI_BSEG S
  JOIN CISADM.CI_SA SA
    ON SA.SA_ID = S.SA_ID
   AND SA.SA_STATUS_FLG = '20'
  LEFT JOIN CISADM.CI_BILL B
    ON B.BILL_ID = S.BILL_ID
  WHERE NULLIF(TRIM(S.BILL_CYC_CD), '') IS NOT NULL
    AND S.CRE_DTTM >= DATE '2024-01-01'
    AND S.CRE_DTTM <  DATE '2026-01-01'
) X
LEFT JOIN (
  SELECT BILL_CYC_CD, MAX(DESCR) AS BILL_CYCLE_DESCRIPTION
  FROM CISADM.CI_BILL_CYC_L
  WHERE LANGUAGE_CD IN ('ENG', 'EN')
  GROUP BY BILL_CYC_CD
) C
  ON C.BILL_CYC_CD = X.BILL_CYCLE_CODE
LEFT JOIN (
  SELECT FIELD_VALUE AS STATUS_CODE, MAX(DESCR) AS STATUS_DESCRIPTION
  FROM CISADM.CI_LOOKUP_VAL_L
  WHERE FIELD_NAME = 'BILL_STAT_FLG'
    AND LANGUAGE_CD = 'ENG'
  GROUP BY FIELD_VALUE
) BS
  ON BS.STATUS_CODE = X.BILL_STAT_FLG
LEFT JOIN (
  SELECT FIELD_VALUE AS STATUS_CODE, MAX(DESCR) AS STATUS_DESCRIPTION
  FROM CISADM.CI_LOOKUP_VAL_L
  WHERE FIELD_NAME = 'BSEG_STAT_FLG'
    AND LANGUAGE_CD = 'ENG'
  GROUP BY FIELD_VALUE
) SS
  ON SS.STATUS_CODE = X.BSEG_STAT_FLG
WHERE X.EVENT_DATE = X.CYCLE_LAST_EVENT_DATE
