SELECT
  X.BILL_CYCLE_CODE,
  X.ACCT_ID AS ACCOUNT_ID,
  X.SA_ID AS SERVICE_AGREEMENT_ID,
  X.BILL_ID,
  X.BSEG_ID AS BILL_SEGMENT_ID,
  X.BILL_STAT_FLG AS BILL_STATUS_CODE,
  X.BSEG_STAT_FLG AS BSEG_STATUS_CODE,
  X.EVENT_DATE,
  X.CYCLE_LAST_EVENT_DATE,
  CASE
    WHEN X.CYCLE_LAST_EVENT_DATE = MAX(X.CYCLE_LAST_EVENT_DATE) OVER () THEN 'Y'
    ELSE 'N'
  END AS MOST_RECENT_BILL_CYCLE_SW
FROM (
  SELECT
    NULLIF(TRIM(S.BILL_CYC_CD), '') AS BILL_CYCLE_CODE,
    SA.ACCT_ID,
    S.SA_ID,
    S.BILL_ID,
    S.BSEG_ID,
    B.BILL_STAT_FLG,
    S.BSEG_STAT_FLG,
    TRUNC(NVL(B.BILL_DT, S.CRE_DTTM)) AS EVENT_DATE,
    MAX(TRUNC(NVL(B.BILL_DT, S.CRE_DTTM))) OVER (PARTITION BY NULLIF(TRIM(S.BILL_CYC_CD), '')) AS CYCLE_LAST_EVENT_DATE
  FROM CISADM.CI_BSEG S
  JOIN CISADM.CI_SA SA
    ON SA.SA_ID = S.SA_ID
   AND SA.SA_STATUS_FLG = '20'
  LEFT JOIN CISADM.CI_BILL B
    ON B.BILL_ID = S.BILL_ID
  WHERE NULLIF(TRIM(S.BILL_CYC_CD), '') IS NOT NULL
    AND S.CRE_DTTM >= DATE '2024-01-01'
    AND S.CRE_DTTM <  DATE '2026-01-01'
) X
WHERE X.EVENT_DATE = X.CYCLE_LAST_EVENT_DATE
