CREATE TABLE cisadm.bseg_sq_usage_rpt_curr (
    -- Core billed-usage determinant grain
    bseg_id                           VARCHAR2(30)    NOT NULL,
    uom_cd                            VARCHAR2(30),
    uom_desc                          VARCHAR2(100),
    tou_cd                            VARCHAR2(30),
    tou_desc                          VARCHAR2(100),
    sqi_cd                            VARCHAR2(30),
    sqi_desc                          VARCHAR2(100),
    sq_line_count                     NUMBER(18,0),
    bseg_determinant_count            NUMBER(18,0),
    total_init_sq                     NUMBER(22,6),
    total_bill_sq                     NUMBER(22,6),
    load_dttm                         TIMESTAMP DEFAULT SYSTIMESTAMP,
    -- Bill and segment context
    bill_id                           VARCHAR2(30),
    acct_id                           VARCHAR2(30),
    customer_name                     VARCHAR2(200),
    sa_id                             VARCHAR2(30),
    sa_type_cd                        VARCHAR2(30),
    sa_type_desc                      VARCHAR2(100),
    utility_type_cd                   VARCHAR2(10),
    prem_id                           VARCHAR2(30),
    bseg_stat_flg                     VARCHAR2(10),
    bseg_stat_desc                    VARCHAR2(100),
    bill_stat_flg                     VARCHAR2(10),
    bill_stat_desc                    VARCHAR2(100),
    bill_dt                           DATE,
    due_dt                            DATE,
    bseg_start_dt                     DATE,
    bseg_end_dt                       DATE,
    win_start_dt                      DATE,
    bseg_bill_cyc_cd                  VARCHAR2(10),
    bseg_bill_cyc_desc                VARCHAR2(100),
    bill_bill_cyc_cd                  VARCHAR2(10),
    bill_bill_cyc_desc                VARCHAR2(100),
    -- Account classification context
    cust_cl_cd                        VARCHAR2(10),
    cust_cl_desc                      VARCHAR2(100),
    coll_cl_cd                        VARCHAR2(10),
    coll_cl_desc                      VARCHAR2(100),
    acct_mgmt_grp_cd                  VARCHAR2(10),
    acct_mgmt_grp_desc                VARCHAR2(100),
    bud_plan_cd                       VARCHAR2(10),
    bud_plan_desc                     VARCHAR2(100),
    -- Segment detail flags
    est_sw                            VARCHAR2(5),
    closing_bseg_sw                   VARCHAR2(5),
    sq_override_sw                    VARCHAR2(5),
    item_override_sw                  VARCHAR2(5),
    can_rsn_cd                        VARCHAR2(10),
    can_rsn_desc                      VARCHAR2(100),
    rebill_seg_id                     VARCHAR2(30),
    can_bseg_id                       VARCHAR2(30),
    master_bseg_id                    VARCHAR2(30)
);
