-- Bind variables: :CLIENT_ID, :START_TS, :END_TS, :REGION
EXPLAIN PLAN FOR
SELECT
    FW.WORK_REGION AS REGION,
    COUNT(*) AS OPEN_WORK_COUNT,
    COUNT(DISTINCT FW.METER_ID) AS DISTINCT_METERS,
    MIN(FW.ASSIGNED_DATE) AS EARLIEST_ASSIGNED_DATE,
    MAX(FW.ASSIGNED_DATE) AS LATEST_ASSIGNED_DATE
FROM CISADM.FIELD_WORK_LOG FW
WHERE FW.WORK_STATUS IN ('Assigned', 'In Progress')
  AND FW.ASSIGNED_DATE >= :START_TS
  AND FW.ASSIGNED_DATE <  :END_TS
  AND FW.CLIENT_ID = :CLIENT_ID
  AND (:REGION IS NULL OR FW.WORK_REGION = :REGION)
GROUP BY FW.WORK_REGION
ORDER BY OPEN_WORK_COUNT DESC, REGION;

SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY(NULL, NULL, 'ALL +PREDICATE +PEEKED_BINDS'));

-- Index recommendations
-- CREATE INDEX CISADM.IDX_FWL_CLIENT_STATUS_ASSIGNED
--   ON CISADM.FIELD_WORK_LOG (CLIENT_ID, WORK_STATUS, ASSIGNED_DATE, WORK_REGION, METER_ID);

-- Rollback
-- DROP INDEX CISADM.IDX_FWL_CLIENT_STATUS_ASSIGNED;
