-- GOVERNED: Strategic Arrears Summary (for AI pipeline)
-- Source: Working file.sql / Age of all Bills & Adjustment FTs.sql
-- Used by: pipeline/fetch_usage.py (QUERY_ARREARS_STRATEGIC)
-- Value: Identifies debt aging risk; key metrics for Arrearage Narrative
-- Filters: Active SAs only (SA_STATUS_FLG='20'); outstanding balance only (ARS_DT NOT NULL, HAVING SUM>0).

SELECT
    ACCNT.ACCT_ID,
    ST.DEBT_CL_CD,
    NULLIF(TRIM(DCL.DESCR), '') AS DEBT_CL_DESCR,
    SUM(FT.CUR_AMT) AS TOTAL_DEBT,
    SUM(CASE WHEN (TRUNC(SYSDATE) - FT.ARS_DT) <= 30 THEN FT.CUR_AMT ELSE 0 END) AS DEBT_30_DAYS,
    SUM(CASE WHEN (TRUNC(SYSDATE) - FT.ARS_DT) BETWEEN 31 AND 60 THEN FT.CUR_AMT ELSE 0 END) AS DEBT_60_DAYS,
    SUM(CASE WHEN (TRUNC(SYSDATE) - FT.ARS_DT) > 60 THEN FT.CUR_AMT ELSE 0 END) AS DEBT_OVER_60,
    COUNT(CASE WHEN FT.CUR_AMT > 500 THEN 1 END) AS LARGE_BILL_COUNT
FROM CISADM.CI_FT FT
JOIN CISADM.CI_SA SA ON SA.SA_ID = FT.SA_ID
JOIN CISADM.CI_SA_TYPE ST ON SA.SA_TYPE_CD = ST.SA_TYPE_CD
LEFT JOIN CISADM.CI_DEBT_CL_L DCL
  ON DCL.DEBT_CL_CD = ST.DEBT_CL_CD
 AND DCL.LANGUAGE_CD = 'EN'
JOIN CISADM.CI_ACCT ACCNT ON SA.ACCT_ID = ACCNT.ACCT_ID
WHERE FT.FREEZE_SW = 'Y'
  AND FT.NOT_IN_ARS_SW = 'N'
  AND FT.FT_TYPE_FLG NOT IN ('PS', 'PX')
  AND FT.ARS_DT IS NOT NULL
  AND NULLIF(TRIM(SA.SA_STATUS_FLG), '') = '20'
GROUP BY ACCNT.ACCT_ID, ST.DEBT_CL_CD, DCL.DESCR
HAVING SUM(FT.CUR_AMT) > 0;
