-- GOVERNED: Collections Prioritization (Jaspersoft-ready, read-only)
-- Purpose: rank accounts for outreach based on aged debt + active alerts.
-- Binds:
--   :client_id          VARCHAR2 (optional; maps to CI_ACCT.CIS_DIVISION)
--   :start_ts           TIMESTAMP
--   :end_ts             TIMESTAMP
--   :min_debt_over_60   NUMBER (optional; defaults to 0)

SELECT
    A.ACCT_ID,
    NULLIF(TRIM(A.COLL_CL_CD), '') AS COLL_CL_CD,
    NULLIF(TRIM(COLL_L.DESCR), '') AS COLL_CL_DESCR,
    SUM(CASE WHEN (TRUNC(:end_ts) - FT.ARS_DT) <= 30 THEN FT.CUR_AMT ELSE 0 END) AS DEBT_30_DAYS,
    SUM(CASE WHEN (TRUNC(:end_ts) - FT.ARS_DT) BETWEEN 31 AND 60 THEN FT.CUR_AMT ELSE 0 END) AS DEBT_60_DAYS,
    SUM(CASE WHEN (TRUNC(:end_ts) - FT.ARS_DT) > 60 THEN FT.CUR_AMT ELSE 0 END) AS DEBT_OVER_60,
    SUM(FT.CUR_AMT) AS TOTAL_DEBT,
    COUNT(DISTINCT CASE WHEN AL.ALERT_TYPE_CD IS NOT NULL THEN AL.ALERT_TYPE_CD END) AS ACTIVE_ALERT_COUNT,
    MAX(B.BILL_DT) AS LAST_BILL_DT,
    (
      SUM(CASE WHEN (TRUNC(:end_ts) - FT.ARS_DT) > 60 THEN FT.CUR_AMT ELSE 0 END)
      + (COUNT(DISTINCT CASE WHEN AL.ALERT_TYPE_CD IS NOT NULL THEN AL.ALERT_TYPE_CD END) * 100)
    ) AS PRIORITY_SCORE
FROM CISADM.CI_ACCT A
LEFT JOIN CISADM.CI_COLL_CL_L COLL_L
  ON COLL_L.COLL_CL_CD = A.COLL_CL_CD
 AND COLL_L.LANGUAGE_CD = 'EN'
JOIN CISADM.CI_SA SA
  ON SA.ACCT_ID = A.ACCT_ID
 AND NULLIF(TRIM(SA.SA_STATUS_FLG), '') = '20'
JOIN CISADM.CI_FT FT
  ON FT.SA_ID = SA.SA_ID
 AND FT.FREEZE_SW = 'Y'
 AND FT.NOT_IN_ARS_SW = 'N'
 AND FT.FT_TYPE_FLG NOT IN ('PS', 'PX')
 AND FT.ARS_DT IS NOT NULL
LEFT JOIN CISADM.CI_ACCT_ALERT AL
  ON AL.ACCT_ID = A.ACCT_ID
 AND :end_ts BETWEEN AL.START_DT AND NVL(AL.END_DT, :end_ts)
LEFT JOIN CISADM.CI_BILL B
  ON B.ACCT_ID = A.ACCT_ID
 AND B.BILL_DT >= :start_ts
 AND B.BILL_DT <  :end_ts
WHERE (:client_id IS NULL OR A.CIS_DIVISION = :client_id)
GROUP BY A.ACCT_ID, A.COLL_CL_CD, COLL_L.DESCR
HAVING SUM(CASE WHEN (TRUNC(:end_ts) - FT.ARS_DT) > 60 THEN FT.CUR_AMT ELSE 0 END) >= NVL(:min_debt_over_60, 0)
ORDER BY PRIORITY_SCORE DESC, DEBT_OVER_60 DESC;

-- EXPLAIN PLAN FOR
-- SELECT ... (paste query above);
-- SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY(NULL, NULL, 'BASIC +PREDICATE +ALIAS +NOTE'));
