-- GOVERNED: Customer Contact Letter Readiness KPI (read-only)
-- Binds:
--   :client_id VARCHAR2 (optional; maps to CI_ACCT.CIS_DIVISION)
--   :start_ts  TIMESTAMP
--   :end_ts    TIMESTAMP

SELECT
    CASE
      WHEN LT.LTR_TMPL_CD IS NULL THEN 'MISSING_TEMPLATE'
      WHEN NULLIF(TRIM(PN.ENTITY_NAME), '') IS NULL THEN 'MISSING_NAME'
      WHEN NULLIF(TRIM(PR.ADDRESS1), '') IS NULL THEN 'MISSING_ADDRESS'
      ELSE 'READY'
    END AS READINESS_STATUS,
    COUNT(*) AS CONTACT_COUNT
FROM CISADM.CI_CC CC
JOIN CISADM.CI_ACCT A ON A.ACCT_ID = CC.ACCT_ID
LEFT JOIN CISADM.CI_LETTER_TMPL LT ON LT.LTR_TMPL_CD = CC.LTR_TMPL_CD
LEFT JOIN CISADM.CI_PER_NAME PN ON PN.PER_ID = CC.PER_ID AND PN.PRIM_NAME_SW = 'Y'
LEFT JOIN CISADM.CI_PREM PR ON PR.PREM_ID = CC.PREM_ID
WHERE CC.PRINT_LETTER_SW = 'Y'
  AND CC.CC_DTTM >= :start_ts
  AND CC.CC_DTTM <  :end_ts
  AND (:client_id IS NULL OR A.CIS_DIVISION = :client_id)
GROUP BY
    CASE
      WHEN LT.LTR_TMPL_CD IS NULL THEN 'MISSING_TEMPLATE'
      WHEN NULLIF(TRIM(PN.ENTITY_NAME), '') IS NULL THEN 'MISSING_NAME'
      WHEN NULLIF(TRIM(PR.ADDRESS1), '') IS NULL THEN 'MISSING_ADDRESS'
      ELSE 'READY'
    END
ORDER BY READINESS_STATUS;
