-- GOVERNED: Master Payment Event & Deposit Reconciliation
-- Source: C2M.Payments.sql / C2M.Payments.DepositLabels.sql
-- For Jaspersoft JDBC evidence table only (not run by the pipeline).
-- Value: Reconciles C2M tender sources with bank deposit methods

SELECT
    PAY_EVNT.PAY_EVENT_ID,
    PAY.ACCT_ID,
    PAY.PAY_AMT,
    PAY_TNDR.TENDER_TYPE_CD,
    DEPOSITS.DEPOSIT_METHOD,
    DEPOSITS.DEPOSIT_METHOD_DETAIL,
    TNDR_CTL.TNDR_SOURCE_CD,
    DEP_CTL.DEP_CTL_ID,
    DEP_CTL.DEP_CTL_STATUS_FLG AS DEP_STATUS
FROM CISADM.CI_PAY_EVENT PAY_EVNT
JOIN CISADM.CI_PAY PAY ON PAY.PAY_EVENT_ID = PAY_EVNT.PAY_EVENT_ID
JOIN CISADM.CI_PAY_TNDR PAY_TNDR ON PAY_TNDR.PAY_EVENT_ID = PAY_EVNT.PAY_EVENT_ID
JOIN CISADM.CI_TNDR_CTL TNDR_CTL ON TNDR_CTL.TNDR_CTL_ID = PAY_TNDR.TNDR_CTL_ID
JOIN CISADM.CI_DEP_CTL DEP_CTL ON DEP_CTL.DEP_CTL_ID = TNDR_CTL.DEP_CTL_ID
JOIN (
    SELECT TS.TNDR_SOURCE_CD, T.TENDER_TYPE_CD,
    CASE
        WHEN TS.TNDR_SOURCE_CD IN ('ACH', 'LOCKBOX') THEN 'INACTIVE'
        WHEN TS.TNDR_SOURCE_CD = 'CMSPYMTS' THEN 'Bank - Electronic Capture'
        WHEN T.TENDER_TYPE_CD IN ('CASH', 'CCHK', 'MO') THEN 'Bank - Deposit Bag'
        ELSE 'Electronic/Other'
    END AS DEPOSIT_METHOD,
    TS.DESCR AS DEPOSIT_METHOD_DETAIL
    FROM CISADM.CI_TENDER_TYPE_L T
    CROSS JOIN CISADM.CI_TNDR_SRCE_L TS
) DEPOSITS ON TNDR_CTL.TNDR_SOURCE_CD = DEPOSITS.TNDR_SOURCE_CD
  AND PAY_TNDR.TENDER_TYPE_CD = DEPOSITS.TENDER_TYPE_CD
WHERE PAY.PAY_STATUS_FLG = '50';
