-- GOVERNED: Lookup Description Completeness Audit (Jaspersoft-ready, read-only)
-- Purpose: find code domains where descriptions are missing, so client-facing reports can stay description-first.
-- Binds:
--   :client_id VARCHAR2 (optional; maps to CI_ACCT.CIS_DIVISION where applicable)
--   :start_ts  TIMESTAMP
--   :end_ts    TIMESTAMP

WITH
coll_codes AS (
    SELECT DISTINCT TRIM(A.COLL_CL_CD) AS CODE
    FROM CISADM.CI_ACCT A
    WHERE NULLIF(TRIM(A.COLL_CL_CD), '') IS NOT NULL
      AND (:client_id IS NULL OR A.CIS_DIVISION = :client_id)
),
coll_desc AS (
    SELECT C.CODE, NULLIF(TRIM(L.DESCR), '') AS DESCR
    FROM coll_codes C
    LEFT JOIN CISADM.CI_COLL_CL_L L
      ON L.COLL_CL_CD = C.CODE
     AND L.LANGUAGE_CD = 'EN'
),
cc_cl_codes AS (
    SELECT DISTINCT TRIM(CC.CC_CL_CD) AS CODE
    FROM CISADM.CI_CC CC
    JOIN CISADM.CI_ACCT A ON A.ACCT_ID = CC.ACCT_ID
    WHERE NULLIF(TRIM(CC.CC_CL_CD), '') IS NOT NULL
      AND CC.CC_DTTM >= :start_ts
      AND CC.CC_DTTM <  :end_ts
      AND (:client_id IS NULL OR A.CIS_DIVISION = :client_id)
),
cc_cl_desc AS (
    SELECT C.CODE, NULLIF(TRIM(L.DESCR), '') AS DESCR
    FROM cc_cl_codes C
    LEFT JOIN CISADM.CI_CC_CL_L L
      ON L.CC_CL_CD = C.CODE
     AND L.LANGUAGE_CD = 'EN'
),
cc_type_codes AS (
    SELECT DISTINCT TRIM(CC.CC_CL_CD) AS CC_CL_CD, TRIM(CC.CC_TYPE_CD) AS CC_TYPE_CD
    FROM CISADM.CI_CC CC
    JOIN CISADM.CI_ACCT A ON A.ACCT_ID = CC.ACCT_ID
    WHERE NULLIF(TRIM(CC.CC_CL_CD), '') IS NOT NULL
      AND NULLIF(TRIM(CC.CC_TYPE_CD), '') IS NOT NULL
      AND CC.CC_DTTM >= :start_ts
      AND CC.CC_DTTM <  :end_ts
      AND (:client_id IS NULL OR A.CIS_DIVISION = :client_id)
),
cc_type_desc AS (
    SELECT
        C.CC_CL_CD || ':' || C.CC_TYPE_CD AS CODE,
        NULLIF(TRIM(L.DESCR), '') AS DESCR
    FROM cc_type_codes C
    LEFT JOIN CISADM.CI_CC_TYPE_L L
      ON L.CC_CL_CD = C.CC_CL_CD
     AND L.CC_TYPE_CD = C.CC_TYPE_CD
     AND L.LANGUAGE_CD = 'EN'
),
bill_stat_codes AS (
    SELECT DISTINCT TRIM(B.BILL_STAT_FLG) AS CODE
    FROM CISADM.CI_BILL B
    JOIN CISADM.CI_ACCT A ON A.ACCT_ID = B.ACCT_ID
    WHERE NULLIF(TRIM(B.BILL_STAT_FLG), '') IS NOT NULL
      AND B.CRE_DTTM >= :start_ts
      AND B.CRE_DTTM <  :end_ts
      AND (:client_id IS NULL OR A.CIS_DIVISION = :client_id)
),
bill_stat_desc AS (
    SELECT C.CODE, NULLIF(TRIM(LU.VALUE_NAME), '') AS DESCR
    FROM bill_stat_codes C
    LEFT JOIN CISADM.CI_LOOKUP_VAL LU
      ON TRIM(LU.FIELD_NAME) = 'BILL_STAT_FLG'
     AND TRIM(LU.FIELD_VALUE) = C.CODE
),
bseg_stat_codes AS (
    SELECT DISTINCT TRIM(S.BSEG_STAT_FLG) AS CODE
    FROM CISADM.CI_BSEG S
    JOIN CISADM.CI_BILL B ON B.BILL_ID = S.BILL_ID
    JOIN CISADM.CI_ACCT A ON A.ACCT_ID = B.ACCT_ID
    WHERE NULLIF(TRIM(S.BSEG_STAT_FLG), '') IS NOT NULL
      AND S.CRE_DTTM >= :start_ts
      AND S.CRE_DTTM <  :end_ts
      AND (:client_id IS NULL OR A.CIS_DIVISION = :client_id)
),
bseg_stat_desc AS (
    SELECT C.CODE, NULLIF(TRIM(LU.VALUE_NAME), '') AS DESCR
    FROM bseg_stat_codes C
    LEFT JOIN CISADM.CI_LOOKUP_VAL LU
      ON TRIM(LU.FIELD_NAME) = 'BSEG_STAT_FLG'
     AND TRIM(LU.FIELD_VALUE) = C.CODE
),
alert_type_codes AS (
    SELECT DISTINCT TRIM(AL.ALERT_TYPE_CD) AS CODE
    FROM CISADM.CI_ACCT_ALERT AL
    JOIN CISADM.CI_ACCT A ON A.ACCT_ID = AL.ACCT_ID
    WHERE NULLIF(TRIM(AL.ALERT_TYPE_CD), '') IS NOT NULL
      AND AL.START_DT >= :start_ts
      AND AL.START_DT <  :end_ts
      AND (:client_id IS NULL OR A.CIS_DIVISION = :client_id)
),
alert_type_desc AS (
    SELECT C.CODE, NULLIF(TRIM(L.DESCR80), '') AS DESCR
    FROM alert_type_codes C
    LEFT JOIN CISADM.CI_ALERT_TYPE_L L
      ON L.ALERT_TYPE_CD = C.CODE
     AND L.LANGUAGE_CD = 'EN'
),
tender_type_codes AS (
    SELECT DISTINCT TRIM(PT.TENDER_TYPE_CD) AS CODE
    FROM CISADM.CI_PAY_TNDR PT
    JOIN CISADM.CI_PAY P ON P.PAY_EVENT_ID = PT.PAY_EVENT_ID
    JOIN CISADM.CI_PAY_EVENT PE ON PE.PAY_EVENT_ID = PT.PAY_EVENT_ID
    JOIN CISADM.CI_ACCT A ON A.ACCT_ID = P.ACCT_ID
    WHERE NULLIF(TRIM(PT.TENDER_TYPE_CD), '') IS NOT NULL
      AND PE.CRE_DTTM >= :start_ts
      AND PE.CRE_DTTM <  :end_ts
      AND (:client_id IS NULL OR A.CIS_DIVISION = :client_id)
),
tender_type_desc AS (
    SELECT C.CODE, NULLIF(TRIM(L.DESCR), '') AS DESCR
    FROM tender_type_codes C
    LEFT JOIN CISADM.CI_TENDER_TYPE_L L
      ON L.TENDER_TYPE_CD = C.CODE
     AND L.LANGUAGE_CD = 'EN'
)
SELECT DOMAIN_FIELD,
       TOTAL_DISTINCT_VALUES,
       MISSING_DESCRIPTIONS,
       COVERAGE_PCT,
       MISSING_SAMPLES
FROM (
    SELECT
        'COLL_CL_CD' AS DOMAIN_FIELD,
        COUNT(*) AS TOTAL_DISTINCT_VALUES,
        SUM(CASE WHEN DESCR IS NULL THEN 1 ELSE 0 END) AS MISSING_DESCRIPTIONS,
        ROUND(100 * (COUNT(*) - SUM(CASE WHEN DESCR IS NULL THEN 1 ELSE 0 END)) / NULLIF(COUNT(*), 0), 2) AS COVERAGE_PCT,
        LISTAGG(CASE WHEN DESCR IS NULL THEN CODE END, ', ') WITHIN GROUP (ORDER BY CODE) AS MISSING_SAMPLES
    FROM coll_desc

    UNION ALL
    SELECT
        'CC_CL_CD',
        COUNT(*),
        SUM(CASE WHEN DESCR IS NULL THEN 1 ELSE 0 END),
        ROUND(100 * (COUNT(*) - SUM(CASE WHEN DESCR IS NULL THEN 1 ELSE 0 END)) / NULLIF(COUNT(*), 0), 2),
        LISTAGG(CASE WHEN DESCR IS NULL THEN CODE END, ', ') WITHIN GROUP (ORDER BY CODE)
    FROM cc_cl_desc

    UNION ALL
    SELECT
        'CC_TYPE_CD',
        COUNT(*),
        SUM(CASE WHEN DESCR IS NULL THEN 1 ELSE 0 END),
        ROUND(100 * (COUNT(*) - SUM(CASE WHEN DESCR IS NULL THEN 1 ELSE 0 END)) / NULLIF(COUNT(*), 0), 2),
        LISTAGG(CASE WHEN DESCR IS NULL THEN CODE END, ', ') WITHIN GROUP (ORDER BY CODE)
    FROM cc_type_desc

    UNION ALL
    SELECT
        'BILL_STAT_FLG',
        COUNT(*),
        SUM(CASE WHEN DESCR IS NULL THEN 1 ELSE 0 END),
        ROUND(100 * (COUNT(*) - SUM(CASE WHEN DESCR IS NULL THEN 1 ELSE 0 END)) / NULLIF(COUNT(*), 0), 2),
        LISTAGG(CASE WHEN DESCR IS NULL THEN CODE END, ', ') WITHIN GROUP (ORDER BY CODE)
    FROM bill_stat_desc

    UNION ALL
    SELECT
        'BSEG_STAT_FLG',
        COUNT(*),
        SUM(CASE WHEN DESCR IS NULL THEN 1 ELSE 0 END),
        ROUND(100 * (COUNT(*) - SUM(CASE WHEN DESCR IS NULL THEN 1 ELSE 0 END)) / NULLIF(COUNT(*), 0), 2),
        LISTAGG(CASE WHEN DESCR IS NULL THEN CODE END, ', ') WITHIN GROUP (ORDER BY CODE)
    FROM bseg_stat_desc

    UNION ALL
    SELECT
        'ALERT_TYPE_CD',
        COUNT(*),
        SUM(CASE WHEN DESCR IS NULL THEN 1 ELSE 0 END),
        ROUND(100 * (COUNT(*) - SUM(CASE WHEN DESCR IS NULL THEN 1 ELSE 0 END)) / NULLIF(COUNT(*), 0), 2),
        LISTAGG(CASE WHEN DESCR IS NULL THEN CODE END, ', ') WITHIN GROUP (ORDER BY CODE)
    FROM alert_type_desc

    UNION ALL
    SELECT
        'TENDER_TYPE_CD',
        COUNT(*),
        SUM(CASE WHEN DESCR IS NULL THEN 1 ELSE 0 END),
        ROUND(100 * (COUNT(*) - SUM(CASE WHEN DESCR IS NULL THEN 1 ELSE 0 END)) / NULLIF(COUNT(*), 0), 2),
        LISTAGG(CASE WHEN DESCR IS NULL THEN CODE END, ', ') WITHIN GROUP (ORDER BY CODE)
    FROM tender_type_desc
)
ORDER BY DOMAIN_FIELD;
