-- Bind variables: :CLIENT_ID, :START_TS, :END_TS, :THRESHOLD_HOURS, :REGION
EXPLAIN PLAN FOR
WITH PARAMS AS (
    SELECT (:END_TS - NUMTODSINTERVAL(:THRESHOLD_HOURS, 'HOUR')) AS THRESHOLD_TS FROM DUAL
),
READING_AGG AS (
    SELECT R.METER_ID, MAX(R.READING_TS) AS LAST_READING_TS
    FROM CISADM.METER_READINGS R
    WHERE R.READING_TS >= :START_TS
      AND R.READING_TS <  :END_TS
    GROUP BY R.METER_ID
)
SELECT
    M.METER_ID,
    M.LAT AS LATITUDE,
    M.LON AS LONGITUDE,
    M.ADDRESS,
    RA.LAST_READING_TS,
    CASE
      WHEN RA.LAST_READING_TS IS NULL THEN 'NO_DATA'
      WHEN RA.LAST_READING_TS < (SELECT THRESHOLD_TS FROM PARAMS) THEN 'NO_DATA'
      ELSE 'OK'
    END AS STATUS
FROM CISADM.METERS M
LEFT JOIN READING_AGG RA ON RA.METER_ID = M.METER_ID
WHERE M.CLIENT_ID = :CLIENT_ID
  AND (:REGION IS NULL OR M.WORK_REGION = :REGION)
  AND M.LAT IS NOT NULL
  AND M.LON IS NOT NULL
  AND (
      RA.LAST_READING_TS IS NULL
      OR RA.LAST_READING_TS < (SELECT THRESHOLD_TS FROM PARAMS)
  )
ORDER BY M.METER_ID;

SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY(NULL, NULL, 'ALL +PREDICATE +PARTITION +PEEKED_BINDS'));

-- Index recommendations
-- CREATE INDEX CISADM.IDX_MR_METER_TS_L
--   ON CISADM.METER_READINGS (METER_ID, READING_TS) LOCAL;
-- CREATE INDEX CISADM.IDX_METERS_CLIENT_REGION
--   ON CISADM.METERS (CLIENT_ID, WORK_REGION, METER_ID);

-- Rollback plan
-- DROP INDEX CISADM.IDX_MR_METER_TS_L;
-- DROP INDEX CISADM.IDX_METERS_CLIENT_REGION;
