"""Which portal modules each client actually uses, as measured on its own CISADM.

config/client_capabilities.json is GENERATED by originba_dbt/scripts/client_capability_profile.py
(keyed by the dbt client id, each row naming its portal organization). A module is hidden only
when the measurement says the client does not use it: an unmeasured client, an undecided
switch or a missing file leaves every module on.
"""
from __future__ import annotations

import json
from pathlib import Path

CAPABILITIES_PATH = Path(__file__).resolve().parent.parent / "config" / "client_capabilities.json"
MODULES = ("letters",)


def _features(organization_id: str | None) -> dict:
    try:
        measured = json.loads(CAPABILITIES_PATH.read_text())
    except (OSError, ValueError):
        return {}
    for client_id, row in measured.items():
        if organization_id and row.get("portal_org_id", client_id) == organization_id:
            return row.get("features") or {}
    return {}


def module_enabled(organization_id: str | None, module: str) -> bool:
    return _features(organization_id).get(module) is not False


def modules_for_organization(organization_id: str | None) -> dict[str, bool]:
    features = _features(organization_id)
    return {m: features.get(m) is not False for m in MODULES}
