-- Staging smoke schema for report validation (non-production)
-- Safe to run in DEV/QA staging schema only.

CREATE TABLE STG_CUSTOMERS (
    CLIENT_ID      VARCHAR2(50) NOT NULL,
    CUSTOMER_ID    NUMBER       NOT NULL,
    CUSTOMER_NAME  VARCHAR2(200) NOT NULL,
    CONSTRAINT PK_STG_CUSTOMERS PRIMARY KEY (CLIENT_ID, CUSTOMER_ID)
);

CREATE TABLE STG_BILL_LINE_ITEMS (
    CLIENT_ID       VARCHAR2(50) NOT NULL,
    BILL_ID         NUMBER       NOT NULL,
    CUSTOMER_ID     NUMBER       NOT NULL,
    LINE_ID         NUMBER       NOT NULL,
    BILL_DATE       DATE         NOT NULL,
    DUE_DATE        DATE         NOT NULL,
    ITEM_CODE       VARCHAR2(50),
    ITEM_DESCRIPTION VARCHAR2(200),
    QUANTITY        NUMBER(12,3),
    UNIT_PRICE      NUMBER(12,2),
    LINE_AMOUNT     NUMBER(12,2),
    CONSTRAINT PK_STG_BILL_LINE_ITEMS PRIMARY KEY (CLIENT_ID, BILL_ID, LINE_ID)
);

CREATE INDEX IX_STG_BLI_CLIENT_BILL ON STG_BILL_LINE_ITEMS (CLIENT_ID, BILL_ID);
CREATE INDEX IX_STG_BLI_CLIENT_BILLDT ON STG_BILL_LINE_ITEMS (CLIENT_ID, BILL_DATE);
